// Package agentsapi embeds the generated OpenAPI documents of Core's three
// namespaces so Core can serve them at /docs.
package agentsapi

import "embed"

// OpenAPI holds openapi.yaml (/v1), core.openapi.yaml (/core/v1) and
// runtime.openapi.yaml (/api/v1), as generated by make openapi.
//
//go:embed openapi.yaml core.openapi.yaml runtime.openapi.yaml
var OpenAPI embed.FS
