/** Retired server-side settings fail before Vite reads credentials or builds browser configuration. */
const retiredSettings = {
  AGENTS_API_PROXY_TARGET: "OAC_WEB_DEV_PROXY_TARGET",
  AGENTS_API_PROXY_TOKEN: "OAC_WEB_DEV_PROXY_TOKEN",
  AGENTS_API_PROXY_TOKEN_FILE: "OAC_WEB_DEV_PROXY_TOKEN_FILE",
  AGENTS_CORE_WEB_SELF_HOSTED_SESSIONS: "OAC_WEB_SELF_HOSTED_SESSIONS",
  AGENTS_CORE_WEB_OPENAI_HOSTED_SESSIONS: "OAC_WEB_OPENAI_HOSTED_SESSIONS",
  AGENTS_CORE_WEB_ENVIRONMENT_FILES: "OAC_WEB_ENVIRONMENT_FILES",
  AGENTS_CORE_WEB_DOCKER_GUIDE: "OAC_WEB_DOCKER_GUIDE",
  AGENTS_CORE_WEB_DOCKER_IMAGE: "OAC_WEB_DOCKER_IMAGE",
  AGENTS_CORE_WEB_DOCKER_API_CONTAINER: "OAC_WEB_DOCKER_API_CONTAINER",
  AGENTS_CORE_WEB_DOCKER_USER: "OAC_WEB_DOCKER_USER",
  AGENTS_CORE_WEB_DOCKER_CREDENTIALS_HOME_PATH: "OAC_WEB_DOCKER_CREDENTIALS_HOME_PATH",
  AGENTS_CORE_WEB_DOCKER_RUNTIME_HOME_PATH: "OAC_WEB_DOCKER_RUNTIME_HOME_PATH",
  AGENTS_CORE_WEB_DOCKER_BACKEND_GUIDE: "OAC_WEB_DOCKER_BACKEND_GUIDE",
  AGENTS_CORE_WEB_DOCKER_DATABASE_CONTAINER: "OAC_WEB_DOCKER_DATABASE_CONTAINER",
  AGENTS_CORE_WEB_DOCKER_DAEMON_CONTAINER: "OAC_WEB_DOCKER_DAEMON_CONTAINER",
  AGENTS_CORE_WEB_DOCKER_CORE_PORT: "OAC_WEB_DOCKER_CORE_PORT",
} as const;

export function assertCurrentWebSettings(env: Record<string, string>): void {
  const retired = Object.entries(retiredSettings).filter(([name]) => Object.hasOwn(env, name));
  if (retired.length) {
    throw new Error(`Retired Web settings: ${retired.map(([name, replacement]) => `${name} is no longer supported; use ${replacement}`).join(". ")}.`);
  }
}
