package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// oacProviderSlug is the model_provider key the daemon always writes
// into CODEX_HOME/config.toml. The session's thread/start request pins
// model_provider to this slug, so codex skips its builtin "openai"
// provider entirely and routes through the values we materialise here.
// Hardcoded (not configurable) on purpose — keeping it a constant makes
// the config.toml deterministic and removes a footgun where two prompts
// in the same CODEX_HOME could disagree on which provider to use.
const oacProviderSlug = "oac"

// providerConfig is the daemon-internal view of the model provider the
// Runtime prepared for this Session. Flattened from the common
// agent_options["model_provider"] bundle into a typed
// struct before TOML emission. Field names mirror the codex-rs
// ModelProviderInfo enum (model-provider-info/src/lib.rs) so the
// rendered TOML deserialises 1:1 against upstream.
type providerConfig struct {
	// Name is the human-readable label shown in codex UI; defaults to
	// "OpenAgentCore" when empty.
	Name string
	// BaseURL is the model provider's HTTPS endpoint, including any
	// path prefix (e.g. /v1). Required.
	BaseURL string
	// BearerToken is the literal API key. Codex's `experimental_bearer_token`
	// field accepts a string; we emit it verbatim. Required.
	BearerToken string
	// HTTPHeaders is forwarded as `[model_providers.oac.http_headers]`.
	// Keys / values rendered as TOML basic strings.
	HTTPHeaders map[string]string
	// QueryParams is forwarded as `[model_providers.oac.query_params]`,
	// used by Azure (api-version=2025-04-01-preview).
	QueryParams map[string]string
	// WireAPI is "responses" (codex Responses API) or "chat" (rejected
	// upstream since codex-rs 0.140). Empty defaults to "responses".
	WireAPI string
	// RequestMaxRetries / StreamMaxRetries map to codex's
	// request_max_retries / stream_max_retries config keys. 0 omits.
	RequestMaxRetries int
	StreamMaxRetries  int
}

// writeCodexProviderConfig writes (or appends to) <codexHome>/config.toml
// with a `[model_providers.<oacProviderSlug>]` block built from cfg.
//
// The file is appended to — writeCodexMCPConfig also writes config.toml
// for MCP servers, and both writers run on the same prompt. Order is
// not load-bearing on codex's side (TOML is a flat key-set), but we keep
// the provider block at the top so a human inspecting the scratch dir
// sees the auth + endpoint first.
//
// The provider block is rewritten on every prompt; manual edits to
// scratch CODEX_HOME files are lost on the next spawn.
func writeCodexProviderConfig(codexHome string, cfg providerConfig) error {
	if err := os.MkdirAll(codexHome, 0o700); err != nil {
		return fmt.Errorf("codex: mkdir CODEX_HOME %s: %w", codexHome, err)
	}
	if strings.TrimSpace(cfg.BaseURL) == "" {
		return fmt.Errorf("codex: provider base_url is required")
	}
	if strings.TrimSpace(cfg.BearerToken) == "" {
		return fmt.Errorf("codex: provider bearer_token is required")
	}

	var b strings.Builder
	b.WriteString("# Generated by oac-daemon (codex agent) — do not edit by hand.\n")
	b.WriteString("# Rewritten on every prompt; manual changes will be lost.\n\n")

	b.WriteString("[model_providers.")
	b.WriteString(oacProviderSlug)
	b.WriteString("]\n")

	name := strings.TrimSpace(cfg.Name)
	if name == "" {
		name = "OpenAgentCore"
	}
	b.WriteString("name = ")
	b.WriteString(tomlQuoteString(name))
	b.WriteByte('\n')

	b.WriteString("base_url = ")
	b.WriteString(tomlQuoteString(cfg.BaseURL))
	b.WriteByte('\n')

	b.WriteString("experimental_bearer_token = ")
	b.WriteString(tomlQuoteString(cfg.BearerToken))
	b.WriteByte('\n')

	wireAPI := strings.TrimSpace(cfg.WireAPI)
	if wireAPI == "" {
		// Codex-rs has removed the "chat" variant; "responses" is the
		// only accepted value. Default explicitly so a future enum
		// addition can't silently flip the wire shape under us.
		wireAPI = "responses"
	}
	b.WriteString("wire_api = ")
	b.WriteString(tomlQuoteString(wireAPI))
	b.WriteByte('\n')

	if cfg.RequestMaxRetries > 0 {
		fmt.Fprintf(&b, "request_max_retries = %d\n", cfg.RequestMaxRetries)
	}
	if cfg.StreamMaxRetries > 0 {
		fmt.Fprintf(&b, "stream_max_retries = %d\n", cfg.StreamMaxRetries)
	}

	if len(cfg.HTTPHeaders) > 0 {
		keys := make([]string, 0, len(cfg.HTTPHeaders))
		for k := range cfg.HTTPHeaders {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\n[model_providers.")
		b.WriteString(oacProviderSlug)
		b.WriteString(".http_headers]\n")
		for _, k := range keys {
			b.WriteString(tomlQuoteString(k))
			b.WriteString(" = ")
			b.WriteString(tomlQuoteString(cfg.HTTPHeaders[k]))
			b.WriteByte('\n')
		}
	}

	if len(cfg.QueryParams) > 0 {
		keys := make([]string, 0, len(cfg.QueryParams))
		for k := range cfg.QueryParams {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\n[model_providers.")
		b.WriteString(oacProviderSlug)
		b.WriteString(".query_params]\n")
		for _, k := range keys {
			b.WriteString(tomlQuoteString(k))
			b.WriteString(" = ")
			b.WriteString(tomlQuoteString(cfg.QueryParams[k]))
			b.WriteByte('\n')
		}
	}

	b.WriteByte('\n')

	path := filepath.Join(codexHome, "config.toml")
	return appendConfigTOML(path, b.String())
}

// appendConfigTOML appends body to <codexHome>/config.toml, creating it
// when missing. Used so writeCodexProviderConfig and writeCodexMCPConfig
// (which target the same file) can cohabit without one truncating the
// other.
//
// File is opened O_APPEND so concurrent writers in the same prompt
// (today: at most one of each) don't race. 0o600 perms because the
// file carries the API bearer token in plaintext.
func appendConfigTOML(path string, body string) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("codex: open %s: %w", path, err)
	}
	defer f.Close()
	if _, err := f.WriteString(body); err != nil {
		return fmt.Errorf("codex: append %s: %w", path, err)
	}
	return nil
}
