// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_model_execution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentModelExecution = `-- name: DeleteAgentModelExecution :exec
DELETE FROM agent_model_execution WHERE agent_id = $1
`

func (q *Queries) DeleteAgentModelExecution(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentModelExecution, agentID)
	return err
}

const getAgentWithModelExecution = `-- name: GetAgentWithModelExecution :one
SELECT a.id, a.tenant_id, a.metadata, a.configuration, a.created_at, a.updated_at, e.encrypted_config FROM agents a
LEFT JOIN agent_model_execution e ON e.agent_id = a.id
WHERE a.tenant_id = $1 AND a.id = $2
`

type GetAgentWithModelExecutionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
}

type GetAgentWithModelExecutionRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Metadata        []byte             `json:"metadata"`
	Configuration   []byte             `json:"configuration"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	EncryptedConfig []byte             `json:"encrypted_config"`
}

func (q *Queries) GetAgentWithModelExecution(ctx context.Context, arg GetAgentWithModelExecutionParams) (GetAgentWithModelExecutionRow, error) {
	row := q.db.QueryRow(ctx, getAgentWithModelExecution, arg.TenantID, arg.AgentID)
	var i GetAgentWithModelExecutionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptedConfig,
	)
	return i, err
}

const saveAgentModelExecution = `-- name: SaveAgentModelExecution :exec
INSERT INTO agent_model_execution(agent_id, encrypted_config) VALUES ($1, $2)
ON CONFLICT (agent_id) DO UPDATE SET encrypted_config = EXCLUDED.encrypted_config
`

type SaveAgentModelExecutionParams struct {
	AgentID         pgtype.UUID `json:"agent_id"`
	EncryptedConfig []byte      `json:"encrypted_config"`
}

func (q *Queries) SaveAgentModelExecution(ctx context.Context, arg SaveAgentModelExecutionParams) error {
	_, err := q.db.Exec(ctx, saveAgentModelExecution, arg.AgentID, arg.EncryptedConfig)
	return err
}
