// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, tenant_id, metadata, configuration)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, metadata, configuration, created_at, updated_at
`

type CreateAgentParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Metadata      []byte      `json:"metadata"`
	Configuration []byte      `json:"configuration"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.TenantID,
		arg.Metadata,
		arg.Configuration,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :one
DELETE FROM agents WHERE tenant_id = $1 AND id = $2 RETURNING id
`

type DeleteAgentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAgent, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, tenant_id, metadata, configuration, created_at, updated_at FROM agents WHERE tenant_id = $1 AND id = $2
`

type GetAgentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.TenantID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, tenant_id, metadata, configuration, created_at, updated_at FROM agents
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL
       OR (NOT $3::boolean AND (created_at, id) < ($2::timestamptz, $4::uuid))
       OR ($3::boolean AND (created_at, id) > ($2::timestamptz, $4::uuid)))
ORDER BY
    CASE WHEN $3::boolean THEN created_at END ASC,
    CASE WHEN $3::boolean THEN id END ASC,
    CASE WHEN NOT $3::boolean THEN created_at END DESC,
    CASE WHEN NOT $3::boolean THEN id END DESC
LIMIT $5
`

type ListAgentsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents,
		arg.TenantID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Metadata,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgent = `-- name: LockAgent :one
SELECT id, tenant_id, metadata, configuration, created_at, updated_at FROM agents WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockAgentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockAgent(ctx context.Context, arg LockAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgent, arg.TenantID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET configuration = $3, metadata = $4, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, metadata, configuration, created_at, updated_at
`

type UpdateAgentParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ID            pgtype.UUID `json:"id"`
	Configuration []byte      `json:"configuration"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.TenantID,
		arg.ID,
		arg.Configuration,
		arg.Metadata,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Metadata,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
