// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: core_metrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const coreDatabaseSize = `-- name: CoreDatabaseSize :one
SELECT pg_database_size(current_database())::bigint
`

func (q *Queries) CoreDatabaseSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, coreDatabaseSize)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const coreExecutionSnapshot = `-- name: CoreExecutionSnapshot :one
SELECT count(*) FILTER (WHERE t.status = 'queued')::bigint AS queued_turns,
    count(*) FILTER (WHERE t.status = 'queued' AND
        (b.device_id IS NULL OR NOT (b.device_id = ANY($1::uuid[]))))::bigint AS waiting_for_daemon,
    count(*) FILTER (WHERE t.status = 'in_progress')::bigint AS in_progress_turns,
    COALESCE(GREATEST(0, extract(epoch FROM ($2::timestamptz -
        min(t.created_at) FILTER (WHERE t.status = 'queued')))), 0)::double precision AS oldest_queued_seconds
FROM turns t LEFT JOIN session_devices b ON b.session_id = t.session_id
WHERE t.status IN ('queued', 'in_progress')
`

type CoreExecutionSnapshotParams struct {
	ConnectedDeviceIds []pgtype.UUID      `json:"connected_device_ids"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
}

type CoreExecutionSnapshotRow struct {
	QueuedTurns         int64   `json:"queued_turns"`
	WaitingForDaemon    int64   `json:"waiting_for_daemon"`
	InProgressTurns     int64   `json:"in_progress_turns"`
	OldestQueuedSeconds float64 `json:"oldest_queued_seconds"`
}

func (q *Queries) CoreExecutionSnapshot(ctx context.Context, arg CoreExecutionSnapshotParams) (CoreExecutionSnapshotRow, error) {
	row := q.db.QueryRow(ctx, coreExecutionSnapshot, arg.ConnectedDeviceIds, arg.ObservedAt)
	var i CoreExecutionSnapshotRow
	err := row.Scan(
		&i.QueuedTurns,
		&i.WaitingForDaemon,
		&i.InProgressTurns,
		&i.OldestQueuedSeconds,
	)
	return i, err
}

const coreInterruptedTurns = `-- name: CoreInterruptedTurns :one
SELECT count(*)::bigint FROM turns
WHERE status = 'failed' AND outcome->>'error_code' = 'execution_interrupted'
    AND completed_at >= $1::timestamptz
    AND completed_at < $2::timestamptz
`

type CoreInterruptedTurnsParams struct {
	RangeStart pgtype.Timestamptz `json:"range_start"`
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
}

func (q *Queries) CoreInterruptedTurns(ctx context.Context, arg CoreInterruptedTurnsParams) (int64, error) {
	row := q.db.QueryRow(ctx, coreInterruptedTurns, arg.RangeStart, arg.RangeEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const coreQueueWaitBuckets = `-- name: CoreQueueWaitBuckets :many
SELECT floor(extract(epoch FROM (started_at - $1::timestamptz)) /
        $2::integer)::integer AS bucket_number,
    count(*)::bigint AS samples,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (started_at - created_at)) * 1000), 0)::double precision AS p95_ms
FROM turns
WHERE started_at >= $1::timestamptz
    AND started_at < $3::timestamptz
GROUP BY bucket_number
ORDER BY bucket_number
`

type CoreQueueWaitBucketsParams struct {
	RangeStart        pgtype.Timestamptz `json:"range_start"`
	ResolutionSeconds int32              `json:"resolution_seconds"`
	RangeEnd          pgtype.Timestamptz `json:"range_end"`
}

type CoreQueueWaitBucketsRow struct {
	BucketNumber int32   `json:"bucket_number"`
	Samples      int64   `json:"samples"`
	P95Ms        float64 `json:"p95_ms"`
}

func (q *Queries) CoreQueueWaitBuckets(ctx context.Context, arg CoreQueueWaitBucketsParams) ([]CoreQueueWaitBucketsRow, error) {
	rows, err := q.db.Query(ctx, coreQueueWaitBuckets, arg.RangeStart, arg.ResolutionSeconds, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreQueueWaitBucketsRow{}
	for rows.Next() {
		var i CoreQueueWaitBucketsRow
		if err := rows.Scan(&i.BucketNumber, &i.Samples, &i.P95Ms); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coreQueueWaitSummary = `-- name: CoreQueueWaitSummary :one
SELECT count(*)::bigint AS samples,
    COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY extract(epoch FROM (started_at - created_at)) * 1000), 0)::double precision AS p50_ms,
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY extract(epoch FROM (started_at - created_at)) * 1000), 0)::double precision AS p95_ms
FROM turns
WHERE started_at >= $1::timestamptz
    AND started_at < $2::timestamptz
`

type CoreQueueWaitSummaryParams struct {
	RangeStart pgtype.Timestamptz `json:"range_start"`
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
}

type CoreQueueWaitSummaryRow struct {
	Samples int64   `json:"samples"`
	P50Ms   float64 `json:"p50_ms"`
	P95Ms   float64 `json:"p95_ms"`
}

func (q *Queries) CoreQueueWaitSummary(ctx context.Context, arg CoreQueueWaitSummaryParams) (CoreQueueWaitSummaryRow, error) {
	row := q.db.QueryRow(ctx, coreQueueWaitSummary, arg.RangeStart, arg.RangeEnd)
	var i CoreQueueWaitSummaryRow
	err := row.Scan(&i.Samples, &i.P50Ms, &i.P95Ms)
	return i, err
}
