// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deployment_model_providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeploymentModelProvider = `-- name: DeleteDeploymentModelProvider :execrows
DELETE FROM deployment_model_providers WHERE harness = $1
`

func (q *Queries) DeleteDeploymentModelProvider(ctx context.Context, harness string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeploymentModelProvider, harness)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeploymentModelProviderSecret = `-- name: GetDeploymentModelProviderSecret :one
SELECT encrypted_config, revision FROM deployment_model_providers WHERE harness = $1
`

type GetDeploymentModelProviderSecretRow struct {
	EncryptedConfig []byte      `json:"encrypted_config"`
	Revision        pgtype.UUID `json:"revision"`
}

func (q *Queries) GetDeploymentModelProviderSecret(ctx context.Context, harness string) (GetDeploymentModelProviderSecretRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentModelProviderSecret, harness)
	var i GetDeploymentModelProviderSecretRow
	err := row.Scan(&i.EncryptedConfig, &i.Revision)
	return i, err
}

const listDeploymentModelProviders = `-- name: ListDeploymentModelProviders :many
SELECT harness, protocol, base_url, context_window, max_output_tokens, model, harness_config, updated_at, last_used_at, last_error_code, last_error_at
FROM deployment_model_providers ORDER BY harness
`

type ListDeploymentModelProvidersRow struct {
	Harness         string             `json:"harness"`
	Protocol        string             `json:"protocol"`
	BaseUrl         string             `json:"base_url"`
	ContextWindow   int32              `json:"context_window"`
	MaxOutputTokens int32              `json:"max_output_tokens"`
	Model           string             `json:"model"`
	HarnessConfig   []byte             `json:"harness_config"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	LastErrorCode   pgtype.Text        `json:"last_error_code"`
	LastErrorAt     pgtype.Timestamptz `json:"last_error_at"`
}

func (q *Queries) ListDeploymentModelProviders(ctx context.Context) ([]ListDeploymentModelProvidersRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentModelProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentModelProvidersRow{}
	for rows.Next() {
		var i ListDeploymentModelProvidersRow
		if err := rows.Scan(
			&i.Harness,
			&i.Protocol,
			&i.BaseUrl,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Model,
			&i.HarnessConfig,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.LastErrorCode,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeploymentModelProvider = `-- name: UpsertDeploymentModelProvider :one
INSERT INTO deployment_model_providers (harness, protocol, base_url, context_window, max_output_tokens, model, harness_config, encrypted_config, revision, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, clock_timestamp())
ON CONFLICT (harness) DO UPDATE SET protocol = EXCLUDED.protocol, base_url = EXCLUDED.base_url,
    context_window = EXCLUDED.context_window, max_output_tokens = EXCLUDED.max_output_tokens,
    model = EXCLUDED.model, harness_config = EXCLUDED.harness_config, encrypted_config = EXCLUDED.encrypted_config, revision = EXCLUDED.revision, updated_at = EXCLUDED.updated_at,
    last_used_at = NULL, last_error_code = NULL, last_error_at = NULL, recovery_pending = false
RETURNING harness, protocol, base_url, context_window, max_output_tokens, model, harness_config, updated_at, last_used_at, last_error_code, last_error_at
`

type UpsertDeploymentModelProviderParams struct {
	Harness         string      `json:"harness"`
	Protocol        string      `json:"protocol"`
	BaseUrl         string      `json:"base_url"`
	ContextWindow   int32       `json:"context_window"`
	MaxOutputTokens int32       `json:"max_output_tokens"`
	Model           string      `json:"model"`
	HarnessConfig   []byte      `json:"harness_config"`
	EncryptedConfig []byte      `json:"encrypted_config"`
	Revision        pgtype.UUID `json:"revision"`
}

type UpsertDeploymentModelProviderRow struct {
	Harness         string             `json:"harness"`
	Protocol        string             `json:"protocol"`
	BaseUrl         string             `json:"base_url"`
	ContextWindow   int32              `json:"context_window"`
	MaxOutputTokens int32              `json:"max_output_tokens"`
	Model           string             `json:"model"`
	HarnessConfig   []byte             `json:"harness_config"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	LastErrorCode   pgtype.Text        `json:"last_error_code"`
	LastErrorAt     pgtype.Timestamptz `json:"last_error_at"`
}

func (q *Queries) UpsertDeploymentModelProvider(ctx context.Context, arg UpsertDeploymentModelProviderParams) (UpsertDeploymentModelProviderRow, error) {
	row := q.db.QueryRow(ctx, upsertDeploymentModelProvider,
		arg.Harness,
		arg.Protocol,
		arg.BaseUrl,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Model,
		arg.HarnessConfig,
		arg.EncryptedConfig,
		arg.Revision,
	)
	var i UpsertDeploymentModelProviderRow
	err := row.Scan(
		&i.Harness,
		&i.Protocol,
		&i.BaseUrl,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Model,
		&i.HarnessConfig,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.LastErrorCode,
		&i.LastErrorAt,
	)
	return i, err
}
