// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindSessionDevice = `-- name: BindSessionDevice :one
INSERT INTO session_devices (session_id, device_id)
SELECT s.id, d.id FROM sessions s JOIN devices d ON d.tenant_id = s.tenant_id
WHERE s.tenant_id = $1 AND s.id = $2 AND d.id = $3 AND d.revoked_at IS NULL
AND (d.environment_id IS NULL OR EXISTS (
    SELECT 1 FROM environments e WHERE e.id = d.environment_id AND e.session_id = s.id
))
ON CONFLICT (session_id) DO UPDATE SET device_id = session_devices.device_id
WHERE session_devices.device_id = EXCLUDED.device_id
RETURNING device_id
`

type BindSessionDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	ID_2     pgtype.UUID `json:"id_2"`
}

func (q *Queries) BindSessionDevice(ctx context.Context, arg BindSessionDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, bindSessionDevice, arg.TenantID, arg.ID, arg.ID_2)
	var device_id pgtype.UUID
	err := row.Scan(&device_id)
	return device_id, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, tenant_id, name, credential_hash)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateDeviceParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	Name           string      `json:"name"`
	CredentialHash pgtype.Text `json:"credential_hash"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CredentialHash,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name FROM devices WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL
`

type GetDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetDeviceRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (GetDeviceRow, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.TenantID, arg.ID)
	var i GetDeviceRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDeviceCredential = `-- name: GetDeviceCredential :one
SELECT d.id, d.name, d.credential_hash, COALESCE(a.node_id::text, '')::text AS runtime_node_id, COALESCE(a.id::text, '')::text AS runtime_allocation_id
FROM runtime_device_authority d
LEFT JOIN runtime_allocations a ON a.device_id = d.id
WHERE d.id = $1
`

type GetDeviceCredentialRow struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	CredentialHash      string      `json:"credential_hash"`
	RuntimeNodeID       string      `json:"runtime_node_id"`
	RuntimeAllocationID string      `json:"runtime_allocation_id"`
}

func (q *Queries) GetDeviceCredential(ctx context.Context, id pgtype.UUID) (GetDeviceCredentialRow, error) {
	row := q.db.QueryRow(ctx, getDeviceCredential, id)
	var i GetDeviceCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.RuntimeNodeID,
		&i.RuntimeAllocationID,
	)
	return i, err
}

const getSessionDevice = `-- name: GetSessionDevice :one
SELECT d.id, d.name, d.environment_id FROM session_devices b
JOIN sessions s ON s.id = b.session_id
JOIN devices d ON d.id = b.device_id AND d.tenant_id = s.tenant_id
WHERE s.tenant_id = $1 AND s.id = $2 AND d.revoked_at IS NULL
AND EXISTS (SELECT 1 FROM runtime_device_authority a WHERE a.id = d.id)
AND (d.environment_id IS NULL OR EXISTS (
    SELECT 1 FROM environments e WHERE e.id = d.environment_id AND e.session_id = s.id
))
`

type GetSessionDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetSessionDeviceRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) GetSessionDevice(ctx context.Context, arg GetSessionDeviceParams) (GetSessionDeviceRow, error) {
	row := q.db.QueryRow(ctx, getSessionDevice, arg.TenantID, arg.ID)
	var i GetSessionDeviceRow
	err := row.Scan(&i.ID, &i.Name, &i.EnvironmentID)
	return i, err
}

const getSessionExecutionBinding = `-- name: GetSessionExecutionBinding :one
SELECT d.id, d.name, b.native_session_id, d.environment_id,
    EXISTS (SELECT 1 FROM turns t WHERE t.session_id = s.id AND t.started_at IS NOT NULL) AS has_started_turn
FROM session_devices b
JOIN sessions s ON s.id = b.session_id
JOIN devices d ON d.id = b.device_id AND d.tenant_id = s.tenant_id
WHERE s.tenant_id = $1 AND s.id = $2 AND d.revoked_at IS NULL
AND EXISTS (SELECT 1 FROM runtime_device_authority a WHERE a.id = d.id)
AND (d.environment_id IS NULL OR EXISTS (
    SELECT 1 FROM environments e WHERE e.id = d.environment_id AND e.session_id = s.id
))
`

type GetSessionExecutionBindingParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetSessionExecutionBindingRow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	NativeSessionID string      `json:"native_session_id"`
	EnvironmentID   pgtype.UUID `json:"environment_id"`
	HasStartedTurn  bool        `json:"has_started_turn"`
}

func (q *Queries) GetSessionExecutionBinding(ctx context.Context, arg GetSessionExecutionBindingParams) (GetSessionExecutionBindingRow, error) {
	row := q.db.QueryRow(ctx, getSessionExecutionBinding, arg.TenantID, arg.ID)
	var i GetSessionExecutionBindingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NativeSessionID,
		&i.EnvironmentID,
		&i.HasStartedTurn,
	)
	return i, err
}

const rememberNativeSession = `-- name: RememberNativeSession :execrows
UPDATE session_devices SET native_session_id = $2 WHERE session_id = $1
`

type RememberNativeSessionParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	NativeSessionID string      `json:"native_session_id"`
}

func (q *Queries) RememberNativeSession(ctx context.Context, arg RememberNativeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rememberNativeSession, arg.SessionID, arg.NativeSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDevice = `-- name: RevokeDevice :execrows
UPDATE devices SET revoked_at = COALESCE(revoked_at, clock_timestamp()), archive_cancel_turn_id = NULL
WHERE tenant_id = $1 AND id = $2
`

type RevokeDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDevice, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDevice = `-- name: TouchDevice :execrows
UPDATE devices SET last_seen_at = clock_timestamp()
WHERE devices.id = $1 AND EXISTS (SELECT 1 FROM runtime_device_authority a WHERE a.id = devices.id)
`

func (q *Queries) TouchDevice(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
