// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAssignmentRelease = `-- name: AcknowledgeAssignmentRelease :execrows
UPDATE session_runtime_assignments SET applied_epoch = epoch
WHERE session_id = $1 AND assignment_id = $2 AND epoch = $3 AND desired_state = 'released'
`

type AcknowledgeAssignmentReleaseParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	AssignmentID pgtype.UUID `json:"assignment_id"`
	Epoch        int64       `json:"epoch"`
}

func (q *Queries) AcknowledgeAssignmentRelease(ctx context.Context, arg AcknowledgeAssignmentReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeAssignmentRelease, arg.SessionID, arg.AssignmentID, arg.Epoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindSessionDevice = `-- name: BindSessionDevice :one
INSERT INTO session_runtime_assignments (session_id, runtime_id)
SELECT s.id, d.id FROM sessions s CROSS JOIN devices d
WHERE s.tenant_id = $1 AND s.id = $2 AND d.id = $3 AND d.revoked_at IS NULL
AND (NOT EXISTS (SELECT 1 FROM environments e WHERE e.session_id = s.id) OR EXISTS (
    SELECT 1 FROM environments e JOIN sandbox_resources r ON r.environment_id = e.id
    WHERE e.session_id = s.id AND r.live
))
ON CONFLICT (session_id) DO UPDATE SET runtime_id = session_runtime_assignments.runtime_id
WHERE session_runtime_assignments.runtime_id = EXCLUDED.runtime_id AND session_runtime_assignments.desired_state = 'bound'
RETURNING runtime_id
`

type BindSessionDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	ID_2     pgtype.UUID `json:"id_2"`
}

// Binds the Session to an agent host. A Session with an Environment binds
// only while its Environment has a live Link resource, through which the
// agent host reaches the sandbox.
func (q *Queries) BindSessionDevice(ctx context.Context, arg BindSessionDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, bindSessionDevice, arg.TenantID, arg.ID, arg.ID_2)
	var runtime_id pgtype.UUID
	err := row.Scan(&runtime_id)
	return runtime_id, err
}

const getAgentHost = `-- name: GetAgentHost :one
SELECT id, name FROM devices
WHERE id = $1 AND revoked_at IS NULL
`

type GetAgentHostRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// A deployment agent host that may run Sessions.
func (q *Queries) GetAgentHost(ctx context.Context, id pgtype.UUID) (GetAgentHostRow, error) {
	row := q.db.QueryRow(ctx, getAgentHost, id)
	var i GetAgentHostRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDeviceCredential = `-- name: GetDeviceCredential :one
SELECT id, name, credential_hash FROM devices
WHERE id = $1 AND revoked_at IS NULL
`

type GetDeviceCredentialRow struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	CredentialHash string      `json:"credential_hash"`
}

func (q *Queries) GetDeviceCredential(ctx context.Context, id pgtype.UUID) (GetDeviceCredentialRow, error) {
	row := q.db.QueryRow(ctx, getDeviceCredential, id)
	var i GetDeviceCredentialRow
	err := row.Scan(&i.ID, &i.Name, &i.CredentialHash)
	return i, err
}

const getSessionDevice = `-- name: GetSessionDevice :one
SELECT d.id, d.name, e.id AS session_environment_id, b.assignment_id, b.epoch FROM session_runtime_assignments b
JOIN sessions s ON s.id = b.session_id
JOIN devices d ON d.id = b.runtime_id
LEFT JOIN environments e ON e.session_id = s.id
WHERE s.tenant_id = $1 AND s.id = $2 AND d.revoked_at IS NULL AND b.desired_state = 'bound'
`

type GetSessionDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetSessionDeviceRow struct {
	ID                   pgtype.UUID `json:"id"`
	Name                 string      `json:"name"`
	SessionEnvironmentID pgtype.UUID `json:"session_environment_id"`
	AssignmentID         pgtype.UUID `json:"assignment_id"`
	Epoch                int64       `json:"epoch"`
}

// The Session's bound agent host and Environment.
func (q *Queries) GetSessionDevice(ctx context.Context, arg GetSessionDeviceParams) (GetSessionDeviceRow, error) {
	row := q.db.QueryRow(ctx, getSessionDevice, arg.TenantID, arg.ID)
	var i GetSessionDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SessionEnvironmentID,
		&i.AssignmentID,
		&i.Epoch,
	)
	return i, err
}

const getSessionExecutionBinding = `-- name: GetSessionExecutionBinding :one
SELECT d.id, d.name, b.native_session_id, e.id AS session_environment_id, b.assignment_id, b.epoch,
    EXISTS (SELECT 1 FROM turns t WHERE t.session_id = s.id AND t.started_at IS NOT NULL) AS has_started_turn
FROM session_runtime_assignments b
JOIN sessions s ON s.id = b.session_id
JOIN devices d ON d.id = b.runtime_id
LEFT JOIN environments e ON e.session_id = s.id
WHERE s.tenant_id = $1 AND s.id = $2 AND d.revoked_at IS NULL AND b.desired_state = 'bound'
`

type GetSessionExecutionBindingParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetSessionExecutionBindingRow struct {
	ID                   pgtype.UUID `json:"id"`
	Name                 string      `json:"name"`
	NativeSessionID      string      `json:"native_session_id"`
	SessionEnvironmentID pgtype.UUID `json:"session_environment_id"`
	AssignmentID         pgtype.UUID `json:"assignment_id"`
	Epoch                int64       `json:"epoch"`
	HasStartedTurn       bool        `json:"has_started_turn"`
}

// The bound Runtime as GetSessionDevice reads it, with the native session.
func (q *Queries) GetSessionExecutionBinding(ctx context.Context, arg GetSessionExecutionBindingParams) (GetSessionExecutionBindingRow, error) {
	row := q.db.QueryRow(ctx, getSessionExecutionBinding, arg.TenantID, arg.ID)
	var i GetSessionExecutionBindingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NativeSessionID,
		&i.SessionEnvironmentID,
		&i.AssignmentID,
		&i.Epoch,
		&i.HasStartedTurn,
	)
	return i, err
}

const listPendingAssignmentReleases = `-- name: ListPendingAssignmentReleases :many
SELECT b.session_id, b.runtime_id, b.assignment_id, b.epoch, b.remove_home,
    r.tenant_id AS resource_tenant_id, r.environment_id AS resource_environment_id, r.kind AS resource_kind,
    r.id AS resource_id, r.generation AS resource_generation
FROM session_runtime_assignments b
LEFT JOIN environments e ON e.session_id = b.session_id
LEFT JOIN sandbox_resources r ON r.environment_id = e.id
WHERE b.desired_state = 'released' AND b.applied_epoch < b.epoch AND b.runtime_id = ANY($1::uuid[])
ORDER BY b.runtime_id, b.session_id
`

type ListPendingAssignmentReleasesRow struct {
	SessionID             pgtype.UUID `json:"session_id"`
	RuntimeID             pgtype.UUID `json:"runtime_id"`
	AssignmentID          pgtype.UUID `json:"assignment_id"`
	Epoch                 int64       `json:"epoch"`
	RemoveHome            bool        `json:"remove_home"`
	ResourceTenantID      pgtype.UUID `json:"resource_tenant_id"`
	ResourceEnvironmentID pgtype.UUID `json:"resource_environment_id"`
	ResourceKind          pgtype.Text `json:"resource_kind"`
	ResourceID            pgtype.UUID `json:"resource_id"`
	ResourceGeneration    pgtype.Int8 `json:"resource_generation"`
}

// Each release carries its Session's Link resource, live or not, which the
// release revokes before it is sent.
func (q *Queries) ListPendingAssignmentReleases(ctx context.Context, runtimeIds []pgtype.UUID) ([]ListPendingAssignmentReleasesRow, error) {
	rows, err := q.db.Query(ctx, listPendingAssignmentReleases, runtimeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingAssignmentReleasesRow{}
	for rows.Next() {
		var i ListPendingAssignmentReleasesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.RuntimeID,
			&i.AssignmentID,
			&i.Epoch,
			&i.RemoveHome,
			&i.ResourceTenantID,
			&i.ResourceEnvironmentID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourceGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAssignmentRuntime = `-- name: LockAssignmentRuntime :exec
SELECT 1 FROM session_runtime_assignments b JOIN devices d ON d.id = b.runtime_id
WHERE b.session_id = $1 FOR SHARE OF d
`

// Locks the agent host before a release reads its authority.
func (q *Queries) LockAssignmentRuntime(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockAssignmentRuntime, sessionID)
	return err
}

const releaseSessionAssignment = `-- name: ReleaseSessionAssignment :exec
UPDATE session_runtime_assignments b
SET desired_state = 'released', epoch = b.epoch + 1, remove_home = b.remove_home OR $1::boolean,
    applied_epoch = CASE WHEN EXISTS (SELECT 1 FROM devices d WHERE d.id = b.runtime_id AND d.revoked_at IS NULL) THEN b.applied_epoch ELSE b.epoch + 1 END
WHERE b.session_id = $2 AND (b.desired_state = 'bound' OR ($1::boolean AND NOT b.remove_home))
`

type ReleaseSessionAssignmentParams struct {
	RemoveHome bool        `json:"remove_home"`
	SessionID  pgtype.UUID `json:"session_id"`
}

// An identical release keeps its epoch; a release that adds home removal
// advances it. A release whose Runtime has no authority is settled, since no
// Runtime can act on it.
func (q *Queries) ReleaseSessionAssignment(ctx context.Context, arg ReleaseSessionAssignmentParams) error {
	_, err := q.db.Exec(ctx, releaseSessionAssignment, arg.RemoveHome, arg.SessionID)
	return err
}

const rememberNativeSession = `-- name: RememberNativeSession :execrows
UPDATE session_runtime_assignments SET native_session_id = $2 WHERE session_id = $1
`

type RememberNativeSessionParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	NativeSessionID string      `json:"native_session_id"`
}

func (q *Queries) RememberNativeSession(ctx context.Context, arg RememberNativeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rememberNativeSession, arg.SessionID, arg.NativeSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDevice = `-- name: TouchDevice :execrows
UPDATE devices SET last_seen_at = clock_timestamp()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchDevice(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
