// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_connections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceEnvironmentConnection = `-- name: AdvanceEnvironmentConnection :exec
UPDATE environment_connections SET revision = $2 WHERE environment_id = $1
`

type AdvanceEnvironmentConnectionParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Revision      int64       `json:"revision"`
}

func (q *Queries) AdvanceEnvironmentConnection(ctx context.Context, arg AdvanceEnvironmentConnectionParams) error {
	_, err := q.db.Exec(ctx, advanceEnvironmentConnection, arg.EnvironmentID, arg.Revision)
	return err
}

const deleteEnvironmentConnection = `-- name: DeleteEnvironmentConnection :exec
DELETE FROM environment_connections WHERE environment_id = $1
`

func (q *Queries) DeleteEnvironmentConnection(ctx context.Context, environmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentConnection, environmentID)
	return err
}

const expireSessionEnvironment = `-- name: ExpireSessionEnvironment :execrows
UPDATE environments e SET status = 'expired'
WHERE e.id = $1 AND e.session_id = $2
AND EXISTS (SELECT 1 FROM sessions s WHERE s.id = e.session_id AND s.tenant_id = $3)
`

type ExpireSessionEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ExpireSessionEnvironment(ctx context.Context, arg ExpireSessionEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireSessionEnvironment, arg.ID, arg.SessionID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironmentConnection = `-- name: GetEnvironmentConnection :one
SELECT environment_id, generation, revision FROM environment_connections WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentConnection(ctx context.Context, environmentID pgtype.UUID) (EnvironmentConnection, error) {
	row := q.db.QueryRow(ctx, getEnvironmentConnection, environmentID)
	var i EnvironmentConnection
	err := row.Scan(&i.EnvironmentID, &i.Generation, &i.Revision)
	return i, err
}

const listEnvironmentConnections = `-- name: ListEnvironmentConnections :many
SELECT e.id, e.session_id, s.tenant_id
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE e.id > $1 AND s.deleted_at IS NULL
  AND (e.status = 'connected' OR EXISTS (
      SELECT 1 FROM environment_connections c WHERE c.environment_id = e.id
  ))
ORDER BY e.id LIMIT 32
`

type ListEnvironmentConnectionsRow struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListEnvironmentConnections(ctx context.Context, id pgtype.UUID) ([]ListEnvironmentConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentConnections, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentConnectionsRow{}
	for rows.Next() {
		var i ListEnvironmentConnectionsRow
		if err := rows.Scan(&i.ID, &i.SessionID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEnvironmentFailure = `-- name: RecordEnvironmentFailure :one
UPDATE environments e SET status = 'failed', failure_reason = $1, failure_detail = $2, failed_at = clock_timestamp()
WHERE e.id = $3 AND e.session_id = $4 AND e.status NOT IN ('failed', 'expired')
AND EXISTS (SELECT 1 FROM sessions s WHERE s.id = e.session_id AND s.tenant_id = $5)
RETURNING e.failed_at
`

type RecordEnvironmentFailureParams struct {
	FailureReason pgtype.Text `json:"failure_reason"`
	FailureDetail []byte      `json:"failure_detail"`
	ID            pgtype.UUID `json:"id"`
	SessionID     pgtype.UUID `json:"session_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RecordEnvironmentFailure(ctx context.Context, arg RecordEnvironmentFailureParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, recordEnvironmentFailure,
		arg.FailureReason,
		arg.FailureDetail,
		arg.ID,
		arg.SessionID,
		arg.TenantID,
	)
	var failed_at pgtype.Timestamptz
	err := row.Scan(&failed_at)
	return failed_at, err
}

const replaceEnvironmentConnection = `-- name: ReplaceEnvironmentConnection :exec
INSERT INTO environment_connections (environment_id, generation, revision)
VALUES ($1, $2, 0)
ON CONFLICT (environment_id) DO UPDATE SET generation = EXCLUDED.generation, revision = 0
`

type ReplaceEnvironmentConnectionParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Generation    pgtype.UUID `json:"generation"`
}

func (q *Queries) ReplaceEnvironmentConnection(ctx context.Context, arg ReplaceEnvironmentConnectionParams) error {
	_, err := q.db.Exec(ctx, replaceEnvironmentConnection, arg.EnvironmentID, arg.Generation)
	return err
}

const setEnvironmentConnectionStatus = `-- name: SetEnvironmentConnectionStatus :exec
UPDATE environments SET status = $2 WHERE id = $1
`

type SetEnvironmentConnectionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetEnvironmentConnectionStatus(ctx context.Context, arg SetEnvironmentConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentConnectionStatus, arg.ID, arg.Status)
	return err
}
