// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_input_expiry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDueEnvironmentInputs = `-- name: ListDueEnvironmentInputs :many
SELECT r.id, r.session_id
FROM environment_input_reservations r
JOIN sessions s ON s.id = r.session_id
WHERE r.state = 'pending'
  AND r.deadline <= statement_timestamp()
  AND s.deleted_at IS NULL
ORDER BY r.deadline, r.id
LIMIT 32
FOR UPDATE OF s SKIP LOCKED
`

type ListDueEnvironmentInputsRow struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListDueEnvironmentInputs(ctx context.Context) ([]ListDueEnvironmentInputsRow, error) {
	rows, err := q.db.Query(ctx, listDueEnvironmentInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueEnvironmentInputsRow{}
	for rows.Next() {
		var i ListDueEnvironmentInputsRow
		if err := rows.Scan(&i.ID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
