// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_input_activity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnvironmentInputActivity = `-- name: GetEnvironmentInputActivity :one
SELECT r.state, r.is_initial, r.created_at, r.settled_at, r.failure_code, e.id AS environment_id, e.status AS connection_status,
       COALESCE(s.configuration->'environment'->>'type', '')::text AS environment_type
FROM environments e
JOIN sessions s ON s.id = e.session_id
JOIN LATERAL (
    SELECT id, session_id, idempotency_key, batch, state, created_at, deadline, settled_at, is_initial, failure_code FROM environment_input_reservations
    WHERE session_id = e.session_id
    ORDER BY created_at DESC, id DESC LIMIT 1
) r ON true
WHERE e.session_id = $1 AND r.state <> 'admitted'
  AND NOT EXISTS (
      SELECT 1 FROM turns t WHERE t.session_id = e.session_id
        AND (t.created_at >= r.created_at OR t.status IN ('queued', 'in_progress', 'waiting'))
  )
`

type GetEnvironmentInputActivityRow struct {
	State            string             `json:"state"`
	IsInitial        bool               `json:"is_initial"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SettledAt        pgtype.Timestamptz `json:"settled_at"`
	FailureCode      pgtype.Text        `json:"failure_code"`
	EnvironmentID    pgtype.UUID        `json:"environment_id"`
	ConnectionStatus string             `json:"connection_status"`
	EnvironmentType  string             `json:"environment_type"`
}

func (q *Queries) GetEnvironmentInputActivity(ctx context.Context, sessionID pgtype.UUID) (GetEnvironmentInputActivityRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentInputActivity, sessionID)
	var i GetEnvironmentInputActivityRow
	err := row.Scan(
		&i.State,
		&i.IsInitial,
		&i.CreatedAt,
		&i.SettledAt,
		&i.FailureCode,
		&i.EnvironmentID,
		&i.ConnectionStatus,
		&i.EnvironmentType,
	)
	return i, err
}
