// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: functions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyFunctionResult = `-- name: ApplyFunctionResult :exec
UPDATE function_calls SET applied = true WHERE session_id = $1 AND turn_id = $2 AND call_id = $3
`

type ApplyFunctionResultParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	CallID    string      `json:"call_id"`
}

func (q *Queries) ApplyFunctionResult(ctx context.Context, arg ApplyFunctionResultParams) error {
	_, err := q.db.Exec(ctx, applyFunctionResult, arg.SessionID, arg.TurnID, arg.CallID)
	return err
}

const createFunctionCall = `-- name: CreateFunctionCall :execrows
INSERT INTO function_calls(session_id, turn_id, call_id, executor_call_id, name, arguments)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING
`

type CreateFunctionCallParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	TurnID         pgtype.UUID `json:"turn_id"`
	CallID         string      `json:"call_id"`
	ExecutorCallID string      `json:"executor_call_id"`
	Name           string      `json:"name"`
	Arguments      []byte      `json:"arguments"`
}

func (q *Queries) CreateFunctionCall(ctx context.Context, arg CreateFunctionCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFunctionCall,
		arg.SessionID,
		arg.TurnID,
		arg.CallID,
		arg.ExecutorCallID,
		arg.Name,
		arg.Arguments,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const functionItemResult = `-- name: FunctionItemResult :one
SELECT result FROM function_calls
WHERE session_id = $1 AND turn_id = $2 AND call_id = $3
`

type FunctionItemResultParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	CallID    string      `json:"call_id"`
}

func (q *Queries) FunctionItemResult(ctx context.Context, arg FunctionItemResultParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, functionItemResult, arg.SessionID, arg.TurnID, arg.CallID)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const getFunctionCall = `-- name: GetFunctionCall :one
SELECT f.session_id, f.turn_id, f.call_id, f.executor_call_id, f.name, f.arguments, f.result, f.applied, f.created_at FROM function_calls f JOIN sessions s ON s.id = f.session_id
WHERE s.tenant_id = $1 AND f.session_id = $2 AND f.turn_id = $3 AND f.call_id = $4
`

type GetFunctionCallParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	CallID    string      `json:"call_id"`
}

func (q *Queries) GetFunctionCall(ctx context.Context, arg GetFunctionCallParams) (FunctionCall, error) {
	row := q.db.QueryRow(ctx, getFunctionCall,
		arg.TenantID,
		arg.SessionID,
		arg.TurnID,
		arg.CallID,
	)
	var i FunctionCall
	err := row.Scan(
		&i.SessionID,
		&i.TurnID,
		&i.CallID,
		&i.ExecutorCallID,
		&i.Name,
		&i.Arguments,
		&i.Result,
		&i.Applied,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingFunctionCalls = `-- name: ListPendingFunctionCalls :many
SELECT f.session_id, f.turn_id, f.call_id, f.executor_call_id, f.name, f.arguments, f.result, f.applied, f.created_at FROM function_calls f JOIN turns t ON t.session_id = f.session_id AND t.id = f.turn_id
WHERE f.session_id = $1 AND f.turn_id = $2 AND NOT f.applied
    AND t.status IN ('in_progress', 'waiting') AND t.cancel_requested_at IS NULL
ORDER BY f.created_at, f.call_id
`

type ListPendingFunctionCallsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

func (q *Queries) ListPendingFunctionCalls(ctx context.Context, arg ListPendingFunctionCallsParams) ([]FunctionCall, error) {
	rows, err := q.db.Query(ctx, listPendingFunctionCalls, arg.SessionID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FunctionCall{}
	for rows.Next() {
		var i FunctionCall
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnID,
			&i.CallID,
			&i.ExecutorCallID,
			&i.Name,
			&i.Arguments,
			&i.Result,
			&i.Applied,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchFunctionCall = `-- name: MatchFunctionCall :one
SELECT COALESCE(executor_call_id = $1 AND name = $2
    AND arguments = $3::jsonb, false)::boolean AS matches
FROM function_calls
WHERE session_id = $4 AND turn_id = $5 AND call_id = $6
`

type MatchFunctionCallParams struct {
	ExecutorCallID string      `json:"executor_call_id"`
	Name           string      `json:"name"`
	Arguments      []byte      `json:"arguments"`
	SessionID      pgtype.UUID `json:"session_id"`
	TurnID         pgtype.UUID `json:"turn_id"`
	CallID         string      `json:"call_id"`
}

func (q *Queries) MatchFunctionCall(ctx context.Context, arg MatchFunctionCallParams) (bool, error) {
	row := q.db.QueryRow(ctx, matchFunctionCall,
		arg.ExecutorCallID,
		arg.Name,
		arg.Arguments,
		arg.SessionID,
		arg.TurnID,
		arg.CallID,
	)
	var matches bool
	err := row.Scan(&matches)
	return matches, err
}

const matchFunctionResult = `-- name: MatchFunctionResult :one
SELECT (result IS NOT NULL)::boolean AS submitted, COALESCE(result = $1::jsonb, false)::boolean AS matches
FROM function_calls
WHERE session_id = $2 AND turn_id = $3 AND call_id = $4
`

type MatchFunctionResultParams struct {
	Result    []byte      `json:"result"`
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	CallID    string      `json:"call_id"`
}

type MatchFunctionResultRow struct {
	Submitted bool `json:"submitted"`
	Matches   bool `json:"matches"`
}

func (q *Queries) MatchFunctionResult(ctx context.Context, arg MatchFunctionResultParams) (MatchFunctionResultRow, error) {
	row := q.db.QueryRow(ctx, matchFunctionResult,
		arg.Result,
		arg.SessionID,
		arg.TurnID,
		arg.CallID,
	)
	var i MatchFunctionResultRow
	err := row.Scan(&i.Submitted, &i.Matches)
	return i, err
}

const sessionHasFunctionCall = `-- name: SessionHasFunctionCall :one
SELECT EXISTS (
    SELECT 1 FROM function_calls WHERE session_id = $1 AND call_id = $2
)::boolean AS found
`

type SessionHasFunctionCallParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	CallID    string      `json:"call_id"`
}

func (q *Queries) SessionHasFunctionCall(ctx context.Context, arg SessionHasFunctionCallParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionHasFunctionCall, arg.SessionID, arg.CallID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const submitFunctionResult = `-- name: SubmitFunctionResult :exec
UPDATE function_calls SET result = $4 WHERE session_id = $1 AND turn_id = $2 AND call_id = $3
`

type SubmitFunctionResultParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	CallID    string      `json:"call_id"`
	Result    []byte      `json:"result"`
}

func (q *Queries) SubmitFunctionResult(ctx context.Context, arg SubmitFunctionResultParams) error {
	_, err := q.db.Exec(ctx, submitFunctionResult,
		arg.SessionID,
		arg.TurnID,
		arg.CallID,
		arg.Result,
	)
	return err
}
