// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: local_environment_devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindHostedSessionDevice = `-- name: BindHostedSessionDevice :one
INSERT INTO session_devices(session_id, device_id)
SELECT s.id, d.id FROM sessions s JOIN devices d ON d.tenant_id = s.tenant_id
JOIN environments e ON e.id = d.environment_id AND e.session_id = s.id
WHERE s.tenant_id = $1 AND s.id = $2 AND d.id = $3 AND d.revoked_at IS NULL
  AND d.executor_key_id IS NULL AND s.deleted_at IS NULL
  AND s.configuration->'environment'->>'type' = 'openai_hosted'
ON CONFLICT (session_id) DO UPDATE SET device_id = EXCLUDED.device_id
WHERE session_devices.device_id = EXCLUDED.device_id OR (
  EXISTS (SELECT 1 FROM devices previous
    JOIN runtime_allocations a ON a.device_id = previous.id
    WHERE previous.id = session_devices.device_id AND previous.revoked_at IS NOT NULL
      AND previous.executor_key_id IS NULL AND a.state = 'released'
      AND previous.environment_id = (SELECT environment_id FROM devices WHERE id = EXCLUDED.device_id))
  AND NOT EXISTS (SELECT 1 FROM runtime_allocations a
    WHERE a.environment_id = (SELECT environment_id FROM devices WHERE id = EXCLUDED.device_id)
      AND a.state <> 'released')
)
RETURNING device_id
`

type BindHostedSessionDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	ID_2     pgtype.UUID `json:"id_2"`
}

func (q *Queries) BindHostedSessionDevice(ctx context.Context, arg BindHostedSessionDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, bindHostedSessionDevice, arg.TenantID, arg.ID, arg.ID_2)
	var device_id pgtype.UUID
	err := row.Scan(&device_id)
	return device_id, err
}

const createEnvironmentDevice = `-- name: CreateEnvironmentDevice :one
INSERT INTO devices (id, tenant_id, name, credential_hash, environment_id)
SELECT $1, s.tenant_id, $2, $3, e.id
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $4 AND s.id = $5 AND e.id = $6
AND s.deleted_at IS NULL AND s.configuration->'environment'->>'type' = 'openai_hosted'
AND NOT EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id AND a.state <> 'released')
AND NOT EXISTS (SELECT 1 FROM devices previous WHERE previous.environment_id = e.id AND (previous.revoked_at IS NULL OR previous.executor_key_id IS NOT NULL))
ON CONFLICT (environment_id) WHERE revoked_at IS NULL OR executor_key_id IS NOT NULL DO NOTHING
RETURNING id
`

type CreateEnvironmentDeviceParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	CredentialHash pgtype.Text `json:"credential_hash"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	SessionID      pgtype.UUID `json:"session_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
}

func (q *Queries) CreateEnvironmentDevice(ctx context.Context, arg CreateEnvironmentDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEnvironmentDevice,
		arg.ID,
		arg.Name,
		arg.CredentialHash,
		arg.TenantID,
		arg.SessionID,
		arg.EnvironmentID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
