// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: node_generations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNodeGenerationStatus = `-- name: DeleteNodeGenerationStatus :exec
DELETE FROM runtime_node_generation_status WHERE node_id=$1 AND generation=$2
`

type DeleteNodeGenerationStatusParams struct {
	NodeID     pgtype.UUID `json:"node_id"`
	Generation int64       `json:"generation"`
}

func (q *Queries) DeleteNodeGenerationStatus(ctx context.Context, arg DeleteNodeGenerationStatusParams) error {
	_, err := q.db.Exec(ctx, deleteNodeGenerationStatus, arg.NodeID, arg.Generation)
	return err
}

const getNodeGenerationSpecification = `-- name: GetNodeGenerationSpecification :one
SELECT d.provider_kind,d.specification FROM runtime_deployment d WHERE d.generation=$1
UNION ALL SELECT g.provider_kind,g.specification FROM runtime_deployment_generations g WHERE g.generation=$1 AND g.generation<>(SELECT d.generation FROM runtime_deployment d)
LIMIT 1
`

type GetNodeGenerationSpecificationRow struct {
	ProviderKind  string `json:"provider_kind"`
	Specification []byte `json:"specification"`
}

func (q *Queries) GetNodeGenerationSpecification(ctx context.Context, generation int64) (GetNodeGenerationSpecificationRow, error) {
	row := q.db.QueryRow(ctx, getNodeGenerationSpecification, generation)
	var i GetNodeGenerationSpecificationRow
	err := row.Scan(&i.ProviderKind, &i.Specification)
	return i, err
}

const nodeGenerationKept = `-- name: NodeGenerationKept :one
SELECT (EXISTS(SELECT 1 FROM runtime_deployment d WHERE d.generation=$1)
 OR EXISTS(SELECT 1 FROM runtime_nodes n WHERE n.id=$2 AND n.removed_at IS NULL AND n.ready_generation=$1)
 OR EXISTS(SELECT 1 FROM runtime_placements p WHERE p.node_id=$2 AND p.released_at IS NULL AND p.deployment_generation=$1)
 OR EXISTS(SELECT 1 FROM runtime_allocations a WHERE a.node_id=$2 AND a.state<>'released' AND a.deployment_generation=$1))::boolean AS kept
`

type NodeGenerationKeptParams struct {
	Generation int64       `json:"generation"`
	NodeID     pgtype.UUID `json:"node_id"`
}

func (q *Queries) NodeGenerationKept(ctx context.Context, arg NodeGenerationKeptParams) (bool, error) {
	row := q.db.QueryRow(ctx, nodeGenerationKept, arg.Generation, arg.NodeID)
	var kept bool
	err := row.Scan(&kept)
	return kept, err
}

const nodeGenerationReady = `-- name: NodeGenerationReady :one
SELECT EXISTS(SELECT 1 FROM runtime_node_generation_status g JOIN runtime_nodes n ON n.id=g.node_id CROSS JOIN runtime_deployment d
 WHERE n.id=$1 AND g.generation=$2 AND n.removed_at IS NULL
 AND n.connection_id=g.connection_id AND n.connected_epoch=g.owner_epoch AND g.owner_epoch=d.owner_epoch
 AND n.last_seen_at>clock_timestamp()-interval '45 seconds' AND g.state='ready')::boolean AS ready
`

type NodeGenerationReadyParams struct {
	NodeID     pgtype.UUID `json:"node_id"`
	Generation int64       `json:"generation"`
}

func (q *Queries) NodeGenerationReady(ctx context.Context, arg NodeGenerationReadyParams) (bool, error) {
	row := q.db.QueryRow(ctx, nodeGenerationReady, arg.NodeID, arg.Generation)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const promoteNodeServingGeneration = `-- name: PromoteNodeServingGeneration :exec
UPDATE runtime_nodes SET ready_generation=$2 WHERE id=$1 AND removed_at IS NULL
AND $2=(SELECT generation FROM runtime_deployment) AND (ready_generation IS NULL OR ready_generation<$2)
`

type PromoteNodeServingGenerationParams struct {
	ID              pgtype.UUID `json:"id"`
	ReadyGeneration pgtype.Int8 `json:"ready_generation"`
}

func (q *Queries) PromoteNodeServingGeneration(ctx context.Context, arg PromoteNodeServingGenerationParams) error {
	_, err := q.db.Exec(ctx, promoteNodeServingGeneration, arg.ID, arg.ReadyGeneration)
	return err
}

const refreshNodeServingReadiness = `-- name: RefreshNodeServingReadiness :exec
UPDATE runtime_nodes n SET protocol_version=$2, provider_ready=EXISTS(
 SELECT 1 FROM runtime_node_generation_status g WHERE g.node_id=n.id AND g.generation=n.ready_generation
 AND g.connection_id=n.connection_id AND g.owner_epoch=n.connected_epoch AND g.state='ready')
WHERE n.id=$1 AND n.removed_at IS NULL
`

type RefreshNodeServingReadinessParams struct {
	ID              pgtype.UUID `json:"id"`
	ProtocolVersion int32       `json:"protocol_version"`
}

func (q *Queries) RefreshNodeServingReadiness(ctx context.Context, arg RefreshNodeServingReadinessParams) error {
	_, err := q.db.Exec(ctx, refreshNodeServingReadiness, arg.ID, arg.ProtocolVersion)
	return err
}

const upsertNodeGenerationStatus = `-- name: UpsertNodeGenerationStatus :exec
INSERT INTO runtime_node_generation_status(node_id,generation,specification_digest,connection_id,owner_epoch,state,diagnostic)
VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(node_id,generation) DO UPDATE SET specification_digest=EXCLUDED.specification_digest,connection_id=EXCLUDED.connection_id,
 owner_epoch=EXCLUDED.owner_epoch,state=EXCLUDED.state,diagnostic=EXCLUDED.diagnostic,observed_at=clock_timestamp()
`

type UpsertNodeGenerationStatusParams struct {
	NodeID              pgtype.UUID `json:"node_id"`
	Generation          int64       `json:"generation"`
	SpecificationDigest string      `json:"specification_digest"`
	ConnectionID        pgtype.UUID `json:"connection_id"`
	OwnerEpoch          int64       `json:"owner_epoch"`
	State               string      `json:"state"`
	Diagnostic          string      `json:"diagnostic"`
}

func (q *Queries) UpsertNodeGenerationStatus(ctx context.Context, arg UpsertNodeGenerationStatusParams) error {
	_, err := q.db.Exec(ctx, upsertNodeGenerationStatus,
		arg.NodeID,
		arg.Generation,
		arg.SpecificationDigest,
		arg.ConnectionID,
		arg.OwnerEpoch,
		arg.State,
		arg.Diagnostic,
	)
	return err
}
