// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET archived_at=COALESCE(archived_at,now()) WHERE id=$1
`

func (q *Queries) ArchiveProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects(id,name,tenant_id,subject_kind,subject_id)
VALUES ($1,$2,$3,'service_account',$4) RETURNING id, name, tenant_id, subject_kind, subject_id, created_at, archived_at
`

type CreateProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	SubjectID string      `json:"subject_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.TenantID,
		arg.SubjectID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TenantID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT p.id, p.name, p.tenant_id, p.subject_kind, p.subject_id, p.created_at, p.archived_at, s.organization_id, s.project_id AS external_project_id,
    (SELECT count(*) FROM project_api_keys k WHERE k.project_id=p.id AND k.revoked_at IS NULL) AS active_key_count
FROM projects p JOIN execution_project_scopes s ON s.tenant_id=p.tenant_id WHERE p.id=$1
`

type GetProjectRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	SubjectKind       string             `json:"subject_kind"`
	SubjectID         string             `json:"subject_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	OrganizationID    string             `json:"organization_id"`
	ExternalProjectID string             `json:"external_project_id"`
	ActiveKeyCount    int64              `json:"active_key_count"`
}

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TenantID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.ExternalProjectID,
		&i.ActiveKeyCount,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.name, p.tenant_id, p.subject_kind, p.subject_id, p.created_at, p.archived_at, s.organization_id, s.project_id AS external_project_id,
    (SELECT count(*) FROM project_api_keys k WHERE k.project_id=p.id AND k.revoked_at IS NULL) AS active_key_count
FROM projects p JOIN execution_project_scopes s ON s.tenant_id=p.tenant_id
WHERE ($1::text='' OR
    ($2::bool AND p.id::text>$1::text) OR
    (NOT $2::bool AND p.id::text<$1::text))
ORDER BY CASE WHEN $2::bool THEN p.id END ASC,
    CASE WHEN NOT $2::bool THEN p.id END DESC
LIMIT $3::int
`

type ListProjectsParams struct {
	AfterID   string `json:"after_id"`
	Ascending bool   `json:"ascending"`
	PageLimit int32  `json:"page_limit"`
}

type ListProjectsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	SubjectKind       string             `json:"subject_kind"`
	SubjectID         string             `json:"subject_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	OrganizationID    string             `json:"organization_id"`
	ExternalProjectID string             `json:"external_project_id"`
	ActiveKeyCount    int64              `json:"active_key_count"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.AfterID, arg.Ascending, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TenantID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.OrganizationID,
			&i.ExternalProjectID,
			&i.ActiveKeyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProject = `-- name: LockProject :one
SELECT id, name, tenant_id, subject_kind, subject_id, created_at, archived_at FROM projects WHERE id=$1 FOR SHARE
`

func (q *Queries) LockProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, lockProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TenantID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const lockProjectByTenant = `-- name: LockProjectByTenant :one
SELECT id, name, tenant_id, subject_kind, subject_id, created_at, archived_at FROM projects WHERE tenant_id=$1 FOR SHARE
`

func (q *Queries) LockProjectByTenant(ctx context.Context, tenantID pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, lockProjectByTenant, tenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TenantID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const lockProjectForUpdate = `-- name: LockProjectForUpdate :one
SELECT id, name, tenant_id, subject_kind, subject_id, created_at, archived_at FROM projects WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockProjectForUpdate(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, lockProjectForUpdate, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TenantID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const renameProject = `-- name: RenameProject :exec
UPDATE projects SET name=$2 WHERE id=$1
`

type RenameProjectParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) error {
	_, err := q.db.Exec(ctx, renameProject, arg.ID, arg.Name)
	return err
}

const revokeProjectKeys = `-- name: RevokeProjectKeys :exec
UPDATE project_api_keys SET revoked_at=COALESCE(revoked_at,now()) WHERE project_id=$1
`

func (q *Queries) RevokeProjectKeys(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeProjectKeys, projectID)
	return err
}
