// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_scopes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureProjectScope = `-- name: EnsureProjectScope :one
INSERT INTO execution_project_scopes (tenant_id, organization_id, project_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id) DO UPDATE SET tenant_id = EXCLUDED.tenant_id
WHERE execution_project_scopes.organization_id = EXCLUDED.organization_id
  AND execution_project_scopes.project_id = EXCLUDED.project_id
RETURNING tenant_id
`

type EnsureProjectScopeParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
}

func (q *Queries) EnsureProjectScope(ctx context.Context, arg EnsureProjectScopeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ensureProjectScope, arg.TenantID, arg.OrganizationID, arg.ProjectID)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
