// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_suspension_pressure.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRuntimeSuspensionInFlightNodes = `-- name: ListRuntimeSuspensionInFlightNodes :many
SELECT DISTINCT a.node_id
FROM runtime_allocations a
WHERE a.node_id IS NOT NULL AND a.state <> 'released'
  AND (a.compute_phase IN ('quiescing', 'suspending')
       OR (a.compute_retained_until <= clock_timestamp() AND a.compute_phase <> 'disabled'))
`

func (q *Queries) ListRuntimeSuspensionInFlightNodes(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRuntimeSuspensionInFlightNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var node_id pgtype.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingRuntimeRestoreGenerations = `-- name: ListWaitingRuntimeRestoreGenerations :many
SELECT DISTINCT a.deployment_generation
FROM runtime_allocations a
JOIN environments e ON e.id = a.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE a.node_id = $1 AND a.state = 'running' AND a.compute_phase = 'suspended'
  AND a.compute_retained_until > clock_timestamp()
  AND s.deleted_at IS NULL AND e.status NOT IN ('failed', 'expired')
  AND (a.compute_wake_requested OR EXISTS (
      SELECT 1 FROM environment_input_reservations r
      WHERE r.session_id = s.id AND r.state = 'pending' AND r.deadline > clock_timestamp()
  ))
`

func (q *Queries) ListWaitingRuntimeRestoreGenerations(ctx context.Context, nodeID pgtype.UUID) ([]pgtype.Int8, error) {
	rows, err := q.db.Query(ctx, listWaitingRuntimeRestoreGenerations, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Int8{}
	for rows.Next() {
		var deployment_generation pgtype.Int8
		if err := rows.Scan(&deployment_generation); err != nil {
			return nil, err
		}
		items = append(items, deployment_generation)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
