// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_cancellation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArchivedCancellationReceipt = `-- name: GetArchivedCancellationReceipt :one
SELECT t.id, t.cancel_requested_at
FROM devices d
JOIN runtime_allocations a ON a.device_id = d.id
JOIN environments e ON e.id = a.environment_id AND e.id = d.environment_id
JOIN sessions s ON s.id = e.session_id AND s.tenant_id = d.tenant_id
JOIN turns t ON t.session_id = s.id AND t.id = d.archive_cancel_turn_id
WHERE d.id = $1
  AND d.credential_hash = $2
  AND d.executor_key_id IS NULL AND d.revoked_at IS NOT NULL
  AND a.state = 'cleanup_pending' AND a.released_at IS NULL
  AND e.status = 'expired' AND s.deleted_at IS NULL
  AND s.configuration->'environment'->>'type' = 'openai_hosted'
  AND t.status IN ('in_progress', 'waiting')
  AND t.id::text = ANY($3::text[])
  AND t.cancel_requested_at IS NOT NULL
  AND d.revoked_at >= t.cancel_requested_at
  AND t.cancel_requested_at > clock_timestamp() - $4::int * interval '1 second'
`

type GetArchivedCancellationReceiptParams struct {
	DeviceID       pgtype.UUID `json:"device_id"`
	CredentialHash pgtype.Text `json:"credential_hash"`
	RunIds         []string    `json:"run_ids"`
	LimitSeconds   int32       `json:"limit_seconds"`
}

type GetArchivedCancellationReceiptRow struct {
	ID                pgtype.UUID        `json:"id"`
	CancelRequestedAt pgtype.Timestamptz `json:"cancel_requested_at"`
}

func (q *Queries) GetArchivedCancellationReceipt(ctx context.Context, arg GetArchivedCancellationReceiptParams) (GetArchivedCancellationReceiptRow, error) {
	row := q.db.QueryRow(ctx, getArchivedCancellationReceipt,
		arg.DeviceID,
		arg.CredentialHash,
		arg.RunIds,
		arg.LimitSeconds,
	)
	var i GetArchivedCancellationReceiptRow
	err := row.Scan(&i.ID, &i.CancelRequestedAt)
	return i, err
}

const revokeArchivedRuntimeDevice = `-- name: RevokeArchivedRuntimeDevice :execrows
UPDATE devices d
SET archive_cancel_turn_id = CASE WHEN d.revoked_at IS NULL THEN (
    SELECT t.id FROM turns t
    WHERE t.session_id = $1
      AND t.status IN ('in_progress', 'waiting') AND t.cancel_requested_at IS NOT NULL
) ELSE d.archive_cancel_turn_id END,
    revoked_at = COALESCE(d.revoked_at, clock_timestamp())
WHERE d.tenant_id = $2 AND d.id = $3
`

type RevokeArchivedRuntimeDeviceParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	DeviceID  pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeArchivedRuntimeDevice(ctx context.Context, arg RevokeArchivedRuntimeDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeArchivedRuntimeDevice, arg.SessionID, arg.TenantID, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRuntimeCleanupDevice = `-- name: RevokeRuntimeCleanupDevice :execrows
UPDATE devices SET revoked_at = COALESCE(revoked_at, clock_timestamp())
WHERE tenant_id = $1 AND id = $2
`

type RevokeRuntimeCleanupDeviceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeRuntimeCleanupDevice(ctx context.Context, arg RevokeRuntimeCleanupDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRuntimeCleanupDevice, arg.TenantID, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
