// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_enrollment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeRuntimeEnrollment = `-- name: AuthorizeRuntimeEnrollment :one
SELECT c.key_id, e.session_id, COALESCE(s.configuration->'environment'->>'workspace_directory', '')::text AS workspace_directory
FROM environment_executor_credentials c
JOIN environments e ON e.id = $1
JOIN sessions s ON s.id = e.session_id
JOIN execution_project_scopes p ON p.tenant_id = c.tenant_id
WHERE c.token_sha256 = $2 AND c.revoked_at IS NULL
    AND c.tenant_id = s.tenant_id AND s.tenant_id = $3
    AND c.subject_kind = s.creator_kind AND c.subject_id = s.creator_id
    AND (c.environment_id IS NULL OR c.environment_id = e.id)
    AND s.deleted_at IS NULL AND e.status NOT IN ('failed', 'expired')
    AND s.configuration->'environment'->>'type' = 'self_hosted'
FOR SHARE OF c
`

type AuthorizeRuntimeEnrollmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TokenSha256   string      `json:"token_sha256"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

type AuthorizeRuntimeEnrollmentRow struct {
	KeyID              pgtype.UUID `json:"key_id"`
	SessionID          pgtype.UUID `json:"session_id"`
	WorkspaceDirectory string      `json:"workspace_directory"`
}

func (q *Queries) AuthorizeRuntimeEnrollment(ctx context.Context, arg AuthorizeRuntimeEnrollmentParams) (AuthorizeRuntimeEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, authorizeRuntimeEnrollment, arg.EnvironmentID, arg.TokenSha256, arg.TenantID)
	var i AuthorizeRuntimeEnrollmentRow
	err := row.Scan(&i.KeyID, &i.SessionID, &i.WorkspaceDirectory)
	return i, err
}

const enrollRuntimeDevice = `-- name: EnrollRuntimeDevice :one
INSERT INTO devices (id, tenant_id, name, environment_id, executor_key_id)
VALUES ($1, $2, 'User-managed Runtime', $3, $4)
ON CONFLICT (environment_id) DO UPDATE SET name = devices.name
WHERE devices.executor_key_id = EXCLUDED.executor_key_id AND devices.revoked_at IS NULL
RETURNING id, name, environment_id
`

type EnrollRuntimeDeviceParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ExecutorKeyID pgtype.UUID `json:"executor_key_id"`
}

type EnrollRuntimeDeviceRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) EnrollRuntimeDevice(ctx context.Context, arg EnrollRuntimeDeviceParams) (EnrollRuntimeDeviceRow, error) {
	row := q.db.QueryRow(ctx, enrollRuntimeDevice,
		arg.ID,
		arg.TenantID,
		arg.EnvironmentID,
		arg.ExecutorKeyID,
	)
	var i EnrollRuntimeDeviceRow
	err := row.Scan(&i.ID, &i.Name, &i.EnvironmentID)
	return i, err
}

const listEnrolledRuntimeBindings = `-- name: ListEnrolledRuntimeBindings :many
SELECT d.id AS device_id, d.tenant_id, e.id AS environment_id, e.session_id
FROM devices d
JOIN environments e ON e.id = d.environment_id
JOIN sessions s ON s.id = e.session_id AND s.tenant_id = d.tenant_id
WHERE d.executor_key_id IS NOT NULL AND s.deleted_at IS NULL
    AND e.status NOT IN ('failed', 'expired')
ORDER BY d.id
`

type ListEnrolledRuntimeBindingsRow struct {
	DeviceID      pgtype.UUID `json:"device_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	SessionID     pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListEnrolledRuntimeBindings(ctx context.Context) ([]ListEnrolledRuntimeBindingsRow, error) {
	rows, err := q.db.Query(ctx, listEnrolledRuntimeBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrolledRuntimeBindingsRow{}
	for rows.Next() {
		var i ListEnrolledRuntimeBindingsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.TenantID,
			&i.EnvironmentID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAuthenticatedDevice = `-- name: TouchAuthenticatedDevice :execrows
UPDATE devices SET last_seen_at = clock_timestamp()
WHERE devices.id = $1 AND EXISTS (
    SELECT 1 FROM runtime_device_authority a
    WHERE a.id = devices.id AND a.credential_hash = $2
)
`

type TouchAuthenticatedDeviceParams struct {
	ID             pgtype.UUID `json:"id"`
	CredentialHash string      `json:"credential_hash"`
}

func (q *Queries) TouchAuthenticatedDevice(ctx context.Context, arg TouchAuthenticatedDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAuthenticatedDevice, arg.ID, arg.CredentialHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
