// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_enrollment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeRuntimeEnrollment = `-- name: AuthorizeRuntimeEnrollment :one
SELECT c.key_id
FROM environment_executor_credentials c
JOIN environments e ON e.id = $1
JOIN sessions s ON s.id = e.session_id
JOIN execution_project_scopes p ON p.tenant_id = c.tenant_id
WHERE c.token_sha256 = $2 AND c.revoked_at IS NULL
    AND c.tenant_id = s.tenant_id AND s.tenant_id = $3
    AND c.subject_kind = s.creator_kind AND c.subject_id = s.creator_id
    AND (c.environment_id IS NULL OR c.environment_id = e.id)
    AND s.deleted_at IS NULL AND e.status NOT IN ('failed', 'expired')
    AND s.configuration->'environment'->>'type' = 'self_hosted'
FOR SHARE OF c
`

type AuthorizeRuntimeEnrollmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TokenSha256   string      `json:"token_sha256"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) AuthorizeRuntimeEnrollment(ctx context.Context, arg AuthorizeRuntimeEnrollmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, authorizeRuntimeEnrollment, arg.EnvironmentID, arg.TokenSha256, arg.TenantID)
	var key_id pgtype.UUID
	err := row.Scan(&key_id)
	return key_id, err
}

const enrollSandbox = `-- name: EnrollSandbox :one
INSERT INTO sandbox_enrollments (id, environment_id, executor_key_id)
VALUES ($1, $2, $3)
ON CONFLICT (environment_id) DO UPDATE SET executor_key_id = EXCLUDED.executor_key_id
WHERE sandbox_enrollments.executor_key_id = EXCLUDED.executor_key_id
RETURNING id, generation
`

type EnrollSandboxParams struct {
	ID            pgtype.UUID `json:"id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ExecutorKeyID pgtype.UUID `json:"executor_key_id"`
}

type EnrollSandboxRow struct {
	ID         pgtype.UUID `json:"id"`
	Generation int64       `json:"generation"`
}

// The first key to enroll the Environment keeps its enrollment; the same key
// enrolling again returns it, and another key conflicts.
func (q *Queries) EnrollSandbox(ctx context.Context, arg EnrollSandboxParams) (EnrollSandboxRow, error) {
	row := q.db.QueryRow(ctx, enrollSandbox, arg.ID, arg.EnvironmentID, arg.ExecutorKeyID)
	var i EnrollSandboxRow
	err := row.Scan(&i.ID, &i.Generation)
	return i, err
}

const touchAuthenticatedDevice = `-- name: TouchAuthenticatedDevice :execrows
UPDATE devices SET last_seen_at = clock_timestamp()
WHERE devices.id = $1 AND EXISTS (
    SELECT 1 FROM runtime_device_authority a
    WHERE a.id = devices.id AND a.credential_hash = $2
)
`

type TouchAuthenticatedDeviceParams struct {
	ID             pgtype.UUID `json:"id"`
	CredentialHash string      `json:"credential_hash"`
}

func (q *Queries) TouchAuthenticatedDevice(ctx context.Context, arg TouchAuthenticatedDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAuthenticatedDevice, arg.ID, arg.CredentialHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
