// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentHostCredential = `-- name: GetAgentHostCredential :one
SELECT COALESCE(credential_hash, '')::text AS credential_hash, credential_revision FROM devices
WHERE id = $1 AND agent_host AND revoked_at IS NULL
`

type GetAgentHostCredentialRow struct {
	CredentialHash     string `json:"credential_hash"`
	CredentialRevision int64  `json:"credential_revision"`
}

func (q *Queries) GetAgentHostCredential(ctx context.Context, id pgtype.UUID) (GetAgentHostCredentialRow, error) {
	row := q.db.QueryRow(ctx, getAgentHostCredential, id)
	var i GetAgentHostCredentialRow
	err := row.Scan(&i.CredentialHash, &i.CredentialRevision)
	return i, err
}

const getEnvironmentResource = `-- name: GetEnvironmentResource :one
SELECT kind, id, generation, credential_hash FROM sandbox_resources
WHERE tenant_id = $1 AND environment_id = $2 AND live
`

type GetEnvironmentResourceParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

type GetEnvironmentResourceRow struct {
	Kind           string      `json:"kind"`
	ID             pgtype.UUID `json:"id"`
	Generation     int64       `json:"generation"`
	CredentialHash pgtype.Text `json:"credential_hash"`
}

// The Environment's live Link resource. An Environment has at most one Link
// resource: its allocation's or its enrollment's.
func (q *Queries) GetEnvironmentResource(ctx context.Context, arg GetEnvironmentResourceParams) (GetEnvironmentResourceRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentResource, arg.TenantID, arg.EnvironmentID)
	var i GetEnvironmentResourceRow
	err := row.Scan(
		&i.Kind,
		&i.ID,
		&i.Generation,
		&i.CredentialHash,
	)
	return i, err
}

const getLinkAssignment = `-- name: GetLinkAssignment :one
SELECT b.session_id, b.runtime_id, b.epoch, b.desired_state = 'bound' AS bound,
    (d.agent_host AND d.revoked_at IS NULL)::boolean AS agent_host, d.credential_revision,
    r.tenant_id AS resource_tenant_id, r.environment_id AS resource_environment_id, r.kind AS resource_kind,
    r.id AS resource_id, r.generation AS resource_generation,
    (COALESCE(s.configuration->'environment'->'network'->>'access', 'enabled') = 'enabled')::boolean AS network_enabled
FROM session_runtime_assignments b
JOIN sessions s ON s.id = b.session_id
JOIN devices d ON d.id = b.runtime_id
LEFT JOIN environments e ON e.session_id = b.session_id
LEFT JOIN sandbox_resources r ON r.environment_id = e.id AND r.live
WHERE b.assignment_id = $1
`

type GetLinkAssignmentRow struct {
	SessionID             pgtype.UUID `json:"session_id"`
	RuntimeID             pgtype.UUID `json:"runtime_id"`
	Epoch                 int64       `json:"epoch"`
	Bound                 bool        `json:"bound"`
	AgentHost             bool        `json:"agent_host"`
	CredentialRevision    int64       `json:"credential_revision"`
	ResourceTenantID      pgtype.UUID `json:"resource_tenant_id"`
	ResourceEnvironmentID pgtype.UUID `json:"resource_environment_id"`
	ResourceKind          pgtype.Text `json:"resource_kind"`
	ResourceID            pgtype.UUID `json:"resource_id"`
	ResourceGeneration    pgtype.Int8 `json:"resource_generation"`
	NetworkEnabled        bool        `json:"network_enabled"`
}

// The assignment with its Runtime's Attach authority, the live Link resource
// of its Session's Environment and that Environment's network access.
func (q *Queries) GetLinkAssignment(ctx context.Context, assignmentID pgtype.UUID) (GetLinkAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getLinkAssignment, assignmentID)
	var i GetLinkAssignmentRow
	err := row.Scan(
		&i.SessionID,
		&i.RuntimeID,
		&i.Epoch,
		&i.Bound,
		&i.AgentHost,
		&i.CredentialRevision,
		&i.ResourceTenantID,
		&i.ResourceEnvironmentID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceGeneration,
		&i.NetworkEnabled,
	)
	return i, err
}

const getSandboxServeAuthority = `-- name: GetSandboxServeAuthority :one
SELECT tenant_id, environment_id, kind, generation, credential_hash FROM sandbox_resources
WHERE id = $1 AND live
`

type GetSandboxServeAuthorityRow struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	Kind           string      `json:"kind"`
	Generation     int64       `json:"generation"`
	CredentialHash pgtype.Text `json:"credential_hash"`
}

func (q *Queries) GetSandboxServeAuthority(ctx context.Context, id pgtype.UUID) (GetSandboxServeAuthorityRow, error) {
	row := q.db.QueryRow(ctx, getSandboxServeAuthority, id)
	var i GetSandboxServeAuthorityRow
	err := row.Scan(
		&i.TenantID,
		&i.EnvironmentID,
		&i.Kind,
		&i.Generation,
		&i.CredentialHash,
	)
	return i, err
}

const listLiveSandboxResources = `-- name: ListLiveSandboxResources :many
SELECT r.tenant_id, r.environment_id, r.kind, r.id, r.generation,
    COALESCE(a.compute_phase NOT IN ('disabled', 'running'), false)::boolean AS quiesced
FROM sandbox_resources r
LEFT JOIN runtime_allocations a ON r.kind = 'allocation' AND a.id = r.id
WHERE r.live
`

type ListLiveSandboxResourcesRow struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Kind          string      `json:"kind"`
	ID            pgtype.UUID `json:"id"`
	Generation    int64       `json:"generation"`
	Quiesced      bool        `json:"quiesced"`
}

// Every live Link resource. Quiesced compute is between a quiesce and the
// wake that resumes it.
func (q *Queries) ListLiveSandboxResources(ctx context.Context) ([]ListLiveSandboxResourcesRow, error) {
	rows, err := q.db.Query(ctx, listLiveSandboxResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSandboxResourcesRow{}
	for rows.Next() {
		var i ListLiveSandboxResourcesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.EnvironmentID,
			&i.Kind,
			&i.ID,
			&i.Generation,
			&i.Quiesced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerAgentHost = `-- name: RegisterAgentHost :one
INSERT INTO devices (id, name, credential_hash, agent_host)
VALUES ($1, 'agent-host', $2, true)
ON CONFLICT (id) DO UPDATE SET credential_hash = EXCLUDED.credential_hash,
    credential_revision = devices.credential_revision + (devices.credential_hash IS DISTINCT FROM EXCLUDED.credential_hash)::int
WHERE devices.agent_host
RETURNING id
`

type RegisterAgentHostParams struct {
	ID             pgtype.UUID `json:"id"`
	CredentialHash pgtype.Text `json:"credential_hash"`
}

// The deployment's agent host, with no tenant, Environment or executor key.
// A new credential advances the revision, which fences the Links the old one
// authenticated; a revocation stays. No row means the ID belongs to a device
// that is not an agent host.
func (q *Queries) RegisterAgentHost(ctx context.Context, arg RegisterAgentHostParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, registerAgentHost, arg.ID, arg.CredentialHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
