// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentHostCredential = `-- name: GetAgentHostCredential :one
SELECT COALESCE(credential_hash, '')::text AS credential_hash, credential_revision FROM devices
WHERE id = $1 AND agent_host AND revoked_at IS NULL
`

type GetAgentHostCredentialRow struct {
	CredentialHash     string `json:"credential_hash"`
	CredentialRevision int64  `json:"credential_revision"`
}

func (q *Queries) GetAgentHostCredential(ctx context.Context, id pgtype.UUID) (GetAgentHostCredentialRow, error) {
	row := q.db.QueryRow(ctx, getAgentHostCredential, id)
	var i GetAgentHostCredentialRow
	err := row.Scan(&i.CredentialHash, &i.CredentialRevision)
	return i, err
}

const getLinkAssignment = `-- name: GetLinkAssignment :one
SELECT b.session_id, b.runtime_id, b.epoch, b.desired_state = 'bound' AS bound,
    d.agent_host AND d.revoked_at IS NULL AS agent_host, d.credential_revision,
    r.tenant_id AS resource_tenant_id, r.environment_id AS resource_environment_id, r.kind AS resource_kind,
    r.id AS resource_id, r.generation AS resource_generation
FROM session_runtime_assignments b
JOIN devices d ON d.id = b.runtime_id
LEFT JOIN environments e ON e.session_id = b.session_id
LEFT JOIN sandbox_resources r ON r.environment_id = e.id AND r.live
WHERE b.assignment_id = $1
`

type GetLinkAssignmentRow struct {
	SessionID             pgtype.UUID `json:"session_id"`
	RuntimeID             pgtype.UUID `json:"runtime_id"`
	Epoch                 int64       `json:"epoch"`
	Bound                 bool        `json:"bound"`
	AgentHost             pgtype.Bool `json:"agent_host"`
	CredentialRevision    int64       `json:"credential_revision"`
	ResourceTenantID      pgtype.UUID `json:"resource_tenant_id"`
	ResourceEnvironmentID pgtype.UUID `json:"resource_environment_id"`
	ResourceKind          pgtype.Text `json:"resource_kind"`
	ResourceID            pgtype.UUID `json:"resource_id"`
	ResourceGeneration    pgtype.Int8 `json:"resource_generation"`
}

// The assignment with its Runtime's Attach authority and the live Link
// resource of its Session's Environment.
func (q *Queries) GetLinkAssignment(ctx context.Context, assignmentID pgtype.UUID) (GetLinkAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getLinkAssignment, assignmentID)
	var i GetLinkAssignmentRow
	err := row.Scan(
		&i.SessionID,
		&i.RuntimeID,
		&i.Epoch,
		&i.Bound,
		&i.AgentHost,
		&i.CredentialRevision,
		&i.ResourceTenantID,
		&i.ResourceEnvironmentID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceGeneration,
	)
	return i, err
}

const getSandboxServeAuthority = `-- name: GetSandboxServeAuthority :one
SELECT tenant_id, environment_id, generation, credential_hash FROM sandbox_resources
WHERE kind = $1 AND id = $2 AND live
`

type GetSandboxServeAuthorityParams struct {
	Kind string      `json:"kind"`
	ID   pgtype.UUID `json:"id"`
}

type GetSandboxServeAuthorityRow struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	Generation     int64       `json:"generation"`
	CredentialHash pgtype.Text `json:"credential_hash"`
}

func (q *Queries) GetSandboxServeAuthority(ctx context.Context, arg GetSandboxServeAuthorityParams) (GetSandboxServeAuthorityRow, error) {
	row := q.db.QueryRow(ctx, getSandboxServeAuthority, arg.Kind, arg.ID)
	var i GetSandboxServeAuthorityRow
	err := row.Scan(
		&i.TenantID,
		&i.EnvironmentID,
		&i.Generation,
		&i.CredentialHash,
	)
	return i, err
}
