// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_generations.sql

package sqlc

import (
	"context"
)

const clearSandboxGenerations = `-- name: ClearSandboxGenerations :exec
DELETE FROM runtime_deployment_generations
`

func (q *Queries) ClearSandboxGenerations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearSandboxGenerations)
	return err
}

const collectSandboxGenerations = `-- name: CollectSandboxGenerations :exec
DELETE FROM runtime_deployment_generations WHERE generation IN (SELECT g.generation FROM runtime_deployment_generations g WHERE g.generation <> (SELECT generation FROM runtime_deployment)
AND NOT EXISTS(SELECT 1 FROM runtime_allocations a WHERE a.state <> 'released' AND a.deployment_generation=g.generation)
AND NOT EXISTS(SELECT 1 FROM runtime_placements p WHERE p.released_at IS NULL AND p.deployment_generation=g.generation)
AND NOT EXISTS(SELECT 1 FROM runtime_nodes n WHERE n.removed_at IS NULL AND n.ready_generation=g.generation) ORDER BY g.generation LIMIT 32)
`

func (q *Queries) CollectSandboxGenerations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, collectSandboxGenerations)
	return err
}

const getSandboxGeneration = `-- name: GetSandboxGeneration :one
SELECT generation, provider_kind, specification, e2b_template, e2b_template_build_status, e2b_template_cpus, e2b_template_memory_mib, e2b_template_root_disk_mib, created_at, e2b_api_url, e2b_domain FROM runtime_deployment_generations WHERE generation=$1
`

func (q *Queries) GetSandboxGeneration(ctx context.Context, generation int64) (RuntimeDeploymentGeneration, error) {
	row := q.db.QueryRow(ctx, getSandboxGeneration, generation)
	var i RuntimeDeploymentGeneration
	err := row.Scan(
		&i.Generation,
		&i.ProviderKind,
		&i.Specification,
		&i.E2bTemplate,
		&i.E2bTemplateBuildStatus,
		&i.E2bTemplateCpus,
		&i.E2bTemplateMemoryMib,
		&i.E2bTemplateRootDiskMib,
		&i.CreatedAt,
		&i.E2bApiUrl,
		&i.E2bDomain,
	)
	return i, err
}

const listSandboxGenerations = `-- name: ListSandboxGenerations :many
SELECT generation, provider_kind, specification, e2b_template, e2b_template_build_status, e2b_template_cpus, e2b_template_memory_mib, e2b_template_root_disk_mib, created_at, e2b_api_url, e2b_domain FROM runtime_deployment_generations WHERE generation > $1 ORDER BY generation LIMIT 32
`

func (q *Queries) ListSandboxGenerations(ctx context.Context, generation int64) ([]RuntimeDeploymentGeneration, error) {
	rows, err := q.db.Query(ctx, listSandboxGenerations, generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeDeploymentGeneration{}
	for rows.Next() {
		var i RuntimeDeploymentGeneration
		if err := rows.Scan(
			&i.Generation,
			&i.ProviderKind,
			&i.Specification,
			&i.E2bTemplate,
			&i.E2bTemplateBuildStatus,
			&i.E2bTemplateCpus,
			&i.E2bTemplateMemoryMib,
			&i.E2bTemplateRootDiskMib,
			&i.CreatedAt,
			&i.E2bApiUrl,
			&i.E2bDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retainSandboxGeneration = `-- name: RetainSandboxGeneration :exec
INSERT INTO runtime_deployment_generations(generation,provider_kind,specification,e2b_template,e2b_template_build_status,e2b_template_cpus,e2b_template_memory_mib,e2b_template_root_disk_mib,e2b_api_url,e2b_domain)
SELECT generation,provider_kind,specification,e2b_template,e2b_template_build_status,e2b_template_cpus,e2b_template_memory_mib,e2b_template_root_disk_mib,e2b_api_url,e2b_domain
FROM runtime_deployment d WHERE provider_kind <> '' AND (
 EXISTS(SELECT 1 FROM runtime_allocations a WHERE a.state <> 'released' AND a.deployment_generation=d.generation)
 OR EXISTS(SELECT 1 FROM runtime_placements p WHERE p.released_at IS NULL AND p.deployment_generation=d.generation)
 OR EXISTS(SELECT 1 FROM runtime_nodes n WHERE n.removed_at IS NULL AND n.ready_generation=d.generation))
`

func (q *Queries) RetainSandboxGeneration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retainSandboxGeneration)
	return err
}
