// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheduling.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSessionTurn = `-- name: GetLatestSessionTurn :one
SELECT id, session_id, status, created_at, started_at, completed_at, cancel_requested_at, outcome, event_count, event_bytes, token_usage, artifact_capture_started FROM turns WHERE session_id = $1 ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLatestSessionTurn(ctx context.Context, sessionID pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, getLatestSessionTurn, sessionID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.TokenUsage,
		&i.ArtifactCaptureStarted,
	)
	return i, err
}

const listEnvironmentInputWork = `-- name: ListEnvironmentInputWork :many
SELECT r.id, r.session_id, s.tenant_id
FROM environment_input_reservations r
JOIN sessions s ON s.id = r.session_id
LEFT JOIN session_devices b ON b.session_id = s.id
WHERE r.state = 'pending' AND r.deadline > clock_timestamp()
AND r.id > $1::uuid AND s.deleted_at IS NULL
AND EXISTS (
    SELECT 1 FROM devices d WHERE d.tenant_id = s.tenant_id AND d.revoked_at IS NULL
        AND d.id = ANY($2::uuid[])
        AND (b.device_id IS NULL OR d.id = b.device_id)
)
ORDER BY r.id LIMIT 100
`

type ListEnvironmentInputWorkParams struct {
	AfterID          pgtype.UUID   `json:"after_id"`
	ConnectedDevices []pgtype.UUID `json:"connected_devices"`
}

type ListEnvironmentInputWorkRow struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListEnvironmentInputWork(ctx context.Context, arg ListEnvironmentInputWorkParams) ([]ListEnvironmentInputWorkRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentInputWork, arg.AfterID, arg.ConnectedDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentInputWorkRow{}
	for rows.Next() {
		var i ListEnvironmentInputWorkRow
		if err := rows.Scan(&i.ID, &i.SessionID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionDevices = `-- name: ListExecutionDevices :many
SELECT id, name FROM devices
WHERE tenant_id = $1 AND revoked_at IS NULL AND environment_id IS NULL
ORDER BY id
`

type ListExecutionDevicesRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListExecutionDevices(ctx context.Context, tenantID pgtype.UUID) ([]ListExecutionDevicesRow, error) {
	rows, err := q.db.Query(ctx, listExecutionDevices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionDevicesRow{}
	for rows.Next() {
		var i ListExecutionDevicesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionWork = `-- name: ListExecutionWork :many
SELECT t.id, t.session_id, s.tenant_id, t.status
FROM turns t JOIN sessions s ON s.id = t.session_id
WHERE t.status = ANY($1::text[]) AND t.id > $2::uuid
AND (s.deleted_at IS NULL OR t.status <> 'queued')
AND (NOT $3::boolean OR EXISTS (
    SELECT 1 FROM devices d WHERE d.tenant_id = s.tenant_id AND d.revoked_at IS NULL
        AND d.id = ANY($4::uuid[])
))
ORDER BY t.id LIMIT 100
`

type ListExecutionWorkParams struct {
	Statuses         []string      `json:"statuses"`
	AfterID          pgtype.UUID   `json:"after_id"`
	ConnectedOnly    bool          `json:"connected_only"`
	ConnectedDevices []pgtype.UUID `json:"connected_devices"`
}

type ListExecutionWorkRow struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Status    string      `json:"status"`
}

func (q *Queries) ListExecutionWork(ctx context.Context, arg ListExecutionWorkParams) ([]ListExecutionWorkRow, error) {
	rows, err := q.db.Query(ctx, listExecutionWork,
		arg.Statuses,
		arg.AfterID,
		arg.ConnectedOnly,
		arg.ConnectedDevices,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionWorkRow{}
	for rows.Next() {
		var i ListExecutionWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TenantID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryExecutionLease = `-- name: TryExecutionLease :one
SELECT pg_try_advisory_lock(706172736172::bigint)::boolean
`

func (q *Queries) TryExecutionLease(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryExecutionLease)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
