// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishSessionItems = `-- name: FinishSessionItems :exec
WITH observed AS MATERIALIZED (SELECT clock_timestamp() AS at)
UPDATE session_items SET payload = jsonb_set(payload, '{status}', to_jsonb($1::text)),
    settled_at = COALESCE(session_items.settled_at, observed.at)
FROM observed
WHERE session_id = $2 AND id = ANY($3::uuid[])
`

type FinishSessionItemsParams struct {
	Status    string        `json:"status"`
	SessionID pgtype.UUID   `json:"session_id"`
	Ids       []pgtype.UUID `json:"ids"`
}

// The finished Items share one settlement time; an Item keeps a settlement
// time it already has.
func (q *Queries) FinishSessionItems(ctx context.Context, arg FinishSessionItemsParams) error {
	_, err := q.db.Exec(ctx, finishSessionItems, arg.Status, arg.SessionID, arg.Ids)
	return err
}

const getSessionItem = `-- name: GetSessionItem :one
SELECT id, session_id, turn_id, created_at, position, payload, output_index, settled_at FROM session_items WHERE session_id = $1 AND id = $2
`

type GetSessionItemParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetSessionItem(ctx context.Context, arg GetSessionItemParams) (SessionItem, error) {
	row := q.db.QueryRow(ctx, getSessionItem, arg.SessionID, arg.ID)
	var i SessionItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.CreatedAt,
		&i.Position,
		&i.Payload,
		&i.OutputIndex,
		&i.SettledAt,
	)
	return i, err
}

const hasNativeMessageItem = `-- name: HasNativeMessageItem :one
SELECT EXISTS(SELECT 1 FROM session_items WHERE turn_id = $1
    AND payload->>'role' = 'assistant' AND id <> $2)
`

type HasNativeMessageItemParams struct {
	TurnID pgtype.UUID `json:"turn_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) HasNativeMessageItem(ctx context.Context, arg HasNativeMessageItemParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasNativeMessageItem, arg.TurnID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const itemEventSources = `-- name: ItemEventSources :many
SELECT session_id, turn_id, ordinal, kind, payload, created_at FROM turn_events WHERE session_id = $1 AND turn_id = $2 AND ordinal >= $3 ORDER BY ordinal
`

type ItemEventSourcesParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	Ordinal   int32       `json:"ordinal"`
}

func (q *Queries) ItemEventSources(ctx context.Context, arg ItemEventSourcesParams) ([]TurnEvent, error) {
	rows, err := q.db.Query(ctx, itemEventSources, arg.SessionID, arg.TurnID, arg.Ordinal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TurnEvent{}
	for rows.Next() {
		var i TurnEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnID,
			&i.Ordinal,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemInputSource = `-- name: ItemInputSource :one
SELECT sequence, session_id, turn_id, idempotency_key, kind, payload, created_at, batch_position FROM turn_inputs WHERE session_id = $1 AND sequence = $2
`

type ItemInputSourceParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Sequence  int64       `json:"sequence"`
}

func (q *Queries) ItemInputSource(ctx context.Context, arg ItemInputSourceParams) (TurnInput, error) {
	row := q.db.QueryRow(ctx, itemInputSource, arg.SessionID, arg.Sequence)
	var i TurnInput
	err := row.Scan(
		&i.Sequence,
		&i.SessionID,
		&i.TurnID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
		&i.BatchPosition,
	)
	return i, err
}

const listSessionItems = `-- name: ListSessionItems :many
SELECT i.id, i.created_at,
    (CASE WHEN i.payload->>'status' = 'in_progress' AND t.status IN ('completed', 'failed', 'cancelled')
         THEN jsonb_set(i.payload, '{status}', '"incomplete"') ELSE i.payload END)::jsonb AS payload
FROM session_items i JOIN turns t ON t.id = i.turn_id
WHERE i.session_id = $1
  AND ($2::timestamptz IS NULL
       OR ($3::boolean AND (i.created_at, i.position, i.id) > ($2::timestamptz, $4::integer, $5::uuid))
       OR (NOT $3::boolean AND (i.created_at, i.position, i.id) < ($2::timestamptz, $4::integer, $5::uuid)))
ORDER BY
    CASE WHEN $3::boolean THEN i.created_at END ASC,
    CASE WHEN $3::boolean THEN i.position END ASC,
    CASE WHEN $3::boolean THEN i.id END ASC,
    CASE WHEN NOT $3::boolean THEN i.created_at END DESC,
    CASE WHEN NOT $3::boolean THEN i.position END DESC,
    CASE WHEN NOT $3::boolean THEN i.id END DESC
LIMIT $6
`

type ListSessionItemsParams struct {
	SessionID     pgtype.UUID        `json:"session_id"`
	AfterCreated  pgtype.Timestamptz `json:"after_created"`
	Ascending     bool               `json:"ascending"`
	AfterPosition int32              `json:"after_position"`
	AfterID       pgtype.UUID        `json:"after_id"`
	PageLimit     int32              `json:"page_limit"`
}

type ListSessionItemsRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Payload   []byte             `json:"payload"`
}

func (q *Queries) ListSessionItems(ctx context.Context, arg ListSessionItemsParams) ([]ListSessionItemsRow, error) {
	rows, err := q.db.Query(ctx, listSessionItems,
		arg.SessionID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterPosition,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionItemsRow{}
	for rows.Next() {
		var i ListSessionItemsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnItemDiagnostics = `-- name: ListTurnItemDiagnostics :many
SELECT id, created_at, settled_at FROM session_items
WHERE session_id = $1 AND turn_id = $2
ORDER BY created_at, position, id
LIMIT 1001
`

type ListTurnItemDiagnosticsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

type ListTurnItemDiagnosticsRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SettledAt pgtype.Timestamptz `json:"settled_at"`
}

func (q *Queries) ListTurnItemDiagnostics(ctx context.Context, arg ListTurnItemDiagnosticsParams) ([]ListTurnItemDiagnosticsRow, error) {
	rows, err := q.db.Query(ctx, listTurnItemDiagnostics, arg.SessionID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTurnItemDiagnosticsRow{}
	for rows.Next() {
		var i ListTurnItemDiagnosticsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.SettledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedSessionItems = `-- name: ListUnfinishedSessionItems :many
SELECT id, position, output_index, payload FROM session_items
WHERE session_id = $1 AND turn_id = $2 AND payload->>'status' = 'in_progress'
`

type ListUnfinishedSessionItemsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

type ListUnfinishedSessionItemsRow struct {
	ID          pgtype.UUID `json:"id"`
	Position    int32       `json:"position"`
	OutputIndex pgtype.Int4 `json:"output_index"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) ListUnfinishedSessionItems(ctx context.Context, arg ListUnfinishedSessionItemsParams) ([]ListUnfinishedSessionItemsRow, error) {
	rows, err := q.db.Query(ctx, listUnfinishedSessionItems, arg.SessionID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnfinishedSessionItemsRow{}
	for rows.Next() {
		var i ListUnfinishedSessionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.OutputIndex,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSessionItem = `-- name: PutSessionItem :one
INSERT INTO session_items(id, session_id, turn_id, created_at, payload, position, output_index, settled_at)
VALUES ($1, $2, $3, $4, $5,
    (SELECT COALESCE(max(position), -1) + 1 FROM session_items WHERE session_id = $2),
    CASE WHEN $6::boolean THEN
        (SELECT COALESCE(max(output_index), -1) + 1 FROM session_items WHERE turn_id = $3)
    END,
    CASE WHEN $5::jsonb->>'status' IN ('completed', 'incomplete', 'failed') THEN $4::timestamptz END)
ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload,
    settled_at = CASE WHEN session_items.payload->>'status' = 'in_progress'
        AND EXCLUDED.payload->>'status' IN ('completed', 'incomplete', 'failed')
        THEN COALESCE(session_items.settled_at, EXCLUDED.created_at) ELSE session_items.settled_at END
RETURNING id, session_id, turn_id, created_at, position, payload, output_index, settled_at
`

type PutSessionItemParams struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	TurnID    pgtype.UUID        `json:"turn_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Payload   []byte             `json:"payload"`
	IsOutput  bool               `json:"is_output"`
}

func (q *Queries) PutSessionItem(ctx context.Context, arg PutSessionItemParams) (SessionItem, error) {
	row := q.db.QueryRow(ctx, putSessionItem,
		arg.ID,
		arg.SessionID,
		arg.TurnID,
		arg.CreatedAt,
		arg.Payload,
		arg.IsOutput,
	)
	var i SessionItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.CreatedAt,
		&i.Position,
		&i.Payload,
		&i.OutputIndex,
		&i.SettledAt,
	)
	return i, err
}
