// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginTurnArtifactCapture = `-- name: BeginTurnArtifactCapture :execrows
UPDATE turns SET artifact_capture_started = true
WHERE session_id = $1 AND id = $2 AND NOT artifact_capture_started
`

type BeginTurnArtifactCaptureParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) BeginTurnArtifactCapture(ctx context.Context, arg BeginTurnArtifactCaptureParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginTurnArtifactCapture, arg.SessionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionArtifact = `-- name: DeleteSessionArtifact :one
DELETE FROM session_artifacts a USING sessions s
WHERE s.id = a.session_id AND s.tenant_id = $1 AND s.deleted_at IS NULL
AND a.session_id = $2 AND a.id = $3 AND a.created_at IS NOT NULL
RETURNING a.body_oid
`

type DeleteSessionArtifactParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteSessionArtifact(ctx context.Context, arg DeleteSessionArtifactParams) (pgtype.Uint32, error) {
	row := q.db.QueryRow(ctx, deleteSessionArtifact, arg.TenantID, arg.SessionID, arg.ID)
	var body_oid pgtype.Uint32
	err := row.Scan(&body_oid)
	return body_oid, err
}

const deleteSessionArtifacts = `-- name: DeleteSessionArtifacts :exec
WITH removed AS (
    DELETE FROM session_artifacts WHERE session_id = $1 RETURNING body_oid
)
SELECT lo_unlink(body_oid) FROM removed
`

func (q *Queries) DeleteSessionArtifacts(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionArtifacts, sessionID)
	return err
}

const deleteUnchangedTurnArtifacts = `-- name: DeleteUnchangedTurnArtifacts :exec
WITH newest AS (
    SELECT DISTINCT ON (published.path) published.path, published.sha256
    FROM session_artifacts published
    JOIN turns producer ON producer.session_id = published.session_id AND producer.id = published.turn_id
    WHERE published.session_id = $1 AND published.created_at IS NOT NULL
    ORDER BY published.path, producer.created_at DESC, producer.id DESC
), removed AS (
    DELETE FROM session_artifacts staged USING newest
    WHERE staged.session_id = $1 AND staged.turn_id = $2 AND staged.created_at IS NULL
      AND staged.path = newest.path AND staged.sha256 = newest.sha256
    RETURNING staged.body_oid
)
SELECT lo_unlink(body_oid) FROM removed
`

type DeleteUnchangedTurnArtifactsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

// A staged path is not republished while the newest remaining published
// Artifact for that path in the Session has the same bytes. Newest follows the
// producing Turn's database creation time: Turns in a Session are serialized,
// while publication time may come from the Runtime's reported completion.
func (q *Queries) DeleteUnchangedTurnArtifacts(ctx context.Context, arg DeleteUnchangedTurnArtifactsParams) error {
	_, err := q.db.Exec(ctx, deleteUnchangedTurnArtifacts, arg.SessionID, arg.TurnID)
	return err
}

const deleteUnpublishedTurnArtifacts = `-- name: DeleteUnpublishedTurnArtifacts :exec
WITH removed AS (
    DELETE FROM session_artifacts WHERE session_id = $1 AND turn_id = $2 AND created_at IS NULL RETURNING body_oid
)
SELECT lo_unlink(body_oid) FROM removed
`

type DeleteUnpublishedTurnArtifactsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

func (q *Queries) DeleteUnpublishedTurnArtifacts(ctx context.Context, arg DeleteUnpublishedTurnArtifactsParams) error {
	_, err := q.db.Exec(ctx, deleteUnpublishedTurnArtifacts, arg.SessionID, arg.TurnID)
	return err
}

const getSessionArtifact = `-- name: GetSessionArtifact :one
SELECT a.id, a.session_id, a.turn_id, a.environment_id, a.path, a.size_bytes, a.body_oid, a.sha256, a.created_at FROM session_artifacts a JOIN sessions s ON s.id = a.session_id
WHERE s.tenant_id = $1 AND s.deleted_at IS NULL AND a.session_id = $2 AND a.id = $3 AND a.created_at IS NOT NULL
`

type GetSessionArtifactParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetSessionArtifact(ctx context.Context, arg GetSessionArtifactParams) (SessionArtifact, error) {
	row := q.db.QueryRow(ctx, getSessionArtifact, arg.TenantID, arg.SessionID, arg.ID)
	var i SessionArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.EnvironmentID,
		&i.Path,
		&i.SizeBytes,
		&i.BodyOid,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionArtifacts = `-- name: ListSessionArtifacts :many
SELECT a.id, a.session_id, a.turn_id, a.environment_id, a.path, a.size_bytes, a.body_oid, a.sha256, a.created_at FROM session_artifacts a JOIN sessions s ON s.id = a.session_id
WHERE s.tenant_id = $1 AND s.deleted_at IS NULL
  AND a.session_id = $2 AND a.created_at IS NOT NULL
  AND ($3::uuid IS NULL OR a.environment_id = $3::uuid)
  AND ($4::timestamptz IS NULL
       OR (NOT $5::boolean AND (a.created_at, a.id) < ($4::timestamptz, $6::uuid))
       OR ($5::boolean AND (a.created_at, a.id) > ($4::timestamptz, $6::uuid)))
ORDER BY
    CASE WHEN $5::boolean THEN a.created_at END ASC,
    CASE WHEN $5::boolean THEN a.id END ASC,
    CASE WHEN NOT $5::boolean THEN a.created_at END DESC,
    CASE WHEN NOT $5::boolean THEN a.id END DESC
LIMIT $7
`

type ListSessionArtifactsParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	AfterCreated  pgtype.Timestamptz `json:"after_created"`
	Ascending     bool               `json:"ascending"`
	AfterID       pgtype.UUID        `json:"after_id"`
	PageLimit     int32              `json:"page_limit"`
}

func (q *Queries) ListSessionArtifacts(ctx context.Context, arg ListSessionArtifactsParams) ([]SessionArtifact, error) {
	rows, err := q.db.Query(ctx, listSessionArtifacts,
		arg.TenantID,
		arg.SessionID,
		arg.EnvironmentID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionArtifact{}
	for rows.Next() {
		var i SessionArtifact
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.EnvironmentID,
			&i.Path,
			&i.SizeBytes,
			&i.BodyOid,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishTurnArtifacts = `-- name: PublishTurnArtifacts :exec
UPDATE session_artifacts SET created_at = $3
WHERE session_id = $1 AND turn_id = $2 AND created_at IS NULL
`

type PublishTurnArtifactsParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	TurnID    pgtype.UUID        `json:"turn_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) PublishTurnArtifacts(ctx context.Context, arg PublishTurnArtifactsParams) error {
	_, err := q.db.Exec(ctx, publishTurnArtifacts, arg.SessionID, arg.TurnID, arg.CreatedAt)
	return err
}

const stageSessionArtifact = `-- name: StageSessionArtifact :exec
INSERT INTO session_artifacts (id, session_id, turn_id, environment_id, path, size_bytes, body_oid, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type StageSessionArtifactParams struct {
	ID            pgtype.UUID   `json:"id"`
	SessionID     pgtype.UUID   `json:"session_id"`
	TurnID        pgtype.UUID   `json:"turn_id"`
	EnvironmentID pgtype.UUID   `json:"environment_id"`
	Path          string        `json:"path"`
	SizeBytes     int64         `json:"size_bytes"`
	BodyOid       pgtype.Uint32 `json:"body_oid"`
	Sha256        string        `json:"sha256"`
}

func (q *Queries) StageSessionArtifact(ctx context.Context, arg StageSessionArtifactParams) error {
	_, err := q.db.Exec(ctx, stageSessionArtifact,
		arg.ID,
		arg.SessionID,
		arg.TurnID,
		arg.EnvironmentID,
		arg.Path,
		arg.SizeBytes,
		arg.BodyOid,
		arg.Sha256,
	)
	return err
}
