// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendSessionEvent = `-- name: AppendSessionEvent :exec
WITH next AS (
    UPDATE sessions SET event_sequence = event_sequence + 1 WHERE id = $1
    RETURNING id, event_sequence
)
INSERT INTO session_events(session_id, sequence, payload)
SELECT id, event_sequence, $2 FROM next
`

type AppendSessionEventParams struct {
	ID      pgtype.UUID `json:"id"`
	Payload []byte      `json:"payload"`
}

func (q *Queries) AppendSessionEvent(ctx context.Context, arg AppendSessionEventParams) error {
	_, err := q.db.Exec(ctx, appendSessionEvent, arg.ID, arg.Payload)
	return err
}

const finishSessionItems = `-- name: FinishSessionItems :many
WITH observed AS MATERIALIZED (SELECT clock_timestamp() AS at)
UPDATE session_items SET payload = jsonb_set(payload, '{status}', '"incomplete"'), settled_at = COALESCE(session_items.settled_at, observed.at)
FROM observed
WHERE session_id = $1 AND turn_id = $2 AND payload->>'status' = 'in_progress'
RETURNING session_items.id, session_items.session_id, session_items.turn_id, session_items.created_at, session_items.position, session_items.payload, session_items.output_index, session_items.settled_at
`

type FinishSessionItemsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

func (q *Queries) FinishSessionItems(ctx context.Context, arg FinishSessionItemsParams) ([]SessionItem, error) {
	rows, err := q.db.Query(ctx, finishSessionItems, arg.SessionID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionItem{}
	for rows.Next() {
		var i SessionItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.CreatedAt,
			&i.Position,
			&i.Payload,
			&i.OutputIndex,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT sequence, payload FROM (
    SELECT e.sequence, e.payload,
        row_number() OVER (ORDER BY e.sequence) AS n,
        sum(e.payload_bytes) OVER (ORDER BY e.sequence) AS bytes
    FROM session_events e JOIN sessions s ON s.id = e.session_id
    WHERE s.tenant_id = $1 AND s.deleted_at IS NULL AND e.session_id = $2 AND e.sequence > $3
) AS pending WHERE n = 1 OR bytes <= 1048576
ORDER BY sequence LIMIT 32
`

type ListSessionEventsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Sequence  int64       `json:"sequence"`
}

type ListSessionEventsRow struct {
	Sequence int64  `json:"sequence"`
	Payload  []byte `json:"payload"`
}

func (q *Queries) ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]ListSessionEventsRow, error) {
	rows, err := q.db.Query(ctx, listSessionEvents, arg.TenantID, arg.SessionID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionEventsRow{}
	for rows.Next() {
		var i ListSessionEventsRow
		if err := rows.Scan(&i.Sequence, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSessionEvents = `-- name: PruneSessionEvents :exec
WITH retained AS (
    SELECT sequence, row_number() OVER (ORDER BY sequence DESC) AS n,
        sum(payload_bytes) OVER (ORDER BY sequence DESC) AS bytes
    FROM session_events e WHERE e.session_id = $1
)
DELETE FROM session_events e WHERE e.session_id = $1 AND e.sequence IN (
    SELECT sequence FROM retained WHERE n > 256 OR (bytes > 67108864 AND n > 1)
)
`

func (q *Queries) PruneSessionEvents(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pruneSessionEvents, sessionID)
	return err
}

const sessionEventCursor = `-- name: SessionEventCursor :one
SELECT event_sequence FROM sessions WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SessionEventCursorParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SessionEventCursor(ctx context.Context, arg SessionEventCursorParams) (int64, error) {
	row := q.db.QueryRow(ctx, sessionEventCursor, arg.TenantID, arg.ID)
	var event_sequence int64
	err := row.Scan(&event_sequence)
	return event_sequence, err
}

const sessionEventTurn = `-- name: SessionEventTurn :one
SELECT id, session_id, status, created_at, started_at, completed_at, cancel_requested_at, outcome, event_count, event_bytes, token_usage, artifact_capture_started FROM turns WHERE session_id = $1 AND id = $2
`

type SessionEventTurnParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SessionEventTurn(ctx context.Context, arg SessionEventTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, sessionEventTurn, arg.SessionID, arg.ID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.TokenUsage,
		&i.ArtifactCaptureStarted,
	)
	return i, err
}
