// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_execution_configuration.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionExecutionConfiguration = `-- name: GetSessionExecutionConfiguration :one
SELECT s.id, s.engine, s.configuration AS session_configuration,
       p.configuration AS execution_configuration
FROM sessions s
LEFT JOIN session_execution_configuration p ON p.session_id = s.id
WHERE s.tenant_id = $1 AND s.id = $2 AND s.deleted_at IS NULL
`

type GetSessionExecutionConfigurationParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type GetSessionExecutionConfigurationRow struct {
	ID                     pgtype.UUID `json:"id"`
	Engine                 string      `json:"engine"`
	SessionConfiguration   []byte      `json:"session_configuration"`
	ExecutionConfiguration []byte      `json:"execution_configuration"`
}

func (q *Queries) GetSessionExecutionConfiguration(ctx context.Context, arg GetSessionExecutionConfigurationParams) (GetSessionExecutionConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getSessionExecutionConfiguration, arg.TenantID, arg.SessionID)
	var i GetSessionExecutionConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.SessionConfiguration,
		&i.ExecutionConfiguration,
	)
	return i, err
}

const saveSessionExecutionConfiguration = `-- name: SaveSessionExecutionConfiguration :exec
INSERT INTO session_execution_configuration(session_id, configuration, deployment_provider_revision)
VALUES ($1, $2, $3)
`

type SaveSessionExecutionConfigurationParams struct {
	SessionID                  pgtype.UUID `json:"session_id"`
	Configuration              []byte      `json:"configuration"`
	DeploymentProviderRevision pgtype.UUID `json:"deployment_provider_revision"`
}

func (q *Queries) SaveSessionExecutionConfiguration(ctx context.Context, arg SaveSessionExecutionConfigurationParams) error {
	_, err := q.db.Exec(ctx, saveSessionExecutionConfiguration, arg.SessionID, arg.Configuration, arg.DeploymentProviderRevision)
	return err
}
