// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_model_execution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionModelExecution = `-- name: GetSessionModelExecution :one
SELECT e.encrypted_config FROM session_model_execution e
JOIN sessions s ON s.id = e.session_id WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSessionModelExecutionParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetSessionModelExecution(ctx context.Context, arg GetSessionModelExecutionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSessionModelExecution, arg.TenantID, arg.SessionID)
	var encrypted_config []byte
	err := row.Scan(&encrypted_config)
	return encrypted_config, err
}

const saveSessionModelExecution = `-- name: SaveSessionModelExecution :exec
INSERT INTO session_model_execution(session_id, encrypted_config) VALUES ($1, $2)
`

type SaveSessionModelExecutionParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	EncryptedConfig []byte      `json:"encrypted_config"`
}

func (q *Queries) SaveSessionModelExecution(ctx context.Context, arg SaveSessionModelExecutionParams) error {
	_, err := q.db.Exec(ctx, saveSessionModelExecution, arg.SessionID, arg.EncryptedConfig)
	return err
}
