// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: turn_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTurnEvent = `-- name: CountTurnEvent :exec
UPDATE turns SET event_count = event_count + $3::integer, event_bytes = event_bytes + $4::bigint
WHERE session_id = $1 AND id = $2
`

type CountTurnEventParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ID           pgtype.UUID `json:"id"`
	EventCount   int32       `json:"event_count"`
	PayloadBytes int64       `json:"payload_bytes"`
}

func (q *Queries) CountTurnEvent(ctx context.Context, arg CountTurnEventParams) error {
	_, err := q.db.Exec(ctx, countTurnEvent,
		arg.SessionID,
		arg.ID,
		arg.EventCount,
		arg.PayloadBytes,
	)
	return err
}

const insertTurnEvent = `-- name: InsertTurnEvent :exec
INSERT INTO turn_events(session_id, turn_id, ordinal, kind, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTurnEventParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	Ordinal   int32       `json:"ordinal"`
	Kind      string      `json:"kind"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) InsertTurnEvent(ctx context.Context, arg InsertTurnEventParams) error {
	_, err := q.db.Exec(ctx, insertTurnEvent,
		arg.SessionID,
		arg.TurnID,
		arg.Ordinal,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const insertTurnEventBatch = `-- name: InsertTurnEventBatch :exec
INSERT INTO turn_events(session_id, turn_id, ordinal, kind, payload)
SELECT $1, $2, $3::integer + item.n::integer - 1, item.value->>'kind', item.value->'payload'
FROM jsonb_array_elements($4::jsonb) WITH ORDINALITY AS item(value, n)
`

type InsertTurnEventBatchParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	TurnID       pgtype.UUID `json:"turn_id"`
	FirstOrdinal int32       `json:"first_ordinal"`
	Batch        []byte      `json:"batch"`
}

func (q *Queries) InsertTurnEventBatch(ctx context.Context, arg InsertTurnEventBatchParams) error {
	_, err := q.db.Exec(ctx, insertTurnEventBatch,
		arg.SessionID,
		arg.TurnID,
		arg.FirstOrdinal,
		arg.Batch,
	)
	return err
}

const listTurnEvents = `-- name: ListTurnEvents :many
SELECT e.session_id, e.turn_id, e.ordinal, e.kind, e.payload, e.created_at FROM turn_events e JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND e.session_id = $2 AND e.turn_id = $3 AND e.ordinal > $4
ORDER BY e.ordinal LIMIT $5
`

type ListTurnEventsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	Ordinal   int32       `json:"ordinal"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTurnEvents(ctx context.Context, arg ListTurnEventsParams) ([]TurnEvent, error) {
	rows, err := q.db.Query(ctx, listTurnEvents,
		arg.TenantID,
		arg.SessionID,
		arg.TurnID,
		arg.Ordinal,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TurnEvent{}
	for rows.Next() {
		var i TurnEvent
		if err := rows.Scan(
			&i.SessionID,
			&i.TurnID,
			&i.Ordinal,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchTurnEventBatch = `-- name: MatchTurnEventBatch :one
SELECT COALESCE(jsonb_agg(jsonb_build_object('kind', e.kind, 'payload', e.payload) ORDER BY ordinal)
    = $3::jsonb, false)::boolean AS matches
FROM turn_events e WHERE session_id = $1 AND turn_id = $2
    AND ordinal >= $4 AND ordinal < $4::integer + $5::integer
`

type MatchTurnEventBatchParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	TurnID       pgtype.UUID `json:"turn_id"`
	Batch        []byte      `json:"batch"`
	FirstOrdinal int32       `json:"first_ordinal"`
	EventCount   int32       `json:"event_count"`
}

func (q *Queries) MatchTurnEventBatch(ctx context.Context, arg MatchTurnEventBatchParams) (bool, error) {
	row := q.db.QueryRow(ctx, matchTurnEventBatch,
		arg.SessionID,
		arg.TurnID,
		arg.Batch,
		arg.FirstOrdinal,
		arg.EventCount,
	)
	var matches bool
	err := row.Scan(&matches)
	return matches, err
}
