// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vault_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaticCredential = `-- name: CreateStaticCredential :one
INSERT INTO vault_credentials (id, vault_id, name, auth_type, mcp_server_url, token_ciphertext)
SELECT $1, v.id, $2, 'static_bearer', $3, $4
FROM vaults v
WHERE v.tenant_id = $5 AND v.id = $6
RETURNING id, vault_id, name, auth_type, mcp_server_url, created_at, updated_at, oauth_metadata
`

type CreateStaticCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	McpServerUrl    string      `json:"mcp_server_url"`
	TokenCiphertext []byte      `json:"token_ciphertext"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
}

type CreateStaticCredentialRow struct {
	ID            pgtype.UUID        `json:"id"`
	VaultID       pgtype.UUID        `json:"vault_id"`
	Name          string             `json:"name"`
	AuthType      string             `json:"auth_type"`
	McpServerUrl  string             `json:"mcp_server_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata []byte             `json:"oauth_metadata"`
}

func (q *Queries) CreateStaticCredential(ctx context.Context, arg CreateStaticCredentialParams) (CreateStaticCredentialRow, error) {
	row := q.db.QueryRow(ctx, createStaticCredential,
		arg.ID,
		arg.Name,
		arg.McpServerUrl,
		arg.TokenCiphertext,
		arg.TenantID,
		arg.VaultID,
	)
	var i CreateStaticCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthMetadata,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :one
DELETE FROM vault_credentials c
USING vaults v
WHERE v.id = c.vault_id AND v.tenant_id = $1
  AND v.id = $2 AND c.id = $3
RETURNING c.id
`

type DeleteCredentialParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	VaultID  pgtype.UUID `json:"vault_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCredential, arg.TenantID, arg.VaultID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCredential = `-- name: GetCredential :one
SELECT c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at, c.oauth_metadata
FROM vault_credentials c
JOIN vaults v ON v.id = c.vault_id
WHERE v.tenant_id = $1 AND v.id = $2 AND c.id = $3
`

type GetCredentialParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	VaultID  pgtype.UUID `json:"vault_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetCredentialRow struct {
	ID            pgtype.UUID        `json:"id"`
	VaultID       pgtype.UUID        `json:"vault_id"`
	Name          string             `json:"name"`
	AuthType      string             `json:"auth_type"`
	McpServerUrl  string             `json:"mcp_server_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata []byte             `json:"oauth_metadata"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (GetCredentialRow, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.TenantID, arg.VaultID, arg.ID)
	var i GetCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthMetadata,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at, c.oauth_metadata
FROM vault_credentials c
JOIN vaults v ON v.id = c.vault_id
WHERE v.tenant_id = $1 AND v.id = $2
  AND c.status = ANY($3::text[])
  AND ($4::timestamptz IS NULL
    OR (NOT $5::boolean AND (c.created_at, c.id) < ($4::timestamptz, $6::uuid))
    OR ($5::boolean AND (c.created_at, c.id) > ($4::timestamptz, $6::uuid)))
ORDER BY
  CASE WHEN $5::boolean THEN c.created_at END ASC,
  CASE WHEN $5::boolean THEN c.id END ASC,
  CASE WHEN NOT $5::boolean THEN c.created_at END DESC,
  CASE WHEN NOT $5::boolean THEN c.id END DESC
LIMIT $7
`

type ListCredentialsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	VaultID      pgtype.UUID        `json:"vault_id"`
	Statuses     []string           `json:"statuses"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

type ListCredentialsRow struct {
	ID            pgtype.UUID        `json:"id"`
	VaultID       pgtype.UUID        `json:"vault_id"`
	Name          string             `json:"name"`
	AuthType      string             `json:"auth_type"`
	McpServerUrl  string             `json:"mcp_server_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata []byte             `json:"oauth_metadata"`
}

func (q *Queries) ListCredentials(ctx context.Context, arg ListCredentialsParams) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials,
		arg.TenantID,
		arg.VaultID,
		arg.Statuses,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.Name,
			&i.AuthType,
			&i.McpServerUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OauthMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaticCredential = `-- name: UpdateStaticCredential :one
UPDATE vault_credentials c
SET token_ciphertext = $1, updated_at = statement_timestamp()
FROM vaults v
WHERE v.id = c.vault_id AND v.tenant_id = $2
  AND v.id = $3 AND c.id = $4
  AND c.auth_type = 'static_bearer' AND c.mcp_server_url = $5
RETURNING c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at, c.oauth_metadata
`

type UpdateStaticCredentialParams struct {
	TokenCiphertext []byte      `json:"token_ciphertext"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
	ID              pgtype.UUID `json:"id"`
	McpServerUrl    string      `json:"mcp_server_url"`
}

type UpdateStaticCredentialRow struct {
	ID            pgtype.UUID        `json:"id"`
	VaultID       pgtype.UUID        `json:"vault_id"`
	Name          string             `json:"name"`
	AuthType      string             `json:"auth_type"`
	McpServerUrl  string             `json:"mcp_server_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata []byte             `json:"oauth_metadata"`
}

func (q *Queries) UpdateStaticCredential(ctx context.Context, arg UpdateStaticCredentialParams) (UpdateStaticCredentialRow, error) {
	row := q.db.QueryRow(ctx, updateStaticCredential,
		arg.TokenCiphertext,
		arg.TenantID,
		arg.VaultID,
		arg.ID,
		arg.McpServerUrl,
	)
	var i UpdateStaticCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthMetadata,
	)
	return i, err
}
