export const app = {
  apiKeysDescription: "Issue and revoke the keys applications use to call the Agents API. The console password never works as an API key.",
  errors: {
    coreRequest: "The Agent Core request failed.", agentChanged: "Agent data changed while the collection was loading. Refresh again to reconcile all loaded pages.", sessionChanged: "Session data changed while the collection was loading. Refresh again to reconcile all loaded pages.", runtimeBudget: "Runtime snapshot exceeded the 15 second Web refresh budget.", runtimeChanged: "Session data changed while Runtime observations were loading. The previous complete snapshot was retained.", filteredChanged: "Filtered Session data changed while the collection was loading. Refresh again to reconcile all loaded pages.", outsideFilter: "Agent Core returned a Session outside the requested Agent filter.", streamRejected: "Live event stream was rejected by Agent Core{{status}}. Check the Core connection settings.", connectionChanged: "The Core connection changed before the Vault operation started.", connectionChangedConfirm: "The Core connection changed before the Vault operation was confirmed.", credentialMismatch: "Agent Core returned mismatched Credential metadata.", latestCredentialMissing: "The latest Credential metadata is unavailable. Refresh before replacing its token.", credentialReplacementMismatch: "Agent Core returned mismatched Credential metadata after replacement.", managedDisabled: "Managed Environment configuration is not enabled for this Web build.", sessionOutcomeUnknown: "The Session creation outcome could not be confirmed.", sessionOutcomeChanged: "The Session creation outcome could not be confirmed after the Core connection changed.", previousSessionUpdate: "The previous Core returned a Session update after the connection changed. The current Core view was not modified.", previousSessionDelete: "The previous Core confirmed Session deletion after the connection changed. The current Core view was not modified.", waitForStream: "Wait for the live event stream to connect before sending.", setupAgentMissing: "Session setup could not open because the selected saved Agent is not loaded.",
  },
  success: {
    agentCreated: "Agent created.", agentUpdated: "Agent updated.", agentDeleted: "Agent deleted.", vaultCreated: "Vault created.", credentialCreated: "Credential created. Token remains hidden.", credentialReplaced: "Credential token replaced. Running work may still hold the previous token.", credentialDeleted: "Credential deleted. Provider-side token was not revoked.", credentialDeleteReconciled: "Credential deletion reconciled from Core.", vaultDeleted: "Vault and its Credentials deleted. Provider-side tokens were not revoked.", vaultDeleteReconciled: "Vault deletion reconciled from Core.", templateSaved: "Environment Template saved. No Runtime was allocated.", idleSessionOpened: "Idle Session created. Opening live events…", sessionOpened: "Session opened. Connecting live events…", managedSessionConnected: "Managed hosted Session created. Live creation events are connected.", idleSessionConnected: "Idle Session created. Live creation events are connected.", sessionInputConnected: "Session created with initial input. Live creation events are connected.", metadataUpdated: "Session metadata updated.", sessionDeleted: "Session deleted from Agent Core.", sessionAbsentAfterCancel: "Session is absent from Agent Core after cancellation.", cancellationRequested: "Cancellation requested.", functionSubmitted: "Function result submitted.",
  },
} as const;
