export const app = {
  apiKeysDescription: "签发和撤销应用调用 Agents API 所用的密钥。控制台密码不能当作 API 密钥使用。",
  errors: {
    coreRequest: "Agent Core 请求失败。", agentChanged: "加载数据集时 Agent 数据已变更。请再次刷新以同步所有已加载页。", sessionChanged: "加载数据集时 Session 数据已变更。请再次刷新以同步所有已加载页。", runtimeBudget: "Runtime 快照超过了 Web 15 秒刷新时限。", runtimeChanged: "加载 Runtime 观测时 Session 数据已变更。已保留上一个完整快照。", filteredChanged: "加载数据集时筛选后的 Session 数据已变更。请再次刷新以同步所有已加载页。", outsideFilter: "Agent Core 返回了不属于当前 Agent 筛选条件的 Session。", streamRejected: "Agent Core 拒绝了实时事件流{{status}}。请检查 Core 连接设置。", connectionChanged: "Vault 操作开始前 Core 连接已变更。", connectionChangedConfirm: "Vault 操作确认前 Core 连接已变更。", credentialMismatch: "Agent Core 返回了不匹配的 Credential 元数据。", latestCredentialMissing: "最新 Credential 元数据不可用。替换 Token 前请先刷新。", credentialReplacementMismatch: "替换后 Agent Core 返回了不匹配的 Credential 元数据。", managedDisabled: "当前 Web 构建未启用托管环境配置。", sessionOutcomeUnknown: "无法确认 Session 创建结果。", sessionOutcomeChanged: "Core 连接变更后无法确认 Session 创建结果。", previousSessionUpdate: "Core 连接变更后，上一个 Core 返回了 Session 更新。当前 Core 视图未被修改。", previousSessionDelete: "Core 连接变更后，上一个 Core 确认了 Session 删除。当前 Core 视图未被修改。", waitForStream: "发送前请等待实时事件流连接。", setupAgentMissing: "选中的已保存 Agent 未加载，无法打开 Session 设置。",
  },
  success: {
    agentCreated: "Agent 已创建。", agentUpdated: "Agent 已更新。", agentDeleted: "Agent 已删除。", vaultCreated: "Vault 已创建。", credentialCreated: "Credential 已创建，Token 仍保持隐藏。", credentialReplaced: "Credential Token 已替换。正在运行的工作可能仍持有旧 Token。", credentialDeleted: "Credential 已删除，Provider 端 Token 未被撤销。", credentialDeleteReconciled: "已根据 Core 状态同步 Credential 删除结果。", vaultDeleted: "Vault 及其 Credential 已删除，Provider 端 Token 未被撤销。", vaultDeleteReconciled: "已根据 Core 状态同步 Vault 删除结果。", templateSaved: "环境模板已保存，未分配 Runtime。", idleSessionOpened: "空闲 Session 已创建，正在打开实时事件…", sessionOpened: "Session 已打开，正在连接实时事件…", managedSessionConnected: "托管 Session 已创建，创建事件流已连接。", idleSessionConnected: "空闲 Session 已创建，创建事件流已连接。", sessionInputConnected: "带初始输入的 Session 已创建，创建事件流已连接。", metadataUpdated: "Session 元数据已更新。", sessionDeleted: "Session 已从 Agent Core 删除。", sessionAbsentAfterCancel: "取消后 Session 已不存在于 Agent Core。", cancellationRequested: "已请求取消。", functionSubmitted: "函数结果已提交。",
  },
} as const;
