// Package sessionview runs a process, and others spawned beside it, inside a per-Session view on the agent host.
//
// A view is private mount, PID, network and cgroup namespaces whose root is the Session's world: a FUSE file system that the daemon serves over a /dev/fuse connection. The launcher adds the local pieces on top of the world: private directories under /.oac, trusted overlays, the command shim, fresh /proc and read-only /sys filesystems, a read-only cgroup2 mount rooted at the view and a minimal /dev. The world presents a mountpoint for each piece and reports where, following the sandbox's symlinks, and the launcher mounts at those paths without following any symlink itself. A [Spec] without a world gets an empty root instead: a read-only, noexec tmpfs that holds only the mountpoints, each at its own path. The process starts with no capabilities, no_new_privs, a seccomp filter and only stdin, stdout and stderr open. Its network namespace has only loopback up.
//
// With a world, the initial process starts only in a directory on that world: the launcher resolves [Process].Dir without symlinks or crossing a mount, then enters the pinned directory before starting the process. Private directories and overlays cannot become its workspace through aliases. An empty-root view and later [View.Spawn] commands retain ordinary working-directory resolution.
//
// The exec guard is narrow. Mount flags alone decide which files can be executed: the world and every writable mount are nosuid and noexec, so executing a file from the file system works only from read-only mounts declared executable, such as the Harness directory, the shim and exec-flagged overlays. The seccomp filter denies creating a user namespace and every setns, so the process cannot create or enter another user namespace. Executing from a memfd and code that an allowed interpreter runs are outside this guard.
//
// The daemon calls [Init] first thing in main. [Start] re-executes the daemon binary as the launcher, which becomes PID 1 of the view: it builds the view, starts the process, delivers signals to every process in the view, reaps orphans and exits with the process status. Once the process has exited, Signal reports [ErrExited] and delivers nothing. When the process exits while others remain, the launcher sends them TERM unless one already went to the view, and waits for them up to [Process].Grace from the first TERM. Its exit kills what remains and tears the view down.
//
// While the process runs, [View.Spawn] has the launcher start another process in the view, passing the command on a pipe and the stdio pipes that Spawn makes over the control socket. A view starts one spawn at a time, and a spawn waiting for its turn holds no descriptors. The launcher starts each from the thread that carries the restrictions, as it started the process, so it runs as the same user, in the view's namespaces and cgroup, under the same restrictions and in a session of its own. That thread does nothing else once the process runs. It enters each command's directory itself, with the process's file system identity, before it forks, so the child inherits the directory and a directory stuck on the world holds up no other thread: reaping, signals, the drain and the exit go on. A command's path does not belong in the world: a child that waits on the world before its exec holds the fork, and with it the launcher, until the world answers. The launcher reaps as SIGCHLD reports exits. While a spawn forks, it reaps only the processes it has registered, so the pid of a child that exits before its registration stays its own until the registration ties it to its spawn. A spawned process counts like any other process in the view: a signal to the view reaches it, and when the process exits it is among those the launcher sends TERM and waits for. Each spawn has an ID, which [Spawned] uses rather than the pid: [Spawned].Signal reaches the process group until the launcher reaps the process, and reports [ErrExited] from then on. What the process leaves runs on as other processes in the view do, and the view's end ends it.
//
// A view that declares a [Shim] also runs the Session's process relay, the shim binary in relay mode (package processshim). The launcher starts it before the process, under the same restrictions and as the same user, with a listening socket at processshim.SocketPath on a read-only mount and its end of a socket pair whose other end is [View.Relay]. The relay is the only process that receives the descriptors a shim hands over; the broker outside the view holds only its end of the pair. The launcher's drain ignores the relay, which ends with the view.
//
// Each view runs in a cgroup v2 of its own, which Start creates in [Spec].CgroupParent. The launcher is cloned into it with CLONE_INTO_CGROUP, so no process of the view ever runs outside it. The cgroup hierarchy is the only record of what the views own: [Recover] ends every cgroup an earlier owner of the parent left, with all its processes.
//
// Teardown never waits unconditionally. Once the launcher has exited, the view shuts its end of the relay connection down, ends every process in its cgroup with cgroup.kill and stops the world server, which ends the requests still pending on the view's FUSE connection so that a process blocked on the world can exit. Only when the world server and the launcher have ended and the cgroup is empty, all within 30 seconds, does it remove the cgroup. Otherwise Wait and Close report [ErrCleanup] and the cgroup stays for Recover; nothing touches it after the teardown. When Start's context ends during the build, Start kills the launcher, stops waiting for it and tears the view down the same way, so a launcher blocked on the world cannot hold Start past this bound.
//
// Views work only on Linux; elsewhere the package offers only [Init] and its types.
package sessionview
