//go:build linux

// Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.
package cli

import (
	"github.com/MiniMax-AI/OpenAgentCore/apps/daemon/internal/agent"
	"github.com/MiniMax-AI/OpenAgentCore/apps/daemon/internal/agent/claudesdk"
	"github.com/MiniMax-AI/OpenAgentCore/apps/daemon/internal/agent/codex"
	"github.com/MiniMax-AI/OpenAgentCore/apps/daemon/internal/agent/mcode"
)

var harnessDeclarations = []agent.Declaration{claudesdk.Declaration, codex.Declaration, mcode.Declaration}
var harnessInstallations = []agent.Installation{claudesdk.Installation(), codex.Installation(), mcode.Installation()}
