// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_copies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCopyCredentialIDs = `-- name: AdminCopyCredentialIDs :many
SELECT c.id FROM vault_credentials c JOIN vaults v ON v.id=c.vault_id
WHERE v.tenant_id=$1 AND v.id=$2 ORDER BY c.id
`

type AdminCopyCredentialIDsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) AdminCopyCredentialIDs(ctx context.Context, arg AdminCopyCredentialIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, adminCopyCredentialIDs, arg.TenantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCopySkillVersionNumbers = `-- name: AdminCopySkillVersionNumbers :many
SELECT version FROM skill_versions WHERE tenant_id=$1 AND skill_id=$2 ORDER BY version
`

type AdminCopySkillVersionNumbersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SkillID  pgtype.UUID `json:"skill_id"`
}

func (q *Queries) AdminCopySkillVersionNumbers(ctx context.Context, arg AdminCopySkillVersionNumbersParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, adminCopySkillVersionNumbers, arg.TenantID, arg.SkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var version int64
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAdminCopyCredential = `-- name: CreateAdminCopyCredential :one
INSERT INTO vault_credentials(id,vault_id,name,auth_type,mcp_server_url,token_ciphertext,oauth_metadata,status)
SELECT $1,v.id,$2,$3,$4,$5,$6,$7
FROM vaults v WHERE v.tenant_id=$8 AND v.id=$9
RETURNING id
`

type CreateAdminCopyCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	AuthType        string      `json:"auth_type"`
	McpServerUrl    string      `json:"mcp_server_url"`
	TokenCiphertext []byte      `json:"token_ciphertext"`
	OauthMetadata   []byte      `json:"oauth_metadata"`
	Status          string      `json:"status"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
}

func (q *Queries) CreateAdminCopyCredential(ctx context.Context, arg CreateAdminCopyCredentialParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAdminCopyCredential,
		arg.ID,
		arg.Name,
		arg.AuthType,
		arg.McpServerUrl,
		arg.TokenCiphertext,
		arg.OauthMetadata,
		arg.Status,
		arg.TenantID,
		arg.VaultID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createAdminCopySkill = `-- name: CreateAdminCopySkill :one
INSERT INTO skills(id,tenant_id,name,description,default_version,latest_version,next_version)
VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, tenant_id, name, description, created_at, default_version, latest_version, next_version
`

type CreateAdminCopySkillParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	DefaultVersion int64       `json:"default_version"`
	LatestVersion  int64       `json:"latest_version"`
	NextVersion    int64       `json:"next_version"`
}

func (q *Queries) CreateAdminCopySkill(ctx context.Context, arg CreateAdminCopySkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createAdminCopySkill,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.DefaultVersion,
		arg.LatestVersion,
		arg.NextVersion,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DefaultVersion,
		&i.LatestVersion,
		&i.NextVersion,
	)
	return i, err
}

const createAdminCopyVault = `-- name: CreateAdminCopyVault :one
INSERT INTO vaults(id,tenant_id,name,metadata,status) VALUES($1,$2,$3,$4,$5) RETURNING id
`

type CreateAdminCopyVaultParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     pgtype.Text `json:"name"`
	Metadata []byte      `json:"metadata"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateAdminCopyVault(ctx context.Context, arg CreateAdminCopyVaultParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAdminCopyVault,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Metadata,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createAdminResourceOwner = `-- name: CreateAdminResourceOwner :exec
INSERT INTO admin_resource_owners(tenant_id,resource_type,resource_id,parent_id,audit_id)
VALUES($1,$2,$3,$4,$5)
`

type CreateAdminResourceOwnerParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	ParentID     string      `json:"parent_id"`
	AuditID      pgtype.UUID `json:"audit_id"`
}

func (q *Queries) CreateAdminResourceOwner(ctx context.Context, arg CreateAdminResourceOwnerParams) error {
	_, err := q.db.Exec(ctx, createAdminResourceOwner,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.ParentID,
		arg.AuditID,
	)
	return err
}

const getAdminAssetCopy = `-- name: GetAdminAssetCopy :one
SELECT request_hash, result FROM admin_asset_copies
WHERE target_tenant_id = $1 AND idempotency_key = $2
`

type GetAdminAssetCopyParams struct {
	TargetTenantID pgtype.UUID `json:"target_tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type GetAdminAssetCopyRow struct {
	RequestHash []byte `json:"request_hash"`
	Result      []byte `json:"result"`
}

func (q *Queries) GetAdminAssetCopy(ctx context.Context, arg GetAdminAssetCopyParams) (GetAdminAssetCopyRow, error) {
	row := q.db.QueryRow(ctx, getAdminAssetCopy, arg.TargetTenantID, arg.IdempotencyKey)
	var i GetAdminAssetCopyRow
	err := row.Scan(&i.RequestHash, &i.Result)
	return i, err
}

const getAdminCopyCredential = `-- name: GetAdminCopyCredential :one
SELECT c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.token_ciphertext, c.created_at, c.updated_at, c.status, c.oauth_metadata FROM vault_credentials c JOIN vaults v ON v.id=c.vault_id
WHERE v.tenant_id=$1 AND c.id=$2 FOR UPDATE OF c
`

type GetAdminCopyCredentialParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAdminCopyCredential(ctx context.Context, arg GetAdminCopyCredentialParams) (VaultCredential, error) {
	row := q.db.QueryRow(ctx, getAdminCopyCredential, arg.TenantID, arg.ID)
	var i VaultCredential
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.TokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.OauthMetadata,
	)
	return i, err
}

const lockAdminAssetCopy = `-- name: LockAdminAssetCopy :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockAdminAssetCopy(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockAdminAssetCopy, lockKey)
	return err
}

const lockAdminCopyTargetProject = `-- name: LockAdminCopyTargetProject :one
SELECT id, archived_at FROM projects WHERE tenant_id=$1 FOR SHARE
`

type LockAdminCopyTargetProjectRow struct {
	ID         pgtype.UUID        `json:"id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) LockAdminCopyTargetProject(ctx context.Context, tenantID pgtype.UUID) (LockAdminCopyTargetProjectRow, error) {
	row := q.db.QueryRow(ctx, lockAdminCopyTargetProject, tenantID)
	var i LockAdminCopyTargetProjectRow
	err := row.Scan(&i.ID, &i.ArchivedAt)
	return i, err
}

const lockAdminCopyTemplate = `-- name: LockAdminCopyTemplate :one
SELECT id FROM environment_templates WHERE tenant_id=$1 AND id=$2 FOR UPDATE
`

type LockAdminCopyTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockAdminCopyTemplate(ctx context.Context, arg LockAdminCopyTemplateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAdminCopyTemplate, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockAdminCopyVault = `-- name: LockAdminCopyVault :one
SELECT id, tenant_id, name, metadata, created_at, status FROM vaults WHERE tenant_id=$1 AND id=$2 FOR UPDATE
`

type LockAdminCopyVaultParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockAdminCopyVault(ctx context.Context, arg LockAdminCopyVaultParams) (Vault, error) {
	row := q.db.QueryRow(ctx, lockAdminCopyVault, arg.TenantID, arg.ID)
	var i Vault
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const saveAdminAssetCopy = `-- name: SaveAdminAssetCopy :exec
INSERT INTO admin_asset_copies(target_tenant_id,idempotency_key,request_hash,result,audit_id)
VALUES($1,$2,$3,$4,$5)
ON CONFLICT (target_tenant_id,idempotency_key) DO UPDATE
SET request_hash=admin_asset_copies.request_hash
`

type SaveAdminAssetCopyParams struct {
	TargetTenantID pgtype.UUID `json:"target_tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	RequestHash    []byte      `json:"request_hash"`
	Result         []byte      `json:"result"`
	AuditID        pgtype.UUID `json:"audit_id"`
}

func (q *Queries) SaveAdminAssetCopy(ctx context.Context, arg SaveAdminAssetCopyParams) error {
	_, err := q.db.Exec(ctx, saveAdminAssetCopy,
		arg.TargetTenantID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Result,
		arg.AuditID,
	)
	return err
}
