// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_session_archive.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getManagedSessionArchive = `-- name: GetManagedSessionArchive :one
SELECT s.id AS session_id, e.id AS environment_id,
       (s.configuration->'environment'->>'type')::text AS environment_type,
       CASE
           WHEN a.state = 'released' THEN 'released'
           WHEN a.state = 'cleanup_pending' THEN 'cleanup_pending'
           WHEN e.status IN ('failed', 'expired') THEN
               CASE WHEN a.id IS NULL THEN 'released' ELSE 'cleanup_pending' END
           ELSE 'active'
       END::text AS state
FROM sessions s JOIN environments e ON e.session_id = s.id
LEFT JOIN runtime_allocations a ON a.environment_id = e.id
WHERE s.tenant_id = $1 AND s.id = $2 AND s.deleted_at IS NULL
`

type GetManagedSessionArchiveParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetManagedSessionArchiveRow struct {
	SessionID       pgtype.UUID `json:"session_id"`
	EnvironmentID   pgtype.UUID `json:"environment_id"`
	EnvironmentType string      `json:"environment_type"`
	State           string      `json:"state"`
}

func (q *Queries) GetManagedSessionArchive(ctx context.Context, arg GetManagedSessionArchiveParams) (GetManagedSessionArchiveRow, error) {
	row := q.db.QueryRow(ctx, getManagedSessionArchive, arg.TenantID, arg.ID)
	var i GetManagedSessionArchiveRow
	err := row.Scan(
		&i.SessionID,
		&i.EnvironmentID,
		&i.EnvironmentType,
		&i.State,
	)
	return i, err
}
