// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_summary.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminAssetCounts = `-- name: AdminAssetCounts :one
SELECT
 (SELECT count(*) FROM agents count_source WHERE count_source.tenant_id=$1)::bigint AS agents,
 (SELECT count(*) FROM skills count_source WHERE count_source.tenant_id=$1)::bigint AS skills,
 (SELECT count(*) FROM environment_templates count_source WHERE count_source.tenant_id=$1)::bigint AS environment_templates,
 (SELECT count(*) FROM source_files count_source WHERE count_source.tenant_id=$1)::bigint AS files,
 (SELECT count(*) FROM vaults count_source WHERE count_source.tenant_id=$1)::bigint AS vaults,
 (SELECT count(*) FROM vault_credentials c JOIN vaults v ON v.id=c.vault_id WHERE v.tenant_id=$1)::bigint AS credentials
`

type AdminAssetCountsRow struct {
	Agents               int64 `json:"agents"`
	Skills               int64 `json:"skills"`
	EnvironmentTemplates int64 `json:"environment_templates"`
	Files                int64 `json:"files"`
	Vaults               int64 `json:"vaults"`
	Credentials          int64 `json:"credentials"`
}

func (q *Queries) AdminAssetCounts(ctx context.Context, tenantID pgtype.UUID) (AdminAssetCountsRow, error) {
	row := q.db.QueryRow(ctx, adminAssetCounts, tenantID)
	var i AdminAssetCountsRow
	err := row.Scan(
		&i.Agents,
		&i.Skills,
		&i.EnvironmentTemplates,
		&i.Files,
		&i.Vaults,
		&i.Credentials,
	)
	return i, err
}

const adminRuntimeCursor = `-- name: AdminRuntimeCursor :one
SELECT created_at FROM sessions WHERE id=$1 AND tenant_id=ANY($2::uuid[]) AND deleted_at IS NULL
`

type AdminRuntimeCursorParams struct {
	ID        pgtype.UUID   `json:"id"`
	TenantIds []pgtype.UUID `json:"tenant_ids"`
}

func (q *Queries) AdminRuntimeCursor(ctx context.Context, arg AdminRuntimeCursorParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, adminRuntimeCursor, arg.ID, arg.TenantIds)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const adminRuntimeTargets = `-- name: AdminRuntimeTargets :many
SELECT id,tenant_id,created_at FROM sessions
WHERE tenant_id=ANY($1::uuid[]) AND deleted_at IS NULL
 AND ($2::timestamptz IS NULL
 OR ($3::boolean AND (created_at,id)>($2::timestamptz,$4::uuid))
 OR (NOT $3::boolean AND (created_at,id)<($2::timestamptz,$4::uuid)))
ORDER BY
 CASE WHEN $3::boolean THEN created_at END ASC,
 CASE WHEN $3::boolean THEN id END ASC,
 CASE WHEN NOT $3::boolean THEN created_at END DESC,
 CASE WHEN NOT $3::boolean THEN id END DESC
LIMIT $5
`

type AdminRuntimeTargetsParams struct {
	TenantIds []pgtype.UUID      `json:"tenant_ids"`
	AfterTime pgtype.Timestamptz `json:"after_time"`
	Ascending bool               `json:"ascending"`
	AfterID   pgtype.UUID        `json:"after_id"`
	PageLimit int32              `json:"page_limit"`
}

type AdminRuntimeTargetsRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AdminRuntimeTargets(ctx context.Context, arg AdminRuntimeTargetsParams) ([]AdminRuntimeTargetsRow, error) {
	rows, err := q.db.Query(ctx, adminRuntimeTargets,
		arg.TenantIds,
		arg.AfterTime,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminRuntimeTargetsRow{}
	for rows.Next() {
		var i AdminRuntimeTargetsRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSummarySessions = `-- name: AdminSummarySessions :many
SELECT s.id, s.tenant_id, s.engine, s.metadata, s.idempotency_key, s.request_hash, s.created_at, s.configuration, s.event_sequence, s.creation_request_hash, s.deleted_at, s.creator_kind, s.creator_id, a.key_id AS creation_key_id FROM sessions s
LEFT JOIN write_audit_owners o ON o.tenant_id=s.tenant_id AND o.resource_type='session' AND o.resource_id=s.id::text
LEFT JOIN write_audit_operations a ON a.tenant_id=o.tenant_id AND a.id=o.operation_id
WHERE s.tenant_id=$1 AND s.deleted_at IS NULL
 AND ($2::timestamptz IS NULL OR s.created_at >= $2::timestamptz)
 AND ($3::timestamptz IS NULL OR s.created_at < $3::timestamptz)
 AND s.id > $4::uuid
ORDER BY s.id LIMIT 100
`

type AdminSummarySessionsParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	AfterID       pgtype.UUID        `json:"after_id"`
}

type AdminSummarySessionsRow struct {
	Session       Session     `json:"session"`
	CreationKeyID pgtype.Text `json:"creation_key_id"`
}

func (q *Queries) AdminSummarySessions(ctx context.Context, arg AdminSummarySessionsParams) ([]AdminSummarySessionsRow, error) {
	rows, err := q.db.Query(ctx, adminSummarySessions,
		arg.TenantID,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSummarySessionsRow{}
	for rows.Next() {
		var i AdminSummarySessionsRow
		if err := rows.Scan(
			&i.Session.ID,
			&i.Session.TenantID,
			&i.Session.Engine,
			&i.Session.Metadata,
			&i.Session.IdempotencyKey,
			&i.Session.RequestHash,
			&i.Session.CreatedAt,
			&i.Session.Configuration,
			&i.Session.EventSequence,
			&i.Session.CreationRequestHash,
			&i.Session.DeletedAt,
			&i.Session.CreatorKind,
			&i.Session.CreatorID,
			&i.CreationKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
