// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_setup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentSetup = `-- name: CreateEnvironmentSetup :exec
INSERT INTO environment_setups (session_id, contents) VALUES ($1, $2)
`

type CreateEnvironmentSetupParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Contents  []byte      `json:"contents"`
}

func (q *Queries) CreateEnvironmentSetup(ctx context.Context, arg CreateEnvironmentSetupParams) error {
	_, err := q.db.Exec(ctx, createEnvironmentSetup, arg.SessionID, arg.Contents)
	return err
}

const getEnvironmentSetup = `-- name: GetEnvironmentSetup :one
SELECT f.contents FROM sessions s LEFT JOIN environment_setups f ON s.id = f.session_id
WHERE s.tenant_id = $1 AND s.id = $2 AND s.deleted_at IS NULL
`

type GetEnvironmentSetupParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetEnvironmentSetup(ctx context.Context, arg GetEnvironmentSetupParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEnvironmentSetup, arg.TenantID, arg.ID)
	var contents []byte
	err := row.Scan(&contents)
	return contents, err
}

const setSessionSetupMetadata = `-- name: SetSessionSetupMetadata :one
UPDATE sessions SET configuration = jsonb_set(jsonb_set(jsonb_set(configuration, '{environment,packages}', $2::jsonb), '{environment,skills}', $3::jsonb), '{environment,initialization}', 'true'::jsonb)
WHERE id = $1 RETURNING id, tenant_id, engine, metadata, idempotency_key, request_hash, created_at, configuration, event_sequence, creation_request_hash, deleted_at, creator_kind, creator_id
`

type SetSessionSetupMetadataParams struct {
	ID       pgtype.UUID `json:"id"`
	Packages []byte      `json:"packages"`
	Skills   []byte      `json:"skills"`
}

func (q *Queries) SetSessionSetupMetadata(ctx context.Context, arg SetSessionSetupMetadataParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionSetupMetadata, arg.ID, arg.Packages, arg.Skills)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Engine,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.Configuration,
		&i.EventSequence,
		&i.CreationRequestHash,
		&i.DeletedAt,
		&i.CreatorKind,
		&i.CreatorID,
	)
	return i, err
}
