// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :exec
INSERT INTO environments (id, session_id) VALUES ($1, $2)
`

type CreateEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, createEnvironment, arg.ID, arg.SessionID)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT e.id, e.session_id, e.status, e.created_at, e.failure_reason, e.failed_at, s.tenant_id, (s.configuration->'environment')::jsonb AS configuration
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND e.id = $2 AND s.deleted_at IS NULL
`

type GetEnvironmentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetEnvironmentRow struct {
	Environment   Environment `json:"environment"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Configuration []byte      `json:"configuration"`
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.TenantID, arg.ID)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.Environment.ID,
		&i.Environment.SessionID,
		&i.Environment.Status,
		&i.Environment.CreatedAt,
		&i.Environment.FailureReason,
		&i.Environment.FailedAt,
		&i.TenantID,
		&i.Configuration,
	)
	return i, err
}

const getSessionEnvironment = `-- name: GetSessionEnvironment :one
SELECT e.id, e.session_id, e.status, e.created_at, e.failure_reason, e.failed_at, s.tenant_id, (s.configuration->'environment')::jsonb AS configuration
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND s.id = $2 AND s.deleted_at IS NULL
`

type GetSessionEnvironmentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetSessionEnvironmentRow struct {
	Environment   Environment `json:"environment"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Configuration []byte      `json:"configuration"`
}

func (q *Queries) GetSessionEnvironment(ctx context.Context, arg GetSessionEnvironmentParams) (GetSessionEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getSessionEnvironment, arg.TenantID, arg.ID)
	var i GetSessionEnvironmentRow
	err := row.Scan(
		&i.Environment.ID,
		&i.Environment.SessionID,
		&i.Environment.Status,
		&i.Environment.CreatedAt,
		&i.Environment.FailureReason,
		&i.Environment.FailedAt,
		&i.TenantID,
		&i.Configuration,
	)
	return i, err
}
