// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_file_writes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentFileWrite = `-- name: CreateEnvironmentFileWrite :one
INSERT INTO environment_file_writes(id, environment_id, device_id, request_sha256, audit_source)
VALUES ($1, $2, $3, $4, $5) RETURNING id, environment_id, device_id, request_sha256, state, created_at, settled_at, audit_source
`

type CreateEnvironmentFileWriteParams struct {
	ID            pgtype.UUID `json:"id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	DeviceID      pgtype.UUID `json:"device_id"`
	RequestSha256 string      `json:"request_sha256"`
	AuditSource   []byte      `json:"audit_source"`
}

func (q *Queries) CreateEnvironmentFileWrite(ctx context.Context, arg CreateEnvironmentFileWriteParams) (EnvironmentFileWrite, error) {
	row := q.db.QueryRow(ctx, createEnvironmentFileWrite,
		arg.ID,
		arg.EnvironmentID,
		arg.DeviceID,
		arg.RequestSha256,
		arg.AuditSource,
	)
	var i EnvironmentFileWrite
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.RequestSha256,
		&i.State,
		&i.CreatedAt,
		&i.SettledAt,
		&i.AuditSource,
	)
	return i, err
}

const environmentFileWriteBlocksSession = `-- name: EnvironmentFileWriteBlocksSession :one
SELECT EXISTS (
    SELECT 1 FROM environments e JOIN environment_file_writes w ON w.environment_id = e.id
    WHERE e.session_id = $1 AND w.state = 'pending'
)::boolean
`

func (q *Queries) EnvironmentFileWriteBlocksSession(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, environmentFileWriteBlocksSession, sessionID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const environmentFileWriteHasPendingInput = `-- name: EnvironmentFileWriteHasPendingInput :one
SELECT EXISTS (
    SELECT 1 FROM environment_input_reservations WHERE session_id = $1 AND state = 'pending'
)::boolean
`

func (q *Queries) EnvironmentFileWriteHasPendingInput(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, environmentFileWriteHasPendingInput, sessionID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getEnvironmentFileWrite = `-- name: GetEnvironmentFileWrite :one
SELECT w.id, w.environment_id, w.device_id, w.request_sha256, w.state, w.created_at, w.settled_at, w.audit_source, e.session_id
FROM environment_file_writes w
JOIN environments e ON e.id = w.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND e.id = $2 AND w.id = $3
`

type GetEnvironmentFileWriteParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
}

type GetEnvironmentFileWriteRow struct {
	EnvironmentFileWrite EnvironmentFileWrite `json:"environment_file_write"`
	SessionID            pgtype.UUID          `json:"session_id"`
}

func (q *Queries) GetEnvironmentFileWrite(ctx context.Context, arg GetEnvironmentFileWriteParams) (GetEnvironmentFileWriteRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentFileWrite, arg.TenantID, arg.EnvironmentID, arg.ID)
	var i GetEnvironmentFileWriteRow
	err := row.Scan(
		&i.EnvironmentFileWrite.ID,
		&i.EnvironmentFileWrite.EnvironmentID,
		&i.EnvironmentFileWrite.DeviceID,
		&i.EnvironmentFileWrite.RequestSha256,
		&i.EnvironmentFileWrite.State,
		&i.EnvironmentFileWrite.CreatedAt,
		&i.EnvironmentFileWrite.SettledAt,
		&i.EnvironmentFileWrite.AuditSource,
		&i.SessionID,
	)
	return i, err
}

const settleEnvironmentFileWrite = `-- name: SettleEnvironmentFileWrite :one
UPDATE environment_file_writes SET state = $3, settled_at = clock_timestamp()
WHERE environment_id = $1 AND id = $2 AND state = 'pending' RETURNING id, environment_id, device_id, request_sha256, state, created_at, settled_at, audit_source
`

type SettleEnvironmentFileWriteParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ID            pgtype.UUID `json:"id"`
	State         string      `json:"state"`
}

func (q *Queries) SettleEnvironmentFileWrite(ctx context.Context, arg SettleEnvironmentFileWriteParams) (EnvironmentFileWrite, error) {
	row := q.db.QueryRow(ctx, settleEnvironmentFileWrite, arg.EnvironmentID, arg.ID, arg.State)
	var i EnvironmentFileWrite
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.RequestSha256,
		&i.State,
		&i.CreatedAt,
		&i.SettledAt,
		&i.AuditSource,
	)
	return i, err
}
