// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_inputs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSessionEnvironmentInput = `-- name: CancelSessionEnvironmentInput :exec
UPDATE environment_input_reservations SET state = 'cancelled', settled_at = clock_timestamp()
WHERE session_id = $1 AND state = 'pending'
`

func (q *Queries) CancelSessionEnvironmentInput(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelSessionEnvironmentInput, sessionID)
	return err
}

const checkEnvironmentInputGate = `-- name: CheckEnvironmentInputGate :one
SELECT COALESCE((
    SELECT r.batch = $1::jsonb FROM environment_input_reservations r
    WHERE r.session_id = $2 AND r.idempotency_key = $3
), true)::boolean AS matches,
EXISTS (
    SELECT 1 FROM environment_input_reservations r
    WHERE r.session_id = $2
      AND (r.state = 'pending' OR r.idempotency_key = $3)
)::boolean AS blocked
`

type CheckEnvironmentInputGateParams struct {
	Batch          []byte      `json:"batch"`
	SessionID      pgtype.UUID `json:"session_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type CheckEnvironmentInputGateRow struct {
	Matches bool `json:"matches"`
	Blocked bool `json:"blocked"`
}

func (q *Queries) CheckEnvironmentInputGate(ctx context.Context, arg CheckEnvironmentInputGateParams) (CheckEnvironmentInputGateRow, error) {
	row := q.db.QueryRow(ctx, checkEnvironmentInputGate, arg.Batch, arg.SessionID, arg.IdempotencyKey)
	var i CheckEnvironmentInputGateRow
	err := row.Scan(&i.Matches, &i.Blocked)
	return i, err
}

const createEnvironmentInputReservation = `-- name: CreateEnvironmentInputReservation :one
WITH accepted AS (SELECT clock_timestamp() AS at)
INSERT INTO environment_input_reservations(id, session_id, idempotency_key, batch, is_initial, created_at, deadline)
SELECT $1, $2, $3, $4, $5, at, at + interval '5 minutes' FROM accepted
RETURNING id, session_id, idempotency_key, batch, state, created_at, deadline, settled_at, is_initial, failure_code
`

type CreateEnvironmentInputReservationParams struct {
	ID             pgtype.UUID `json:"id"`
	SessionID      pgtype.UUID `json:"session_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Batch          []byte      `json:"batch"`
	IsInitial      bool        `json:"is_initial"`
}

func (q *Queries) CreateEnvironmentInputReservation(ctx context.Context, arg CreateEnvironmentInputReservationParams) (EnvironmentInputReservation, error) {
	row := q.db.QueryRow(ctx, createEnvironmentInputReservation,
		arg.ID,
		arg.SessionID,
		arg.IdempotencyKey,
		arg.Batch,
		arg.IsInitial,
	)
	var i EnvironmentInputReservation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdempotencyKey,
		&i.Batch,
		&i.State,
		&i.CreatedAt,
		&i.Deadline,
		&i.SettledAt,
		&i.IsInitial,
		&i.FailureCode,
	)
	return i, err
}

const expireEnvironmentInputReservation = `-- name: ExpireEnvironmentInputReservation :exec
UPDATE environment_input_reservations SET state = 'expired', settled_at = clock_timestamp()
WHERE session_id = $1 AND id = $2 AND state = 'pending' AND deadline <= clock_timestamp()
`

type ExpireEnvironmentInputReservationParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) ExpireEnvironmentInputReservation(ctx context.Context, arg ExpireEnvironmentInputReservationParams) error {
	_, err := q.db.Exec(ctx, expireEnvironmentInputReservation, arg.SessionID, arg.ID)
	return err
}

const failEnvironmentInputWithoutModelProvider = `-- name: FailEnvironmentInputWithoutModelProvider :execrows
UPDATE environment_input_reservations
SET state = 'failed', settled_at = clock_timestamp(), failure_code = 'model_provider_required'
WHERE session_id = $1 AND id = $2 AND state = 'pending'
`

type FailEnvironmentInputWithoutModelProviderParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) FailEnvironmentInputWithoutModelProvider(ctx context.Context, arg FailEnvironmentInputWithoutModelProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, failEnvironmentInputWithoutModelProvider, arg.SessionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failSessionEnvironmentInput = `-- name: FailSessionEnvironmentInput :exec
UPDATE environment_input_reservations SET state = 'failed', settled_at = clock_timestamp()
WHERE session_id = $1 AND state = 'pending'
`

func (q *Queries) FailSessionEnvironmentInput(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failSessionEnvironmentInput, sessionID)
	return err
}

const findEnvironmentInputReservation = `-- name: FindEnvironmentInputReservation :one
SELECT r.id, r.session_id, r.idempotency_key, r.batch, r.state, r.created_at, r.deadline, r.settled_at, r.is_initial, r.failure_code, r.batch = $1::jsonb AS matches
FROM environment_input_reservations r
WHERE r.session_id = $2 AND r.idempotency_key = $3
`

type FindEnvironmentInputReservationParams struct {
	Batch          []byte      `json:"batch"`
	SessionID      pgtype.UUID `json:"session_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type FindEnvironmentInputReservationRow struct {
	EnvironmentInputReservation EnvironmentInputReservation `json:"environment_input_reservation"`
	Matches                     bool                        `json:"matches"`
}

func (q *Queries) FindEnvironmentInputReservation(ctx context.Context, arg FindEnvironmentInputReservationParams) (FindEnvironmentInputReservationRow, error) {
	row := q.db.QueryRow(ctx, findEnvironmentInputReservation, arg.Batch, arg.SessionID, arg.IdempotencyKey)
	var i FindEnvironmentInputReservationRow
	err := row.Scan(
		&i.EnvironmentInputReservation.ID,
		&i.EnvironmentInputReservation.SessionID,
		&i.EnvironmentInputReservation.IdempotencyKey,
		&i.EnvironmentInputReservation.Batch,
		&i.EnvironmentInputReservation.State,
		&i.EnvironmentInputReservation.CreatedAt,
		&i.EnvironmentInputReservation.Deadline,
		&i.EnvironmentInputReservation.SettledAt,
		&i.EnvironmentInputReservation.IsInitial,
		&i.EnvironmentInputReservation.FailureCode,
		&i.Matches,
	)
	return i, err
}

const getEnvironmentInputReservation = `-- name: GetEnvironmentInputReservation :one
SELECT id, session_id, idempotency_key, batch, state, created_at, deadline, settled_at, is_initial, failure_code FROM environment_input_reservations
WHERE session_id = $1 AND id = $2
`

type GetEnvironmentInputReservationParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetEnvironmentInputReservation(ctx context.Context, arg GetEnvironmentInputReservationParams) (EnvironmentInputReservation, error) {
	row := q.db.QueryRow(ctx, getEnvironmentInputReservation, arg.SessionID, arg.ID)
	var i EnvironmentInputReservation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdempotencyKey,
		&i.Batch,
		&i.State,
		&i.CreatedAt,
		&i.Deadline,
		&i.SettledAt,
		&i.IsInitial,
		&i.FailureCode,
	)
	return i, err
}

const settleEnvironmentInputReservation = `-- name: SettleEnvironmentInputReservation :one
UPDATE environment_input_reservations SET state = $1, settled_at = clock_timestamp()
WHERE session_id = $2 AND id = $3 AND state = 'pending'
RETURNING id, session_id, idempotency_key, batch, state, created_at, deadline, settled_at, is_initial, failure_code
`

type SettleEnvironmentInputReservationParams struct {
	State     string      `json:"state"`
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SettleEnvironmentInputReservation(ctx context.Context, arg SettleEnvironmentInputReservationParams) (EnvironmentInputReservation, error) {
	row := q.db.QueryRow(ctx, settleEnvironmentInputReservation, arg.State, arg.SessionID, arg.ID)
	var i EnvironmentInputReservation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdempotencyKey,
		&i.Batch,
		&i.State,
		&i.CreatedAt,
		&i.Deadline,
		&i.SettledAt,
		&i.IsInitial,
		&i.FailureCode,
	)
	return i, err
}
