// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_initialization.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEnvironmentInitialization = `-- name: ClaimEnvironmentInitialization :execrows
UPDATE environments SET initialization = 'running'
WHERE id = $1 AND initialization = 'pending' AND status NOT IN ('failed', 'expired')
`

func (q *Queries) ClaimEnvironmentInitialization(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimEnvironmentInitialization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeEnvironmentInitialization = `-- name: CompleteEnvironmentInitialization :execrows
UPDATE environments SET initialization = 'complete'
WHERE id = $1 AND initialization = 'running' AND status NOT IN ('failed', 'expired')
`

func (q *Queries) CompleteEnvironmentInitialization(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeEnvironmentInitialization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failEnvironmentInitialization = `-- name: FailEnvironmentInitialization :exec
UPDATE environments SET initialization = 'failed' WHERE id = $1 AND initialization <> 'complete'
`

func (q *Queries) FailEnvironmentInitialization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failEnvironmentInitialization, id)
	return err
}

const listEnvironmentInitializations = `-- name: ListEnvironmentInitializations :many
SELECT e.id, e.session_id, s.tenant_id, s.engine, e.initialization, b.device_id
FROM environments e JOIN sessions s ON s.id = e.session_id
LEFT JOIN session_devices b ON b.session_id = s.id
WHERE e.id > $1 AND s.deleted_at IS NULL AND e.status NOT IN ('failed', 'expired')
 AND e.initialization IN ('pending', 'running')
ORDER BY e.id LIMIT 32
`

type ListEnvironmentInitializationsRow struct {
	ID             pgtype.UUID `json:"id"`
	SessionID      pgtype.UUID `json:"session_id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	Engine         string      `json:"engine"`
	Initialization string      `json:"initialization"`
	DeviceID       pgtype.UUID `json:"device_id"`
}

func (q *Queries) ListEnvironmentInitializations(ctx context.Context, id pgtype.UUID) ([]ListEnvironmentInitializationsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentInitializations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentInitializationsRow{}
	for rows.Next() {
		var i ListEnvironmentInitializationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TenantID,
			&i.Engine,
			&i.Initialization,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
