// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentTemplate = `-- name: CreateEnvironmentTemplate :one
INSERT INTO environment_templates (id, tenant_id, name, network_access, files, file_contents, packages, env_contents, setup_contents, skills, skill_contents, network_allowed_domains, plugins, plugin_contents, capability_directories)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING id, tenant_id, name, network_access, network_allowed_domains, created_at, updated_at, files, packages, skills, plugins, capability_directories
`

type CreateEnvironmentTemplateParams struct {
	ID                    pgtype.UUID `json:"id"`
	TenantID              pgtype.UUID `json:"tenant_id"`
	Name                  pgtype.Text `json:"name"`
	NetworkAccess         string      `json:"network_access"`
	Files                 []byte      `json:"files"`
	FileContents          []byte      `json:"file_contents"`
	Packages              []byte      `json:"packages"`
	EnvContents           []byte      `json:"env_contents"`
	SetupContents         []byte      `json:"setup_contents"`
	Skills                []byte      `json:"skills"`
	SkillContents         []byte      `json:"skill_contents"`
	NetworkAllowedDomains []string    `json:"network_allowed_domains"`
	Plugins               []byte      `json:"plugins"`
	PluginContents        []byte      `json:"plugin_contents"`
	CapabilityDirectories []string    `json:"capability_directories"`
}

type CreateEnvironmentTemplateRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  pgtype.Text        `json:"name"`
	NetworkAccess         string             `json:"network_access"`
	NetworkAllowedDomains []string           `json:"network_allowed_domains"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Files                 []byte             `json:"files"`
	Packages              []byte             `json:"packages"`
	Skills                []byte             `json:"skills"`
	Plugins               []byte             `json:"plugins"`
	CapabilityDirectories []string           `json:"capability_directories"`
}

func (q *Queries) CreateEnvironmentTemplate(ctx context.Context, arg CreateEnvironmentTemplateParams) (CreateEnvironmentTemplateRow, error) {
	row := q.db.QueryRow(ctx, createEnvironmentTemplate,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.NetworkAccess,
		arg.Files,
		arg.FileContents,
		arg.Packages,
		arg.EnvContents,
		arg.SetupContents,
		arg.Skills,
		arg.SkillContents,
		arg.NetworkAllowedDomains,
		arg.Plugins,
		arg.PluginContents,
		arg.CapabilityDirectories,
	)
	var i CreateEnvironmentTemplateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.NetworkAllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Files,
		&i.Packages,
		&i.Skills,
		&i.Plugins,
		&i.CapabilityDirectories,
	)
	return i, err
}

const deleteEnvironmentTemplate = `-- name: DeleteEnvironmentTemplate :one
DELETE FROM environment_templates WHERE tenant_id = $1 AND id = $2 RETURNING id
`

type DeleteEnvironmentTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteEnvironmentTemplate(ctx context.Context, arg DeleteEnvironmentTemplateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEnvironmentTemplate, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEnvironmentTemplate = `-- name: GetEnvironmentTemplate :one
SELECT id, tenant_id, name, network_access, network_allowed_domains, created_at, updated_at, files, packages, skills, plugins, capability_directories FROM environment_templates WHERE tenant_id = $1 AND id = $2
`

type GetEnvironmentTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetEnvironmentTemplateRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  pgtype.Text        `json:"name"`
	NetworkAccess         string             `json:"network_access"`
	NetworkAllowedDomains []string           `json:"network_allowed_domains"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Files                 []byte             `json:"files"`
	Packages              []byte             `json:"packages"`
	Skills                []byte             `json:"skills"`
	Plugins               []byte             `json:"plugins"`
	CapabilityDirectories []string           `json:"capability_directories"`
}

func (q *Queries) GetEnvironmentTemplate(ctx context.Context, arg GetEnvironmentTemplateParams) (GetEnvironmentTemplateRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentTemplate, arg.TenantID, arg.ID)
	var i GetEnvironmentTemplateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.NetworkAllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Files,
		&i.Packages,
		&i.Skills,
		&i.Plugins,
		&i.CapabilityDirectories,
	)
	return i, err
}

const listEnvironmentTemplates = `-- name: ListEnvironmentTemplates :many
SELECT id, tenant_id, name, network_access, network_allowed_domains, created_at, updated_at, files, packages, skills, plugins, capability_directories FROM environment_templates
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL
       OR (NOT $3::boolean AND (created_at, id) < ($2::timestamptz, $4::uuid))
       OR ($3::boolean AND (created_at, id) > ($2::timestamptz, $4::uuid)))
ORDER BY
    CASE WHEN $3::boolean THEN created_at END ASC,
    CASE WHEN $3::boolean THEN id END ASC,
    CASE WHEN NOT $3::boolean THEN created_at END DESC,
    CASE WHEN NOT $3::boolean THEN id END DESC
LIMIT $5
`

type ListEnvironmentTemplatesParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

type ListEnvironmentTemplatesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  pgtype.Text        `json:"name"`
	NetworkAccess         string             `json:"network_access"`
	NetworkAllowedDomains []string           `json:"network_allowed_domains"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Files                 []byte             `json:"files"`
	Packages              []byte             `json:"packages"`
	Skills                []byte             `json:"skills"`
	Plugins               []byte             `json:"plugins"`
	CapabilityDirectories []string           `json:"capability_directories"`
}

func (q *Queries) ListEnvironmentTemplates(ctx context.Context, arg ListEnvironmentTemplatesParams) ([]ListEnvironmentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentTemplates,
		arg.TenantID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentTemplatesRow{}
	for rows.Next() {
		var i ListEnvironmentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NetworkAccess,
			&i.NetworkAllowedDomains,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Files,
			&i.Packages,
			&i.Skills,
			&i.Plugins,
			&i.CapabilityDirectories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEnvironmentTemplate = `-- name: ResolveEnvironmentTemplate :one
SELECT id, tenant_id, name, network_access, created_at, updated_at, files, file_contents, packages, env_contents, setup_contents, skills, skill_contents, network_allowed_domains, plugins, plugin_contents, capability_directories FROM environment_templates WHERE tenant_id = $1 AND id = $2
`

type ResolveEnvironmentTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ResolveEnvironmentTemplate(ctx context.Context, arg ResolveEnvironmentTemplateParams) (EnvironmentTemplate, error) {
	row := q.db.QueryRow(ctx, resolveEnvironmentTemplate, arg.TenantID, arg.ID)
	var i EnvironmentTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Files,
		&i.FileContents,
		&i.Packages,
		&i.EnvContents,
		&i.SetupContents,
		&i.Skills,
		&i.SkillContents,
		&i.NetworkAllowedDomains,
		&i.Plugins,
		&i.PluginContents,
		&i.CapabilityDirectories,
	)
	return i, err
}

const updateEnvironmentTemplate = `-- name: UpdateEnvironmentTemplate :one
UPDATE environment_templates SET
    name = CASE WHEN $1::boolean THEN $2::text ELSE name END,
    network_access = CASE WHEN $3::boolean THEN $4::text ELSE network_access END,
    network_allowed_domains = CASE WHEN $3::boolean THEN $5::text[] ELSE network_allowed_domains END,
    files = CASE WHEN $6::boolean THEN $7::jsonb ELSE files END,
    file_contents = CASE WHEN $6::boolean THEN $8::bytea ELSE file_contents END,
    packages = CASE WHEN $9::boolean THEN $10::jsonb ELSE packages END,
    env_contents = CASE WHEN $11::boolean THEN $12::bytea ELSE env_contents END,
    setup_contents = CASE WHEN $13::boolean THEN $14::bytea ELSE setup_contents END,
    skills = CASE WHEN $15::boolean THEN $16::jsonb ELSE skills END,
    skill_contents = CASE WHEN $15::boolean THEN $17::bytea ELSE skill_contents END,
    plugins = CASE WHEN $18::boolean THEN $19::jsonb ELSE plugins END,
    plugin_contents = CASE WHEN $18::boolean THEN $20::bytea ELSE plugin_contents END,
    capability_directories = CASE WHEN $21::boolean THEN $22::text[] ELSE capability_directories END,
    updated_at = clock_timestamp()
WHERE tenant_id = $23 AND id = $24
RETURNING id, tenant_id, name, network_access, network_allowed_domains, created_at, updated_at, files, packages, skills, plugins, capability_directories
`

type UpdateEnvironmentTemplateParams struct {
	SetName               bool        `json:"set_name"`
	Name                  pgtype.Text `json:"name"`
	SetNetwork            bool        `json:"set_network"`
	NetworkAccess         string      `json:"network_access"`
	NetworkAllowedDomains []string    `json:"network_allowed_domains"`
	SetFiles              bool        `json:"set_files"`
	Files                 []byte      `json:"files"`
	FileContents          []byte      `json:"file_contents"`
	SetPackages           bool        `json:"set_packages"`
	Packages              []byte      `json:"packages"`
	SetEnv                bool        `json:"set_env"`
	EnvContents           []byte      `json:"env_contents"`
	SetSetup              bool        `json:"set_setup"`
	SetupContents         []byte      `json:"setup_contents"`
	SetSkills             bool        `json:"set_skills"`
	Skills                []byte      `json:"skills"`
	SkillContents         []byte      `json:"skill_contents"`
	SetPlugins            bool        `json:"set_plugins"`
	Plugins               []byte      `json:"plugins"`
	PluginContents        []byte      `json:"plugin_contents"`
	SetDirectories        bool        `json:"set_directories"`
	CapabilityDirectories []string    `json:"capability_directories"`
	TenantID              pgtype.UUID `json:"tenant_id"`
	ID                    pgtype.UUID `json:"id"`
}

type UpdateEnvironmentTemplateRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  pgtype.Text        `json:"name"`
	NetworkAccess         string             `json:"network_access"`
	NetworkAllowedDomains []string           `json:"network_allowed_domains"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Files                 []byte             `json:"files"`
	Packages              []byte             `json:"packages"`
	Skills                []byte             `json:"skills"`
	Plugins               []byte             `json:"plugins"`
	CapabilityDirectories []string           `json:"capability_directories"`
}

func (q *Queries) UpdateEnvironmentTemplate(ctx context.Context, arg UpdateEnvironmentTemplateParams) (UpdateEnvironmentTemplateRow, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentTemplate,
		arg.SetName,
		arg.Name,
		arg.SetNetwork,
		arg.NetworkAccess,
		arg.NetworkAllowedDomains,
		arg.SetFiles,
		arg.Files,
		arg.FileContents,
		arg.SetPackages,
		arg.Packages,
		arg.SetEnv,
		arg.EnvContents,
		arg.SetSetup,
		arg.SetupContents,
		arg.SetSkills,
		arg.Skills,
		arg.SkillContents,
		arg.SetPlugins,
		arg.Plugins,
		arg.PluginContents,
		arg.SetDirectories,
		arg.CapabilityDirectories,
		arg.TenantID,
		arg.ID,
	)
	var i UpdateEnvironmentTemplateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NetworkAccess,
		&i.NetworkAllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Files,
		&i.Packages,
		&i.Skills,
		&i.Plugins,
		&i.CapabilityDirectories,
	)
	return i, err
}
