// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: initial_environment_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRuntimeInitialization = `-- name: ClaimRuntimeInitialization :one
UPDATE runtime_allocations SET initialization = 'running'
WHERE id = $1 AND initialization = 'pending' AND state = 'running' AND create_settled
AND (node_id IS NOT NULL OR (SELECT mode FROM runtime_deployment) = 'direct' OR kept_at > clock_timestamp() - interval '1 hour')
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error
`

func (q *Queries) ClaimRuntimeInitialization(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, claimRuntimeInitialization, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
	)
	return i, err
}

const completeRuntimeInitialization = `-- name: CompleteRuntimeInitialization :one
UPDATE runtime_allocations SET initialization = 'complete'
WHERE id = $1 AND initialization = 'running' AND state = 'running' AND create_settled
AND (node_id IS NOT NULL OR (SELECT mode FROM runtime_deployment) = 'direct' OR kept_at > clock_timestamp() - interval '1 hour')
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until, node_id, observation_error
`

func (q *Queries) CompleteRuntimeInitialization(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, completeRuntimeInitialization, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
		&i.NodeID,
		&i.ObservationError,
	)
	return i, err
}

const createInitialEnvironmentFile = `-- name: CreateInitialEnvironmentFile :exec
INSERT INTO initial_environment_files (id, session_id, position, path, size_bytes, contents)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInitialEnvironmentFileParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	Position  int32       `json:"position"`
	Path      string      `json:"path"`
	SizeBytes int64       `json:"size_bytes"`
	Contents  []byte      `json:"contents"`
}

func (q *Queries) CreateInitialEnvironmentFile(ctx context.Context, arg CreateInitialEnvironmentFileParams) error {
	_, err := q.db.Exec(ctx, createInitialEnvironmentFile,
		arg.ID,
		arg.SessionID,
		arg.Position,
		arg.Path,
		arg.SizeBytes,
		arg.Contents,
	)
	return err
}

const getInitialEnvironmentFile = `-- name: GetInitialEnvironmentFile :one
SELECT f.id, f.session_id, f.position, f.path, f.size_bytes, f.contents FROM initial_environment_files f JOIN sessions s ON s.id = f.session_id
WHERE s.tenant_id = $1 AND f.session_id = $2 AND f.position = $3 AND s.deleted_at IS NULL
`

type GetInitialEnvironmentFileParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Position  int32       `json:"position"`
}

func (q *Queries) GetInitialEnvironmentFile(ctx context.Context, arg GetInitialEnvironmentFileParams) (InitialEnvironmentFile, error) {
	row := q.db.QueryRow(ctx, getInitialEnvironmentFile, arg.TenantID, arg.SessionID, arg.Position)
	var i InitialEnvironmentFile
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Position,
		&i.Path,
		&i.SizeBytes,
		&i.Contents,
	)
	return i, err
}

const getSessionInitializationReady = `-- name: GetSessionInitializationReady :one
SELECT NOT EXISTS (
 SELECT 1 FROM runtime_allocations a JOIN environments e ON e.id = a.environment_id
 WHERE e.session_id = s.id AND a.initialization <> 'complete'
) AND ((NOT EXISTS (SELECT 1 FROM initial_environment_files f WHERE f.session_id = s.id)
 AND NOT EXISTS (SELECT 1 FROM environment_setups f WHERE f.session_id = s.id))
 OR EXISTS (SELECT 1 FROM runtime_allocations a JOIN environments e ON e.id = a.environment_id
 WHERE e.session_id = s.id AND a.initialization = 'complete')) AS ready
FROM sessions s WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSessionInitializationReadyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSessionInitializationReady(ctx context.Context, arg GetSessionInitializationReadyParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, getSessionInitializationReady, arg.TenantID, arg.ID)
	var ready pgtype.Bool
	err := row.Scan(&ready)
	return ready, err
}

const lockInitialSourceFile = `-- name: LockInitialSourceFile :one
SELECT id, tenant_id, filename, purpose, body_oid, size_bytes, sha256, created_at FROM source_files WHERE tenant_id = $1 AND id = $2 FOR SHARE
`

type LockInitialSourceFileParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockInitialSourceFile(ctx context.Context, arg LockInitialSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRow(ctx, lockInitialSourceFile, arg.TenantID, arg.ID)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.Purpose,
		&i.BodyOid,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const setSessionInitialFileMetadata = `-- name: SetSessionInitialFileMetadata :one
UPDATE sessions SET configuration = jsonb_set(configuration, '{environment,files}', $2::jsonb)
WHERE id = $1 RETURNING id, tenant_id, engine, metadata, idempotency_key, request_hash, created_at, configuration, event_sequence, creation_request_hash, deleted_at, creator_kind, creator_id
`

type SetSessionInitialFileMetadataParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 []byte      `json:"column_2"`
}

func (q *Queries) SetSessionInitialFileMetadata(ctx context.Context, arg SetSessionInitialFileMetadataParams) (Session, error) {
	row := q.db.QueryRow(ctx, setSessionInitialFileMetadata, arg.ID, arg.Column2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Engine,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.Configuration,
		&i.EventSequence,
		&i.CreationRequestHash,
		&i.DeletedAt,
		&i.CreatorKind,
		&i.CreatorID,
	)
	return i, err
}
