// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: local_environment_devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironmentDevice = `-- name: CreateEnvironmentDevice :one
INSERT INTO devices (id, tenant_id, name, credential_hash, environment_id)
SELECT $1, s.tenant_id, $2, $3, e.id
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $4 AND e.id = $5
AND s.deleted_at IS NULL AND s.configuration->'environment'->>'type' = 'openai_hosted'
ON CONFLICT (environment_id) DO NOTHING
RETURNING id
`

type CreateEnvironmentDeviceParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	CredentialHash pgtype.Text `json:"credential_hash"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
}

func (q *Queries) CreateEnvironmentDevice(ctx context.Context, arg CreateEnvironmentDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEnvironmentDevice,
		arg.ID,
		arg.Name,
		arg.CredentialHash,
		arg.TenantID,
		arg.EnvironmentID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
