// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcp_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findMCPCredentials = `-- name: FindMCPCredentials :many
SELECT c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at
FROM vault_credentials c
JOIN vaults v ON v.id = c.vault_id
WHERE v.tenant_id = $1
  AND v.id = ANY($2::uuid[])
  AND c.auth_type IN ('static_bearer', 'mcp_oauth')
  AND c.mcp_server_url = $3
  AND ($4::uuid IS NULL OR c.id = $4::uuid)
ORDER BY c.id
LIMIT 2
`

type FindMCPCredentialsParams struct {
	TenantID     pgtype.UUID   `json:"tenant_id"`
	VaultIds     []pgtype.UUID `json:"vault_ids"`
	McpServerUrl string        `json:"mcp_server_url"`
	CredentialID pgtype.UUID   `json:"credential_id"`
}

type FindMCPCredentialsRow struct {
	ID           pgtype.UUID        `json:"id"`
	VaultID      pgtype.UUID        `json:"vault_id"`
	Name         string             `json:"name"`
	AuthType     string             `json:"auth_type"`
	McpServerUrl string             `json:"mcp_server_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindMCPCredentials(ctx context.Context, arg FindMCPCredentialsParams) ([]FindMCPCredentialsRow, error) {
	rows, err := q.db.Query(ctx, findMCPCredentials,
		arg.TenantID,
		arg.VaultIds,
		arg.McpServerUrl,
		arg.CredentialID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMCPCredentialsRow{}
	for rows.Next() {
		var i FindMCPCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.VaultID,
			&i.Name,
			&i.AuthType,
			&i.McpServerUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachedVaultIDs = `-- name: GetAttachedVaultIDs :many
SELECT id FROM vaults
WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type GetAttachedVaultIDsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	VaultIds []pgtype.UUID `json:"vault_ids"`
}

func (q *Queries) GetAttachedVaultIDs(ctx context.Context, arg GetAttachedVaultIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAttachedVaultIDs, arg.TenantID, arg.VaultIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCPStaticCredentialCiphertext = `-- name: GetMCPStaticCredentialCiphertext :one
SELECT c.token_ciphertext
FROM vault_credentials c
JOIN vaults v ON v.id = c.vault_id
WHERE v.tenant_id = $1
  AND v.id = ANY($2::uuid[])
  AND v.id = $3
  AND c.id = $4
  AND c.auth_type = 'static_bearer'
  AND c.mcp_server_url = $5
`

type GetMCPStaticCredentialCiphertextParams struct {
	TenantID     pgtype.UUID   `json:"tenant_id"`
	VaultIds     []pgtype.UUID `json:"vault_ids"`
	VaultID      pgtype.UUID   `json:"vault_id"`
	CredentialID pgtype.UUID   `json:"credential_id"`
	McpServerUrl string        `json:"mcp_server_url"`
}

func (q *Queries) GetMCPStaticCredentialCiphertext(ctx context.Context, arg GetMCPStaticCredentialCiphertextParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMCPStaticCredentialCiphertext,
		arg.TenantID,
		arg.VaultIds,
		arg.VaultID,
		arg.CredentialID,
		arg.McpServerUrl,
	)
	var token_ciphertext []byte
	err := row.Scan(&token_ciphertext)
	return token_ciphertext, err
}
