// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Metadata      []byte             `json:"metadata"`
	Configuration []byte             `json:"configuration"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	CredentialHash pgtype.Text        `json:"credential_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	ExecutorKeyID  pgtype.UUID        `json:"executor_key_id"`
}

type Environment struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EnvironmentConnection struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Generation    pgtype.UUID `json:"generation"`
	Revision      int64       `json:"revision"`
}

type EnvironmentExecutorCredential struct {
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	TokenSha256   string             `json:"token_sha256"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	KeyID         pgtype.UUID        `json:"key_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SubjectKind   pgtype.Text        `json:"subject_kind"`
	SubjectID     pgtype.Text        `json:"subject_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type EnvironmentFileWrite struct {
	ID            pgtype.UUID        `json:"id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	RequestSha256 string             `json:"request_sha256"`
	State         string             `json:"state"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
}

type EnvironmentInputReservation struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Batch          []byte             `json:"batch"`
	State          string             `json:"state"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Deadline       pgtype.Timestamptz `json:"deadline"`
	SettledAt      pgtype.Timestamptz `json:"settled_at"`
	IsInitial      bool               `json:"is_initial"`
}

type EnvironmentSetup struct {
	SessionID pgtype.UUID `json:"session_id"`
	Contents  []byte      `json:"contents"`
}

type EnvironmentTemplate struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  pgtype.Text        `json:"name"`
	NetworkAccess         string             `json:"network_access"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Files                 []byte             `json:"files"`
	FileContents          []byte             `json:"file_contents"`
	Packages              []byte             `json:"packages"`
	EnvContents           []byte             `json:"env_contents"`
	SetupContents         []byte             `json:"setup_contents"`
	Skills                []byte             `json:"skills"`
	SkillContents         []byte             `json:"skill_contents"`
	NetworkAllowedDomains []string           `json:"network_allowed_domains"`
	Plugins               []byte             `json:"plugins"`
	PluginContents        []byte             `json:"plugin_contents"`
	CapabilityDirectories []string           `json:"capability_directories"`
}

type ExecutionProjectScope struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
}

type FunctionCall struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	CallID         string             `json:"call_id"`
	ExecutorCallID string             `json:"executor_call_id"`
	Name           string             `json:"name"`
	Arguments      []byte             `json:"arguments"`
	Result         []byte             `json:"result"`
	Applied        bool               `json:"applied"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InitialEnvironmentFile struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	Position  int32       `json:"position"`
	Path      string      `json:"path"`
	SizeBytes int64       `json:"size_bytes"`
	Contents  []byte      `json:"contents"`
}

type RuntimeAllocation struct {
	ID             pgtype.UUID        `json:"id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	DeviceID       pgtype.UUID        `json:"device_id"`
	ProviderKey    pgtype.UUID        `json:"provider_key"`
	State          string             `json:"state"`
	CreateSettled  bool               `json:"create_settled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	KeptAt         pgtype.Timestamptz `json:"kept_at"`
	ReleasedAt     pgtype.Timestamptz `json:"released_at"`
	Initialization string             `json:"initialization"`
}

type RuntimeDeviceAuthority struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	Name           string      `json:"name"`
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	CredentialHash string      `json:"credential_hash"`
}

type Session struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Engine              string             `json:"engine"`
	Metadata            []byte             `json:"metadata"`
	IdempotencyKey      string             `json:"idempotency_key"`
	RequestHash         string             `json:"request_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Configuration       []byte             `json:"configuration"`
	EventSequence       int64              `json:"event_sequence"`
	CreationRequestHash pgtype.Text        `json:"creation_request_hash"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatorKind         pgtype.Text        `json:"creator_kind"`
	CreatorID           pgtype.Text        `json:"creator_id"`
}

type SessionArtifact struct {
	ID            pgtype.UUID        `json:"id"`
	SessionID     pgtype.UUID        `json:"session_id"`
	TurnID        pgtype.UUID        `json:"turn_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	Path          string             `json:"path"`
	SizeBytes     int64              `json:"size_bytes"`
	BodyOid       pgtype.Uint32      `json:"body_oid"`
	Sha256        string             `json:"sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SessionDevice struct {
	SessionID       pgtype.UUID `json:"session_id"`
	DeviceID        pgtype.UUID `json:"device_id"`
	NativeSessionID string      `json:"native_session_id"`
}

type SessionEvent struct {
	SessionID    pgtype.UUID `json:"session_id"`
	Sequence     int64       `json:"sequence"`
	Payload      []byte      `json:"payload"`
	PayloadBytes pgtype.Int4 `json:"payload_bytes"`
}

type SessionItem struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	TurnID      pgtype.UUID        `json:"turn_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Position    int32              `json:"position"`
	Payload     []byte             `json:"payload"`
	OutputIndex pgtype.Int4        `json:"output_index"`
}

type SessionModelExecution struct {
	SessionID       pgtype.UUID `json:"session_id"`
	EncryptedConfig []byte      `json:"encrypted_config"`
}

type Skill struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DefaultVersion int64              `json:"default_version"`
	LatestVersion  int64              `json:"latest_version"`
	NextVersion    int64              `json:"next_version"`
}

type SkillVersion struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Contents    []byte             `json:"contents"`
}

type SourceFile struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Filename  string             `json:"filename"`
	Purpose   string             `json:"purpose"`
	BodyOid   pgtype.Uint32      `json:"body_oid"`
	SizeBytes int64              `json:"size_bytes"`
	Sha256    string             `json:"sha256"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SubagentIdentity struct {
	ID                pgtype.UUID `json:"id"`
	SessionID         pgtype.UUID `json:"session_id"`
	DeviceID          pgtype.UUID `json:"device_id"`
	Engine            string      `json:"engine"`
	NativeID          string      `json:"native_id"`
	ParentNativeID    string      `json:"parent_native_id"`
	NativeCreatedAt   int64       `json:"native_created_at"`
	FirstTurnID       pgtype.UUID `json:"first_turn_id"`
	FirstEventOrdinal int32       `json:"first_event_ordinal"`
}

type Turn struct {
	ID                     pgtype.UUID        `json:"id"`
	SessionID              pgtype.UUID        `json:"session_id"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CancelRequestedAt      pgtype.Timestamptz `json:"cancel_requested_at"`
	Outcome                []byte             `json:"outcome"`
	EventCount             int32              `json:"event_count"`
	EventBytes             int64              `json:"event_bytes"`
	TokenUsage             []byte             `json:"token_usage"`
	ArtifactCaptureStarted bool               `json:"artifact_capture_started"`
}

type TurnEvent struct {
	SessionID pgtype.UUID        `json:"session_id"`
	TurnID    pgtype.UUID        `json:"turn_id"`
	Ordinal   int32              `json:"ordinal"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TurnInput struct {
	Sequence       int64              `json:"sequence"`
	SessionID      pgtype.UUID        `json:"session_id"`
	TurnID         pgtype.UUID        `json:"turn_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Kind           string             `json:"kind"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	BatchPosition  int32              `json:"batch_position"`
}

type Vault struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      pgtype.Text        `json:"name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    string             `json:"status"`
}

type VaultCredential struct {
	ID              pgtype.UUID        `json:"id"`
	VaultID         pgtype.UUID        `json:"vault_id"`
	Name            string             `json:"name"`
	AuthType        string             `json:"auth_type"`
	McpServerUrl    string             `json:"mcp_server_url"`
	TokenCiphertext []byte             `json:"token_ciphertext"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Status          string             `json:"status"`
}
