// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthCredential = `-- name: CreateOAuthCredential :one
INSERT INTO vault_credentials (id, vault_id, name, auth_type, mcp_server_url, token_ciphertext, oauth_metadata)
SELECT $1, v.id, $2, 'mcp_oauth', $3, $4, $5
FROM vaults v
WHERE v.tenant_id = $6 AND v.id = $7
RETURNING id, vault_id, name, auth_type, mcp_server_url, created_at, updated_at, oauth_metadata
`

type CreateOAuthCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	McpServerUrl    string      `json:"mcp_server_url"`
	TokenCiphertext []byte      `json:"token_ciphertext"`
	OauthMetadata   []byte      `json:"oauth_metadata"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
}

type CreateOAuthCredentialRow struct {
	ID            pgtype.UUID        `json:"id"`
	VaultID       pgtype.UUID        `json:"vault_id"`
	Name          string             `json:"name"`
	AuthType      string             `json:"auth_type"`
	McpServerUrl  string             `json:"mcp_server_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata []byte             `json:"oauth_metadata"`
}

func (q *Queries) CreateOAuthCredential(ctx context.Context, arg CreateOAuthCredentialParams) (CreateOAuthCredentialRow, error) {
	row := q.db.QueryRow(ctx, createOAuthCredential,
		arg.ID,
		arg.Name,
		arg.McpServerUrl,
		arg.TokenCiphertext,
		arg.OauthMetadata,
		arg.TenantID,
		arg.VaultID,
	)
	var i CreateOAuthCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthMetadata,
	)
	return i, err
}

const getOAuthCredentialForUpdate = `-- name: GetOAuthCredentialForUpdate :one
SELECT c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at,
    c.oauth_metadata, c.token_ciphertext
FROM vault_credentials c
JOIN vaults v ON v.id = c.vault_id
WHERE v.tenant_id = $1 AND v.id = $2
    AND c.id = $3 AND c.auth_type = 'mcp_oauth'
FOR UPDATE OF c
`

type GetOAuthCredentialForUpdateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	VaultID  pgtype.UUID `json:"vault_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetOAuthCredentialForUpdateRow struct {
	ID              pgtype.UUID        `json:"id"`
	VaultID         pgtype.UUID        `json:"vault_id"`
	Name            string             `json:"name"`
	AuthType        string             `json:"auth_type"`
	McpServerUrl    string             `json:"mcp_server_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata   []byte             `json:"oauth_metadata"`
	TokenCiphertext []byte             `json:"token_ciphertext"`
}

func (q *Queries) GetOAuthCredentialForUpdate(ctx context.Context, arg GetOAuthCredentialForUpdateParams) (GetOAuthCredentialForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOAuthCredentialForUpdate, arg.TenantID, arg.VaultID, arg.ID)
	var i GetOAuthCredentialForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthMetadata,
		&i.TokenCiphertext,
	)
	return i, err
}

const updateOAuthCredential = `-- name: UpdateOAuthCredential :one
UPDATE vault_credentials c
SET token_ciphertext = $1, oauth_metadata = $2,
    updated_at = statement_timestamp()
FROM vaults v
WHERE v.id = c.vault_id AND v.tenant_id = $3
    AND v.id = $4 AND c.id = $5
    AND c.auth_type = 'mcp_oauth' AND c.mcp_server_url = $6
RETURNING c.id, c.vault_id, c.name, c.auth_type, c.mcp_server_url, c.created_at, c.updated_at, c.oauth_metadata
`

type UpdateOAuthCredentialParams struct {
	TokenCiphertext []byte      `json:"token_ciphertext"`
	OauthMetadata   []byte      `json:"oauth_metadata"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	VaultID         pgtype.UUID `json:"vault_id"`
	ID              pgtype.UUID `json:"id"`
	McpServerUrl    string      `json:"mcp_server_url"`
}

type UpdateOAuthCredentialRow struct {
	ID            pgtype.UUID        `json:"id"`
	VaultID       pgtype.UUID        `json:"vault_id"`
	Name          string             `json:"name"`
	AuthType      string             `json:"auth_type"`
	McpServerUrl  string             `json:"mcp_server_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OauthMetadata []byte             `json:"oauth_metadata"`
}

func (q *Queries) UpdateOAuthCredential(ctx context.Context, arg UpdateOAuthCredentialParams) (UpdateOAuthCredentialRow, error) {
	row := q.db.QueryRow(ctx, updateOAuthCredential,
		arg.TokenCiphertext,
		arg.OauthMetadata,
		arg.TenantID,
		arg.VaultID,
		arg.ID,
		arg.McpServerUrl,
	)
	var i UpdateOAuthCredentialRow
	err := row.Scan(
		&i.ID,
		&i.VaultID,
		&i.Name,
		&i.AuthType,
		&i.McpServerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthMetadata,
	)
	return i, err
}
