// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectAPIKey = `-- name: CreateProjectAPIKey :one
INSERT INTO project_api_keys
    (id, name, prefix, token_sha256, binding_digest, tenant_id, organization_id, project_id, subject_kind, subject_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO NOTHING
RETURNING id, name, prefix, created_at, revoked_at
`

type CreateProjectAPIKeyParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Prefix         string      `json:"prefix"`
	TokenSha256    string      `json:"token_sha256"`
	BindingDigest  string      `json:"binding_digest"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
	SubjectKind    string      `json:"subject_kind"`
	SubjectID      string      `json:"subject_id"`
}

type CreateProjectAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateProjectAPIKey(ctx context.Context, arg CreateProjectAPIKeyParams) (CreateProjectAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createProjectAPIKey,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.TokenSha256,
		arg.BindingDigest,
		arg.TenantID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.SubjectKind,
		arg.SubjectID,
	)
	var i CreateProjectAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listProjectAPIKeys = `-- name: ListProjectAPIKeys :many
SELECT id, name, prefix, created_at, revoked_at FROM project_api_keys
WHERE binding_digest = $1 AND tenant_id = $2 AND organization_id = $3
  AND project_id = $4 AND subject_kind = $5 AND subject_id = $6
ORDER BY created_at DESC, id
`

type ListProjectAPIKeysParams struct {
	BindingDigest  string      `json:"binding_digest"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
	SubjectKind    string      `json:"subject_kind"`
	SubjectID      string      `json:"subject_id"`
}

type ListProjectAPIKeysRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListProjectAPIKeys(ctx context.Context, arg ListProjectAPIKeysParams) ([]ListProjectAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listProjectAPIKeys,
		arg.BindingDigest,
		arg.TenantID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.SubjectKind,
		arg.SubjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectAPIKeysRow{}
	for rows.Next() {
		var i ListProjectAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProjectAPIKey = `-- name: ResolveProjectAPIKey :one
SELECT binding_digest, tenant_id, organization_id, project_id, subject_kind, subject_id
FROM project_api_keys WHERE token_sha256 = $1 AND revoked_at IS NULL
`

type ResolveProjectAPIKeyRow struct {
	BindingDigest  string      `json:"binding_digest"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
	SubjectKind    string      `json:"subject_kind"`
	SubjectID      string      `json:"subject_id"`
}

func (q *Queries) ResolveProjectAPIKey(ctx context.Context, tokenSha256 string) (ResolveProjectAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, resolveProjectAPIKey, tokenSha256)
	var i ResolveProjectAPIKeyRow
	err := row.Scan(
		&i.BindingDigest,
		&i.TenantID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.SubjectKind,
		&i.SubjectID,
	)
	return i, err
}

const revokeProjectAPIKey = `-- name: RevokeProjectAPIKey :execrows
UPDATE project_api_keys SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1 AND binding_digest = $2 AND tenant_id = $3 AND organization_id = $4
  AND project_id = $5 AND subject_kind = $6 AND subject_id = $7
`

type RevokeProjectAPIKeyParams struct {
	ID             pgtype.UUID `json:"id"`
	BindingDigest  string      `json:"binding_digest"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID string      `json:"organization_id"`
	ProjectID      string      `json:"project_id"`
	SubjectKind    string      `json:"subject_kind"`
	SubjectID      string      `json:"subject_id"`
}

func (q *Queries) RevokeProjectAPIKey(ctx context.Context, arg RevokeProjectAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeProjectAPIKey,
		arg.ID,
		arg.BindingDigest,
		arg.TenantID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.SubjectKind,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
