// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_allocations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRuntimeAllocation = `-- name: CreateRuntimeAllocation :one
INSERT INTO runtime_allocations (id, environment_id, device_id, provider_key, initialization)
VALUES ($1, $2, $3, $4, CASE WHEN EXISTS (SELECT 1 FROM initial_environment_files f JOIN environments e ON e.session_id = f.session_id WHERE e.id = $2) OR EXISTS (SELECT 1 FROM environment_setups f JOIN environments e ON e.session_id = f.session_id WHERE e.id = $2) THEN 'pending' ELSE 'complete' END) RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until
`

type CreateRuntimeAllocationParams struct {
	ID            pgtype.UUID `json:"id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	DeviceID      pgtype.UUID `json:"device_id"`
	ProviderKey   pgtype.UUID `json:"provider_key"`
}

func (q *Queries) CreateRuntimeAllocation(ctx context.Context, arg CreateRuntimeAllocationParams) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, createRuntimeAllocation,
		arg.ID,
		arg.EnvironmentID,
		arg.DeviceID,
		arg.ProviderKey,
	)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
	)
	return i, err
}

const getRuntimeAllocation = `-- name: GetRuntimeAllocation :one
SELECT a.id, a.environment_id, a.device_id, a.provider_key, a.state, a.create_settled, a.created_at, a.kept_at, a.released_at, a.initialization, a.compute_phase, a.compute_revision, a.compute_state, a.compute_activity_at, a.compute_wake_requested, a.compute_retained_until, e.session_id, s.tenant_id, s.deleted_at, (CASE WHEN a.compute_phase NOT IN ('disabled', 'running') THEN a.compute_retained_until IS NOT NULL AND a.compute_retained_until <= clock_timestamp() ELSE a.kept_at <= clock_timestamp() - interval '1 hour' END)::boolean AS expired
FROM runtime_allocations a
JOIN environments e ON e.id = a.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE s.tenant_id = $1 AND a.environment_id = $2
`

type GetRuntimeAllocationParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

type GetRuntimeAllocationRow struct {
	RuntimeAllocation RuntimeAllocation  `json:"runtime_allocation"`
	SessionID         pgtype.UUID        `json:"session_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Expired           bool               `json:"expired"`
}

func (q *Queries) GetRuntimeAllocation(ctx context.Context, arg GetRuntimeAllocationParams) (GetRuntimeAllocationRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeAllocation, arg.TenantID, arg.EnvironmentID)
	var i GetRuntimeAllocationRow
	err := row.Scan(
		&i.RuntimeAllocation.ID,
		&i.RuntimeAllocation.EnvironmentID,
		&i.RuntimeAllocation.DeviceID,
		&i.RuntimeAllocation.ProviderKey,
		&i.RuntimeAllocation.State,
		&i.RuntimeAllocation.CreateSettled,
		&i.RuntimeAllocation.CreatedAt,
		&i.RuntimeAllocation.KeptAt,
		&i.RuntimeAllocation.ReleasedAt,
		&i.RuntimeAllocation.Initialization,
		&i.RuntimeAllocation.ComputePhase,
		&i.RuntimeAllocation.ComputeRevision,
		&i.RuntimeAllocation.ComputeState,
		&i.RuntimeAllocation.ComputeActivityAt,
		&i.RuntimeAllocation.ComputeWakeRequested,
		&i.RuntimeAllocation.ComputeRetainedUntil,
		&i.SessionID,
		&i.TenantID,
		&i.DeletedAt,
		&i.Expired,
	)
	return i, err
}

const keepRuntimeAllocation = `-- name: KeepRuntimeAllocation :one
UPDATE runtime_allocations SET kept_at = clock_timestamp()
WHERE id = $1 AND state = 'running'
AND kept_at > clock_timestamp() - interval '1 hour'
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until
`

func (q *Queries) KeepRuntimeAllocation(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, keepRuntimeAllocation, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
	)
	return i, err
}

const listRuntimeAllocations = `-- name: ListRuntimeAllocations :many
SELECT a.id, a.environment_id, a.device_id, a.provider_key, a.state, a.create_settled, a.created_at, a.kept_at, a.released_at, a.initialization, a.compute_phase, a.compute_revision, a.compute_state, a.compute_activity_at, a.compute_wake_requested, a.compute_retained_until, e.session_id, s.tenant_id, s.deleted_at, (CASE WHEN a.compute_phase NOT IN ('disabled', 'running') THEN a.compute_retained_until IS NOT NULL AND a.compute_retained_until <= clock_timestamp() ELSE a.kept_at <= clock_timestamp() - interval '1 hour' END)::boolean AS expired
FROM runtime_allocations a
JOIN environments e ON e.id = a.environment_id
JOIN sessions s ON s.id = e.session_id
WHERE a.id > $1 AND a.state <> 'released'
ORDER BY a.id LIMIT 32
`

type ListRuntimeAllocationsRow struct {
	RuntimeAllocation RuntimeAllocation  `json:"runtime_allocation"`
	SessionID         pgtype.UUID        `json:"session_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Expired           bool               `json:"expired"`
}

func (q *Queries) ListRuntimeAllocations(ctx context.Context, id pgtype.UUID) ([]ListRuntimeAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeAllocations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeAllocationsRow{}
	for rows.Next() {
		var i ListRuntimeAllocationsRow
		if err := rows.Scan(
			&i.RuntimeAllocation.ID,
			&i.RuntimeAllocation.EnvironmentID,
			&i.RuntimeAllocation.DeviceID,
			&i.RuntimeAllocation.ProviderKey,
			&i.RuntimeAllocation.State,
			&i.RuntimeAllocation.CreateSettled,
			&i.RuntimeAllocation.CreatedAt,
			&i.RuntimeAllocation.KeptAt,
			&i.RuntimeAllocation.ReleasedAt,
			&i.RuntimeAllocation.Initialization,
			&i.RuntimeAllocation.ComputePhase,
			&i.RuntimeAllocation.ComputeRevision,
			&i.RuntimeAllocation.ComputeState,
			&i.RuntimeAllocation.ComputeActivityAt,
			&i.RuntimeAllocation.ComputeWakeRequested,
			&i.RuntimeAllocation.ComputeRetainedUntil,
			&i.SessionID,
			&i.TenantID,
			&i.DeletedAt,
			&i.Expired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnallocatedHostedEnvironments = `-- name: ListUnallocatedHostedEnvironments :many
SELECT e.id, s.tenant_id
FROM environments e JOIN sessions s ON s.id = e.session_id
WHERE e.id > $1 AND s.deleted_at IS NULL AND e.status = 'pending'
  AND s.configuration->'environment'->>'type' = 'openai_hosted'
  AND NOT EXISTS (SELECT 1 FROM runtime_allocations a WHERE a.environment_id = e.id)
ORDER BY e.id LIMIT 32
`

type ListUnallocatedHostedEnvironmentsRow struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListUnallocatedHostedEnvironments(ctx context.Context, id pgtype.UUID) ([]ListUnallocatedHostedEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listUnallocatedHostedEnvironments, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnallocatedHostedEnvironmentsRow{}
	for rows.Next() {
		var i ListUnallocatedHostedEnvironmentsRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observeRuntimeRunning = `-- name: ObserveRuntimeRunning :one
UPDATE runtime_allocations SET state = 'running', create_settled = true
WHERE id = $1 AND state IN ('creating', 'running')
AND kept_at > clock_timestamp() - interval '1 hour'
RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until
`

func (q *Queries) ObserveRuntimeRunning(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, observeRuntimeRunning, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
	)
	return i, err
}

const releaseRuntimeAllocation = `-- name: ReleaseRuntimeAllocation :one
UPDATE runtime_allocations SET state = 'released', released_at = clock_timestamp()
WHERE id = $1 AND state = 'cleanup_pending' AND create_settled RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until
`

func (q *Queries) ReleaseRuntimeAllocation(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, releaseRuntimeAllocation, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
	)
	return i, err
}

const requestRuntimeCleanup = `-- name: RequestRuntimeCleanup :one
UPDATE runtime_allocations SET state = 'cleanup_pending'
WHERE id = $1 AND state <> 'released' RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until
`

func (q *Queries) RequestRuntimeCleanup(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, requestRuntimeCleanup, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
	)
	return i, err
}

const settleRuntimeCreation = `-- name: SettleRuntimeCreation :one
UPDATE runtime_allocations SET create_settled = true
WHERE id = $1 AND state <> 'released' RETURNING id, environment_id, device_id, provider_key, state, create_settled, created_at, kept_at, released_at, initialization, compute_phase, compute_revision, compute_state, compute_activity_at, compute_wake_requested, compute_retained_until
`

func (q *Queries) SettleRuntimeCreation(ctx context.Context, id pgtype.UUID) (RuntimeAllocation, error) {
	row := q.db.QueryRow(ctx, settleRuntimeCreation, id)
	var i RuntimeAllocation
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.DeviceID,
		&i.ProviderKey,
		&i.State,
		&i.CreateSettled,
		&i.CreatedAt,
		&i.KeptAt,
		&i.ReleasedAt,
		&i.Initialization,
		&i.ComputePhase,
		&i.ComputeRevision,
		&i.ComputeState,
		&i.ComputeActivityAt,
		&i.ComputeWakeRequested,
		&i.ComputeRetainedUntil,
	)
	return i, err
}
