// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runtime_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRuntimeHistorySample = `-- name: InsertRuntimeHistorySample :exec
INSERT INTO runtime_history_samples (
    tenant_id, session_id, environment_id, resolved_at_ns, allocation_id, provider_type,
    status, observed_at_ns, started_at_ns, cpu_usage_seconds, cpu_capacity_cores,
    memory_usage_bytes, memory_limit_bytes, input_tokens, output_tokens
)
SELECT s.tenant_id, s.id, e.id, $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10, $11, $12
FROM sessions s JOIN environments e ON e.session_id = s.id
WHERE s.tenant_id = $13 AND s.id = $14 AND e.id = $15
ON CONFLICT (tenant_id, session_id, environment_id, resolved_at_ns) DO NOTHING
`

type InsertRuntimeHistorySampleParams struct {
	ResolvedAtNs     int64         `json:"resolved_at_ns"`
	AllocationID     pgtype.UUID   `json:"allocation_id"`
	ProviderType     string        `json:"provider_type"`
	Status           string        `json:"status"`
	ObservedAtNs     pgtype.Int8   `json:"observed_at_ns"`
	StartedAtNs      pgtype.Int8   `json:"started_at_ns"`
	CpuUsageSeconds  pgtype.Float8 `json:"cpu_usage_seconds"`
	CpuCapacityCores pgtype.Float8 `json:"cpu_capacity_cores"`
	MemoryUsageBytes pgtype.Int8   `json:"memory_usage_bytes"`
	MemoryLimitBytes pgtype.Int8   `json:"memory_limit_bytes"`
	InputTokens      pgtype.Int8   `json:"input_tokens"`
	OutputTokens     pgtype.Int8   `json:"output_tokens"`
	TenantID         pgtype.UUID   `json:"tenant_id"`
	SessionID        pgtype.UUID   `json:"session_id"`
	EnvironmentID    pgtype.UUID   `json:"environment_id"`
}

func (q *Queries) InsertRuntimeHistorySample(ctx context.Context, arg InsertRuntimeHistorySampleParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeHistorySample,
		arg.ResolvedAtNs,
		arg.AllocationID,
		arg.ProviderType,
		arg.Status,
		arg.ObservedAtNs,
		arg.StartedAtNs,
		arg.CpuUsageSeconds,
		arg.CpuCapacityCores,
		arg.MemoryUsageBytes,
		arg.MemoryLimitBytes,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TenantID,
		arg.SessionID,
		arg.EnvironmentID,
	)
	return err
}

const listRuntimeHistorySamples = `-- name: ListRuntimeHistorySamples :many
SELECT tenant_id, session_id, environment_id, resolved_at_ns, allocation_id, provider_type, status, observed_at_ns, started_at_ns, cpu_usage_seconds, cpu_capacity_cores, memory_usage_bytes, memory_limit_bytes, input_tokens, output_tokens FROM runtime_history_samples
WHERE tenant_id = $1 AND session_id = $2 AND environment_id = $3
  AND resolved_at_ns >= $4 AND resolved_at_ns < $5
ORDER BY resolved_at_ns
LIMIT $6
`

type ListRuntimeHistorySamplesParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	SessionID     pgtype.UUID `json:"session_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	StartNs       int64       `json:"start_ns"`
	EndNs         int64       `json:"end_ns"`
	RowLimit      int32       `json:"row_limit"`
}

func (q *Queries) ListRuntimeHistorySamples(ctx context.Context, arg ListRuntimeHistorySamplesParams) ([]RuntimeHistorySample, error) {
	rows, err := q.db.Query(ctx, listRuntimeHistorySamples,
		arg.TenantID,
		arg.SessionID,
		arg.EnvironmentID,
		arg.StartNs,
		arg.EndNs,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeHistorySample{}
	for rows.Next() {
		var i RuntimeHistorySample
		if err := rows.Scan(
			&i.TenantID,
			&i.SessionID,
			&i.EnvironmentID,
			&i.ResolvedAtNs,
			&i.AllocationID,
			&i.ProviderType,
			&i.Status,
			&i.ObservedAtNs,
			&i.StartedAtNs,
			&i.CpuUsageSeconds,
			&i.CpuCapacityCores,
			&i.MemoryUsageBytes,
			&i.MemoryLimitBytes,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRuntimeHistorySamples = `-- name: PruneRuntimeHistorySamples :execrows
WITH expired AS (
    SELECT p.tenant_id, p.session_id, p.environment_id, p.resolved_at_ns FROM runtime_history_samples p
    WHERE p.resolved_at_ns < $1
    ORDER BY p.resolved_at_ns LIMIT 256 FOR UPDATE SKIP LOCKED
)
DELETE FROM runtime_history_samples h USING expired e
WHERE h.tenant_id = e.tenant_id AND h.session_id = e.session_id
  AND h.environment_id = e.environment_id AND h.resolved_at_ns = e.resolved_at_ns
`

func (q *Queries) PruneRuntimeHistorySamples(ctx context.Context, beforeNs int64) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRuntimeHistorySamples, beforeNs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
