// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_deployment_setup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSandboxOwnerEpoch = `-- name: AdvanceSandboxOwnerEpoch :exec
UPDATE runtime_deployment SET owner_epoch=owner_epoch+1 WHERE singleton=true
`

func (q *Queries) AdvanceSandboxOwnerEpoch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, advanceSandboxOwnerEpoch)
	return err
}

const claimWebSandboxDeployment = `-- name: ClaimWebSandboxDeployment :exec
UPDATE runtime_deployment SET installation_id=$1, web_managed=true,
owner_epoch=owner_epoch+1, updated_at=clock_timestamp() WHERE singleton=true
`

func (q *Queries) ClaimWebSandboxDeployment(ctx context.Context, installationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, claimWebSandboxDeployment, installationID)
	return err
}

const initializeSandboxDeployment = `-- name: InitializeSandboxDeployment :exec
UPDATE runtime_deployment SET provider_kind=$1, backend_fingerprint=$2,
idle_seconds=$3, retention_seconds=$4, generation=$5, mode=$6, e2b_template=$7, e2b_credential=$8, specification=$9,
e2b_api_url=$10, e2b_domain=$11,
e2b_template_build_status=$12, e2b_template_cpus=$13,
e2b_template_memory_mib=$14, e2b_template_root_disk_mib=$15,
updated_at=clock_timestamp() WHERE singleton=true
`

type InitializeSandboxDeploymentParams struct {
	ProviderKind           string      `json:"provider_kind"`
	BackendFingerprint     string      `json:"backend_fingerprint"`
	IdleSeconds            int64       `json:"idle_seconds"`
	RetentionSeconds       int64       `json:"retention_seconds"`
	Generation             int64       `json:"generation"`
	Mode                   string      `json:"mode"`
	E2bTemplate            string      `json:"e2b_template"`
	E2bCredential          []byte      `json:"e2b_credential"`
	Specification          []byte      `json:"specification"`
	E2bApiUrl              string      `json:"e2b_api_url"`
	E2bDomain              string      `json:"e2b_domain"`
	E2bTemplateBuildStatus pgtype.Text `json:"e2b_template_build_status"`
	E2bTemplateCpus        pgtype.Int4 `json:"e2b_template_cpus"`
	E2bTemplateMemoryMib   pgtype.Int4 `json:"e2b_template_memory_mib"`
	E2bTemplateRootDiskMib pgtype.Int4 `json:"e2b_template_root_disk_mib"`
}

func (q *Queries) InitializeSandboxDeployment(ctx context.Context, arg InitializeSandboxDeploymentParams) error {
	_, err := q.db.Exec(ctx, initializeSandboxDeployment,
		arg.ProviderKind,
		arg.BackendFingerprint,
		arg.IdleSeconds,
		arg.RetentionSeconds,
		arg.Generation,
		arg.Mode,
		arg.E2bTemplate,
		arg.E2bCredential,
		arg.Specification,
		arg.E2bApiUrl,
		arg.E2bDomain,
		arg.E2bTemplateBuildStatus,
		arg.E2bTemplateCpus,
		arg.E2bTemplateMemoryMib,
		arg.E2bTemplateRootDiskMib,
	)
	return err
}

const recordSandboxTemplateBuild = `-- name: RecordSandboxTemplateBuild :exec
UPDATE runtime_deployment SET e2b_template_build_status=$1, e2b_template_cpus=$2,
e2b_template_memory_mib=$3, e2b_template_root_disk_mib=$4,
updated_at=clock_timestamp() WHERE singleton=true AND e2b_template<>''
`

type RecordSandboxTemplateBuildParams struct {
	E2bTemplateBuildStatus pgtype.Text `json:"e2b_template_build_status"`
	E2bTemplateCpus        pgtype.Int4 `json:"e2b_template_cpus"`
	E2bTemplateMemoryMib   pgtype.Int4 `json:"e2b_template_memory_mib"`
	E2bTemplateRootDiskMib pgtype.Int4 `json:"e2b_template_root_disk_mib"`
}

func (q *Queries) RecordSandboxTemplateBuild(ctx context.Context, arg RecordSandboxTemplateBuildParams) error {
	_, err := q.db.Exec(ctx, recordSandboxTemplateBuild,
		arg.E2bTemplateBuildStatus,
		arg.E2bTemplateCpus,
		arg.E2bTemplateMemoryMib,
		arg.E2bTemplateRootDiskMib,
	)
	return err
}

const retireSandboxEnrollments = `-- name: RetireSandboxEnrollments :exec
UPDATE runtime_node_enrollments SET expires_at=clock_timestamp() WHERE consumed_at IS NULL
`

func (q *Queries) RetireSandboxEnrollments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireSandboxEnrollments)
	return err
}

const retireSandboxNodes = `-- name: RetireSandboxNodes :exec
UPDATE runtime_nodes SET removed_at=clock_timestamp(),connection_id=NULL,provider_ready=false,ready_generation=NULL WHERE removed_at IS NULL
`

func (q *Queries) RetireSandboxNodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, retireSandboxNodes)
	return err
}
