// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sandbox_deployment_setup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebSandboxDeployment = `-- name: ClaimWebSandboxDeployment :exec
UPDATE runtime_deployment SET installation_id=$1, web_managed=true,
owner_epoch=owner_epoch+1, updated_at=clock_timestamp() WHERE singleton=true
`

func (q *Queries) ClaimWebSandboxDeployment(ctx context.Context, installationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, claimWebSandboxDeployment, installationID)
	return err
}

const initializeSandboxDeployment = `-- name: InitializeSandboxDeployment :exec
UPDATE runtime_deployment SET provider_kind=$1, core_url=$2, backend_fingerprint=$3,
idle_seconds=$4, retention_seconds=$5, updated_at=clock_timestamp() WHERE singleton=true
`

type InitializeSandboxDeploymentParams struct {
	ProviderKind       string `json:"provider_kind"`
	CoreUrl            string `json:"core_url"`
	BackendFingerprint string `json:"backend_fingerprint"`
	IdleSeconds        int64  `json:"idle_seconds"`
	RetentionSeconds   int64  `json:"retention_seconds"`
}

func (q *Queries) InitializeSandboxDeployment(ctx context.Context, arg InitializeSandboxDeploymentParams) error {
	_, err := q.db.Exec(ctx, initializeSandboxDeployment,
		arg.ProviderKind,
		arg.CoreUrl,
		arg.BackendFingerprint,
		arg.IdleSeconds,
		arg.RetentionSeconds,
	)
	return err
}
