// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: skills.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSkillVersion = `-- name: AdvanceSkillVersion :exec
UPDATE skills SET latest_version = next_version, next_version = next_version + 1,
 default_version = CASE WHEN $1::boolean THEN next_version ELSE default_version END
WHERE tenant_id = $2 AND id = $3
`

type AdvanceSkillVersionParams struct {
	MakeDefault bool        `json:"make_default"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) AdvanceSkillVersion(ctx context.Context, arg AdvanceSkillVersionParams) error {
	_, err := q.db.Exec(ctx, advanceSkillVersion, arg.MakeDefault, arg.TenantID, arg.ID)
	return err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, tenant_id, name, description, default_version, latest_version, next_version)
VALUES ($1, $2, $3, $4, 1, 1, 2)
RETURNING id, tenant_id, name, description, created_at, default_version, latest_version, next_version
`

type CreateSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DefaultVersion,
		&i.LatestVersion,
		&i.NextVersion,
	)
	return i, err
}

const createSkillVersion = `-- name: CreateSkillVersion :one
INSERT INTO skill_versions (id, tenant_id, skill_id, version, name, description, contents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, skill_id, version, name, description, created_at
`

type CreateSkillVersionParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	SkillID     pgtype.UUID `json:"skill_id"`
	Version     int64       `json:"version"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Contents    []byte      `json:"contents"`
}

type CreateSkillVersionRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) (CreateSkillVersionRow, error) {
	row := q.db.QueryRow(ctx, createSkillVersion,
		arg.ID,
		arg.TenantID,
		arg.SkillID,
		arg.Version,
		arg.Name,
		arg.Description,
		arg.Contents,
	)
	var i CreateSkillVersionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SkillID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :one
DELETE FROM skills WHERE tenant_id = $1 AND id = $2 RETURNING id
`

type DeleteSkillParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteSkill, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSkillVersion = `-- name: DeleteSkillVersion :one
DELETE FROM skill_versions WHERE tenant_id = $1 AND skill_id = $2 AND version = $3
RETURNING id, tenant_id, skill_id, version, name, description, created_at
`

type DeleteSkillVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SkillID  pgtype.UUID `json:"skill_id"`
	Version  int64       `json:"version"`
}

type DeleteSkillVersionRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) DeleteSkillVersion(ctx context.Context, arg DeleteSkillVersionParams) (DeleteSkillVersionRow, error) {
	row := q.db.QueryRow(ctx, deleteSkillVersion, arg.TenantID, arg.SkillID, arg.Version)
	var i DeleteSkillVersionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SkillID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getSkill = `-- name: GetSkill :one
SELECT id, tenant_id, name, description, created_at, default_version, latest_version, next_version FROM skills WHERE tenant_id = $1 AND id = $2
`

type GetSkillParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.TenantID, arg.ID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DefaultVersion,
		&i.LatestVersion,
		&i.NextVersion,
	)
	return i, err
}

const getSkillVersion = `-- name: GetSkillVersion :one
SELECT id, tenant_id, skill_id, version, name, description, created_at
FROM skill_versions WHERE tenant_id = $1 AND skill_id = $2 AND version = $3
`

type GetSkillVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SkillID  pgtype.UUID `json:"skill_id"`
	Version  int64       `json:"version"`
}

type GetSkillVersionRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSkillVersion(ctx context.Context, arg GetSkillVersionParams) (GetSkillVersionRow, error) {
	row := q.db.QueryRow(ctx, getSkillVersion, arg.TenantID, arg.SkillID, arg.Version)
	var i GetSkillVersionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SkillID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillVersionByID = `-- name: GetSkillVersionByID :one
SELECT id, tenant_id, skill_id, version, name, description, created_at
FROM skill_versions WHERE tenant_id = $1 AND skill_id = $2 AND id = $3
`

type GetSkillVersionByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SkillID  pgtype.UUID `json:"skill_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetSkillVersionByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSkillVersionByID(ctx context.Context, arg GetSkillVersionByIDParams) (GetSkillVersionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSkillVersionByID, arg.TenantID, arg.SkillID, arg.ID)
	var i GetSkillVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SkillID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listSkillVersions = `-- name: ListSkillVersions :many
SELECT id, tenant_id, skill_id, version, name, description, created_at
FROM skill_versions
WHERE tenant_id = $1 AND skill_id = $2
 AND ($3::bigint IS NULL
 OR ($4::boolean AND version > $3::bigint)
 OR (NOT $4::boolean AND version < $3::bigint))
ORDER BY CASE WHEN $4::boolean THEN version END ASC,
 CASE WHEN NOT $4::boolean THEN version END DESC
LIMIT $5
`

type ListSkillVersionsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SkillID      pgtype.UUID `json:"skill_id"`
	AfterVersion pgtype.Int8 `json:"after_version"`
	Ascending    bool        `json:"ascending"`
	PageLimit    int32       `json:"page_limit"`
}

type ListSkillVersionsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SkillID     pgtype.UUID        `json:"skill_id"`
	Version     int64              `json:"version"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSkillVersions(ctx context.Context, arg ListSkillVersionsParams) ([]ListSkillVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSkillVersions,
		arg.TenantID,
		arg.SkillID,
		arg.AfterVersion,
		arg.Ascending,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillVersionsRow{}
	for rows.Next() {
		var i ListSkillVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SkillID,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, tenant_id, name, description, created_at, default_version, latest_version, next_version FROM skills
WHERE tenant_id = $1
 AND ($2::timestamptz IS NULL
 OR ($3::boolean AND (created_at, id) > ($2::timestamptz, $4::uuid))
 OR (NOT $3::boolean AND (created_at, id) < ($2::timestamptz, $4::uuid)))
ORDER BY
 CASE WHEN $3::boolean THEN created_at END ASC,
 CASE WHEN $3::boolean THEN id END ASC,
 CASE WHEN NOT $3::boolean THEN created_at END DESC,
 CASE WHEN NOT $3::boolean THEN id END DESC
LIMIT $5
`

type ListSkillsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListSkills(ctx context.Context, arg ListSkillsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills,
		arg.TenantID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.DefaultVersion,
			&i.LatestVersion,
			&i.NextVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSkill = `-- name: LockSkill :one
SELECT id, tenant_id, name, description, created_at, default_version, latest_version, next_version FROM skills WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockSkillParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) LockSkill(ctx context.Context, arg LockSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, lockSkill, arg.TenantID, arg.ID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DefaultVersion,
		&i.LatestVersion,
		&i.NextVersion,
	)
	return i, err
}

const readDefaultSkillVersion = `-- name: ReadDefaultSkillVersion :one
SELECT v.id, v.tenant_id, v.skill_id, v.version, v.name, v.description, v.created_at, v.contents FROM skill_versions v JOIN skills s ON s.id = v.skill_id AND s.default_version = v.version
WHERE s.tenant_id = $1 AND s.id = $2
`

type ReadDefaultSkillVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ReadDefaultSkillVersion(ctx context.Context, arg ReadDefaultSkillVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, readDefaultSkillVersion, arg.TenantID, arg.ID)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SkillID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Contents,
	)
	return i, err
}

const readSkillVersion = `-- name: ReadSkillVersion :one
SELECT id, tenant_id, skill_id, version, name, description, created_at, contents FROM skill_versions WHERE tenant_id = $1 AND skill_id = $2 AND version = $3
`

type ReadSkillVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SkillID  pgtype.UUID `json:"skill_id"`
	Version  int64       `json:"version"`
}

func (q *Queries) ReadSkillVersion(ctx context.Context, arg ReadSkillVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, readSkillVersion, arg.TenantID, arg.SkillID, arg.Version)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SkillID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Contents,
	)
	return i, err
}

const refreshLatestSkillVersion = `-- name: RefreshLatestSkillVersion :exec
UPDATE skills SET latest_version = (SELECT max(v.version) FROM skill_versions v WHERE v.skill_id = skills.id)
WHERE skills.tenant_id = $1 AND skills.id = $2
`

type RefreshLatestSkillVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) RefreshLatestSkillVersion(ctx context.Context, arg RefreshLatestSkillVersionParams) error {
	_, err := q.db.Exec(ctx, refreshLatestSkillVersion, arg.TenantID, arg.ID)
	return err
}

const setDefaultSkillVersion = `-- name: SetDefaultSkillVersion :one
UPDATE skills SET default_version = $3 WHERE tenant_id = $1 AND id = $2 RETURNING id, tenant_id, name, description, created_at, default_version, latest_version, next_version
`

type SetDefaultSkillVersionParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ID             pgtype.UUID `json:"id"`
	DefaultVersion int64       `json:"default_version"`
}

func (q *Queries) SetDefaultSkillVersion(ctx context.Context, arg SetDefaultSkillVersionParams) (Skill, error) {
	row := q.db.QueryRow(ctx, setDefaultSkillVersion, arg.TenantID, arg.ID, arg.DefaultVersion)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.DefaultVersion,
		&i.LatestVersion,
		&i.NextVersion,
	)
	return i, err
}
