// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: turns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns(id, session_id) VALUES ($1, $2) RETURNING id, session_id, status, created_at, started_at, completed_at, cancel_requested_at, outcome, event_count, event_bytes, token_usage, artifact_capture_started
`

type CreateTurnParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn, arg.ID, arg.SessionID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.TokenUsage,
		&i.ArtifactCaptureStarted,
	)
	return i, err
}

const createTurnInput = `-- name: CreateTurnInput :one
INSERT INTO turn_inputs(session_id, turn_id, idempotency_key, kind, payload, batch_position)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING sequence
`

type CreateTurnInputParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	TurnID         pgtype.UUID `json:"turn_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Kind           string      `json:"kind"`
	Payload        []byte      `json:"payload"`
	BatchPosition  int32       `json:"batch_position"`
}

func (q *Queries) CreateTurnInput(ctx context.Context, arg CreateTurnInputParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTurnInput,
		arg.SessionID,
		arg.TurnID,
		arg.IdempotencyKey,
		arg.Kind,
		arg.Payload,
		arg.BatchPosition,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const findInputBatch = `-- name: FindInputBatch :many
WITH previous AS (
    SELECT sequence, turn_id, kind, payload, batch_position FROM turn_inputs
    WHERE session_id = $1 AND idempotency_key = $2
)
SELECT sequence, turn_id, COALESCE((
    SELECT jsonb_agg(jsonb_build_object('kind', kind, 'payload', payload) ORDER BY batch_position)
        = $3::jsonb FROM previous
), false)::boolean AS matches
FROM previous ORDER BY batch_position
`

type FindInputBatchParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Batch          []byte      `json:"batch"`
}

type FindInputBatchRow struct {
	Sequence int64       `json:"sequence"`
	TurnID   pgtype.UUID `json:"turn_id"`
	Matches  bool        `json:"matches"`
}

func (q *Queries) FindInputBatch(ctx context.Context, arg FindInputBatchParams) ([]FindInputBatchRow, error) {
	rows, err := q.db.Query(ctx, findInputBatch, arg.SessionID, arg.IdempotencyKey, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindInputBatchRow{}
	for rows.Next() {
		var i FindInputBatchRow
		if err := rows.Scan(&i.Sequence, &i.TurnID, &i.Matches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTurn = `-- name: GetActiveTurn :one
SELECT id, session_id, status, created_at, started_at, completed_at, cancel_requested_at, outcome, event_count, event_bytes, token_usage, artifact_capture_started FROM turns WHERE session_id = $1 AND status IN ('queued', 'in_progress', 'waiting')
`

func (q *Queries) GetActiveTurn(ctx context.Context, sessionID pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, getActiveTurn, sessionID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.TokenUsage,
		&i.ArtifactCaptureStarted,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT t.id, t.session_id, t.status, t.created_at, t.started_at, t.completed_at, t.cancel_requested_at, t.outcome, t.event_count, t.event_bytes, t.token_usage, t.artifact_capture_started FROM turns t JOIN sessions s ON s.id = t.session_id
WHERE s.tenant_id = $1 AND t.session_id = $2 AND t.id = $3
`

type GetTurnParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetTurn(ctx context.Context, arg GetTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, arg.TenantID, arg.SessionID, arg.ID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.TokenUsage,
		&i.ArtifactCaptureStarted,
	)
	return i, err
}

const hasUnappliedMessages = `-- name: HasUnappliedMessages :one
SELECT EXISTS(SELECT 1 FROM turn_inputs
WHERE session_id = $1 AND turn_id = $2 AND sequence > $3 AND kind = 'message')
`

type HasUnappliedMessagesParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	Sequence  int64       `json:"sequence"`
}

func (q *Queries) HasUnappliedMessages(ctx context.Context, arg HasUnappliedMessagesParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnappliedMessages, arg.SessionID, arg.TurnID, arg.Sequence)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTurnInputs = `-- name: ListTurnInputs :many
SELECT i.sequence, i.session_id, i.turn_id, i.idempotency_key, i.kind, i.payload, i.created_at, i.batch_position FROM turn_inputs i JOIN sessions s ON s.id = i.session_id
WHERE s.tenant_id = $1 AND i.session_id = $2 AND i.turn_id = $3 AND i.sequence > $4
ORDER BY i.sequence LIMIT $5
`

type ListTurnInputsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SessionID pgtype.UUID `json:"session_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
	Sequence  int64       `json:"sequence"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTurnInputs(ctx context.Context, arg ListTurnInputsParams) ([]TurnInput, error) {
	rows, err := q.db.Query(ctx, listTurnInputs,
		arg.TenantID,
		arg.SessionID,
		arg.TurnID,
		arg.Sequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TurnInput{}
	for rows.Next() {
		var i TurnInput
		if err := rows.Scan(
			&i.Sequence,
			&i.SessionID,
			&i.TurnID,
			&i.IdempotencyKey,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.BatchPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT id, deleted_at FROM sessions WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockSessionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type LockSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) LockSession(ctx context.Context, arg LockSessionParams) (LockSessionRow, error) {
	row := q.db.QueryRow(ctx, lockSession, arg.TenantID, arg.ID)
	var i LockSessionRow
	err := row.Scan(&i.ID, &i.DeletedAt)
	return i, err
}

const requestTurnCancel = `-- name: RequestTurnCancel :exec
UPDATE turns SET cancel_requested_at = COALESCE(cancel_requested_at, clock_timestamp()),
    completed_at = CASE WHEN status = 'queued' THEN clock_timestamp() ELSE completed_at END,
    status = CASE WHEN status = 'queued' THEN 'cancelled' ELSE status END
WHERE id = $1 AND session_id = $2 AND status IN ('queued', 'in_progress', 'waiting')
`

type RequestTurnCancelParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) RequestTurnCancel(ctx context.Context, arg RequestTurnCancelParams) error {
	_, err := q.db.Exec(ctx, requestTurnCancel, arg.ID, arg.SessionID)
	return err
}

const transitionTurn = `-- name: TransitionTurn :one
UPDATE turns SET status = $1, outcome = $2,
    started_at = CASE WHEN $1::text = 'in_progress'
        THEN COALESCE(started_at, clock_timestamp()) ELSE started_at END,
    completed_at = CASE WHEN $1::text IN ('completed', 'failed', 'cancelled')
        THEN COALESCE($3::timestamptz, clock_timestamp()) ELSE NULL END
WHERE id = $4 AND session_id = $5
    AND status = $6
    AND status IN ('queued', 'in_progress', 'waiting')
    AND ($1::text <> 'in_progress' OR cancel_requested_at IS NULL)
RETURNING id, session_id, status, created_at, started_at, completed_at, cancel_requested_at, outcome, event_count, event_bytes, token_usage, artifact_capture_started
`

type TransitionTurnParams struct {
	NewStatus         string             `json:"new_status"`
	Outcome           []byte             `json:"outcome"`
	SourceCompletedAt pgtype.Timestamptz `json:"source_completed_at"`
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	ExpectedStatus    string             `json:"expected_status"`
}

func (q *Queries) TransitionTurn(ctx context.Context, arg TransitionTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, transitionTurn,
		arg.NewStatus,
		arg.Outcome,
		arg.SourceCompletedAt,
		arg.ID,
		arg.SessionID,
		arg.ExpectedStatus,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelRequestedAt,
		&i.Outcome,
		&i.EventCount,
		&i.EventBytes,
		&i.TokenUsage,
		&i.ArtifactCaptureStarted,
	)
	return i, err
}
