// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: turn_reads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTurns = `-- name: ListTurns :many
SELECT t.id, t.session_id, t.status, t.created_at, t.started_at, t.completed_at, t.cancel_requested_at, t.outcome, t.token_usage, t.artifact_capture_started, t.subagent_id FROM public_execution_turns t JOIN sessions s ON s.id = t.session_id
WHERE s.tenant_id = $1 AND t.session_id = $2
  AND ($3::timestamptz IS NULL
       OR (NOT $4::boolean AND (t.created_at, t.id) < ($3::timestamptz, $5::uuid))
       OR ($4::boolean AND (t.created_at, t.id) > ($3::timestamptz, $5::uuid)))
ORDER BY
    CASE WHEN $4::boolean THEN t.created_at END ASC,
    CASE WHEN $4::boolean THEN t.id END ASC,
    CASE WHEN NOT $4::boolean THEN t.created_at END DESC,
    CASE WHEN NOT $4::boolean THEN t.id END DESC
LIMIT $6
`

type ListTurnsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	AfterCreated pgtype.Timestamptz `json:"after_created"`
	Ascending    bool               `json:"ascending"`
	AfterID      pgtype.UUID        `json:"after_id"`
	PageLimit    int32              `json:"page_limit"`
}

func (q *Queries) ListTurns(ctx context.Context, arg ListTurnsParams) ([]PublicExecutionTurn, error) {
	rows, err := q.db.Query(ctx, listTurns,
		arg.TenantID,
		arg.SessionID,
		arg.AfterCreated,
		arg.Ascending,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicExecutionTurn{}
	for rows.Next() {
		var i PublicExecutionTurn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CancelRequestedAt,
			&i.Outcome,
			&i.TokenUsage,
			&i.ArtifactCaptureStarted,
			&i.SubagentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
