// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: write_audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredWriteOperations = `-- name: DeleteExpiredWriteOperations :execrows
DELETE FROM write_audit_operations WHERE id IN (
  SELECT a.id FROM write_audit_operations a
  WHERE a.created_at < $1 AND NOT EXISTS (SELECT 1 FROM write_audit_owners o WHERE o.operation_id = a.id)
  ORDER BY a.created_at, a.id LIMIT $2
  FOR UPDATE SKIP LOCKED
)
`

type DeleteExpiredWriteOperationsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) DeleteExpiredWriteOperations(ctx context.Context, arg DeleteExpiredWriteOperationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredWriteOperations, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResourceOwners = `-- name: GetResourceOwners :many
SELECT o.resource_id, a.key_id, a.key_name, a.key_prefix, a.key_kind, k.revoked_at
FROM write_audit_owners o
JOIN write_audit_operations a ON a.tenant_id = o.tenant_id AND a.id = o.operation_id
LEFT JOIN project_api_keys k ON k.tenant_id = a.tenant_id AND k.id = CASE WHEN a.key_kind = 'issued' THEN a.key_id::uuid END
WHERE o.tenant_id = $1 AND o.resource_type = $2 AND o.resource_id = ANY($3::text[])
`

type GetResourceOwnersParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ResourceType string      `json:"resource_type"`
	Column3      []string    `json:"column_3"`
}

type GetResourceOwnersRow struct {
	ResourceID string             `json:"resource_id"`
	KeyID      string             `json:"key_id"`
	KeyName    string             `json:"key_name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyKind    string             `json:"key_kind"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetResourceOwners(ctx context.Context, arg GetResourceOwnersParams) ([]GetResourceOwnersRow, error) {
	rows, err := q.db.Query(ctx, getResourceOwners, arg.TenantID, arg.ResourceType, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetResourceOwnersRow{}
	for rows.Next() {
		var i GetResourceOwnersRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.KeyID,
			&i.KeyName,
			&i.KeyPrefix,
			&i.KeyKind,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWriteAuditCursor = `-- name: GetWriteAuditCursor :one
SELECT created_at FROM write_audit_operations WHERE tenant_id = $1 AND id = $2
`

type GetWriteAuditCursorParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetWriteAuditCursor(ctx context.Context, arg GetWriteAuditCursorParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getWriteAuditCursor, arg.TenantID, arg.ID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertWriteAuditOperation = `-- name: InsertWriteAuditOperation :one
INSERT INTO write_audit_operations (id, tenant_id, key_id, key_name, key_prefix, key_kind, action, resource_type, resource_id, parent_id, request_id, trace_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT (tenant_id, request_id) DO NOTHING
RETURNING id
`

type InsertWriteAuditOperationParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	KeyID        string      `json:"key_id"`
	KeyName      string      `json:"key_name"`
	KeyPrefix    string      `json:"key_prefix"`
	KeyKind      string      `json:"key_kind"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	ParentID     string      `json:"parent_id"`
	RequestID    string      `json:"request_id"`
	TraceID      string      `json:"trace_id"`
}

func (q *Queries) InsertWriteAuditOperation(ctx context.Context, arg InsertWriteAuditOperationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertWriteAuditOperation,
		arg.ID,
		arg.TenantID,
		arg.KeyID,
		arg.KeyName,
		arg.KeyPrefix,
		arg.KeyKind,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ParentID,
		arg.RequestID,
		arg.TraceID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertWriteAuditOwner = `-- name: InsertWriteAuditOwner :exec
INSERT INTO write_audit_owners (tenant_id, resource_type, resource_id, parent_id, operation_id)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (tenant_id, resource_type, resource_id) DO NOTHING
`

type InsertWriteAuditOwnerParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	ParentID     string      `json:"parent_id"`
	OperationID  pgtype.UUID `json:"operation_id"`
}

func (q *Queries) InsertWriteAuditOwner(ctx context.Context, arg InsertWriteAuditOwnerParams) error {
	_, err := q.db.Exec(ctx, insertWriteAuditOwner,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.ParentID,
		arg.OperationID,
	)
	return err
}

const listWriteOperations = `-- name: ListWriteOperations :many
SELECT a.id, a.tenant_id, a.key_id, a.key_name, a.key_prefix, a.key_kind, a.action, a.resource_type, a.resource_id, a.parent_id, a.request_id, a.trace_id, a.created_at, k.revoked_at
FROM write_audit_operations a
LEFT JOIN project_api_keys k ON k.tenant_id = a.tenant_id AND k.id = CASE WHEN a.key_kind = 'issued' THEN a.key_id::uuid END
WHERE a.tenant_id = $1
  AND ($2::text = '' OR a.key_id = $2)
  AND ($3::text = '' OR a.resource_type = $3)
  AND ($4::text = '' OR a.resource_id = $4)
  AND ($5::timestamptz IS NULL OR a.created_at >= $5)
  AND ($6::timestamptz IS NULL OR a.created_at < $6)
  AND ($7::timestamptz IS NULL OR (a.created_at, a.id) < ($7, $8::uuid))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $9
`

type ListWriteOperationsParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	KeyID         string             `json:"key_id"`
	ResourceType  string             `json:"resource_type"`
	ResourceID    string             `json:"resource_id"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	AfterTime     pgtype.Timestamptz `json:"after_time"`
	AfterID       pgtype.UUID        `json:"after_id"`
	PageLimit     int32              `json:"page_limit"`
}

type ListWriteOperationsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	KeyID        string             `json:"key_id"`
	KeyName      string             `json:"key_name"`
	KeyPrefix    string             `json:"key_prefix"`
	KeyKind      string             `json:"key_kind"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	ParentID     string             `json:"parent_id"`
	RequestID    string             `json:"request_id"`
	TraceID      string             `json:"trace_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListWriteOperations(ctx context.Context, arg ListWriteOperationsParams) ([]ListWriteOperationsRow, error) {
	rows, err := q.db.Query(ctx, listWriteOperations,
		arg.TenantID,
		arg.KeyID,
		arg.ResourceType,
		arg.ResourceID,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.AfterTime,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWriteOperationsRow{}
	for rows.Next() {
		var i ListWriteOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KeyID,
			&i.KeyName,
			&i.KeyPrefix,
			&i.KeyKind,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ParentID,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
