// Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.
package engine

var qualified = NewCatalog(map[string]Profile{
	"claude_sdk": claudeProfile(),
	"codex":      codexProfile(),
	"mcode":      mcodeProfile(),
})
