#!/usr/bin/env python3
"""Render the config.json reference table in docs/configuration.md from its schema.

Usage: scripts/config-reference.py [--check]
--check fails when the table differs from deploy/install/config.schema.json.
"""
import json
import pathlib
import sys

REPOSITORY = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY / "deploy/install"))
import config_model  # noqa: E402

DOCUMENT = REPOSITORY / "docs/configuration.md"
BEGIN = "<!-- BEGIN config-reference: generated by scripts/config-reference.py from deploy/install/config.schema.json -->"
END = "<!-- END config-reference -->"
CHECKS = {"origin": "canonical origin; HTTP only on loopback", "https_origin": "canonical HTTPS origin",
          "go_duration": "Go duration", "go_duration_min_1h": "Go duration, at least `1h`"}


def code(value):
    return "`" + json.dumps(value, ensure_ascii=False) + "`" if not isinstance(value, str) else f'`"{value}"`'


def kind(node):
    if "const" in node:
        return code(node["const"])
    if "enum" in node:
        return " \\| ".join(code(item) for item in node["enum"])
    types = node.get("type", [])
    types = [types] if isinstance(types, str) else list(types)
    names = []
    for name in types:
        if name == "array":
            names.append("array of " + kind(node.get("items", {})))
        elif name == "object" and isinstance(node.get("additionalProperties"), dict):
            names.append("object of " + kind(node["additionalProperties"]) + " values")
        else:
            names.append(name)
    text = " or ".join(names)
    if "minimum" in node and "maximum" in node:
        text += f' {node["minimum"]}–{node["maximum"]}'
    elif "minimum" in node:
        text += f' ≥ {node["minimum"]}'
    check = config_model.annotation(node, "check")
    if check:
        text += f" ({CHECKS[check]})"
    return text


def rows(node=None, prefix="", modes=config_model.MODES):
    """Leaves, plus nullable objects such as core.runtime_history, in schema order."""
    node = config_model.SCHEMA if node is None else node
    for name, child in node["properties"].items():
        child_modes = tuple(config_model.annotation(child, "modes", modes))
        if "properties" not in child or "default" in child:
            yield prefix + name, child, child_modes
        if "properties" in child:
            yield from rows(child, prefix + name + ".", child_modes)


def table():
    lines = ["| Key | Type | Default | Modes | Change | Restarts | Meaning |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    for key, node, modes in rows():
        annotation = lambda name, default=None: config_model.annotation(node, name, default)
        default = code(node["default"]) if "default" in node else "none"
        scope = "all" if set(modes) == set(config_model.MODES) else ", ".join(f"`{mode}`" for mode in modes)
        change = ("fixed" if not annotation("changeable", True)
                  else "`parsar apply`" if annotation("setting", True) else "any time")
        restarts = ", ".join(annotation("restarts", [])) or "none"
        if annotation("native_restarts"):
            restarts += " (" + ", ".join(annotation("native_restarts")) + " with native Core)"
        meaning = node.get("description", "")
        if annotation("sensitive"):
            meaning += " Sensitive."
        if annotation("install_flag"):
            meaning += " Install flag: " + " or ".join(f"`{flag}`" for flag in annotation("install_flag").split(" or ")) + "."
        lines.append(f"| `{key}` | {kind(node)} | {default} | {scope} | {change} | {restarts} | {meaning.strip()} |")
    return "\n".join(lines)


def main(argv):
    text = DOCUMENT.read_text()
    before, found, rest = text.partition(BEGIN + "\n")
    _, found_end, after = rest.partition(END)
    if not found or not found_end:
        sys.exit(f"{DOCUMENT} lacks the config-reference markers")
    rendered = before + BEGIN + "\n" + table() + "\n" + END + after
    if argv == ["--check"]:
        if rendered != text:
            sys.exit(f"{DOCUMENT.relative_to(REPOSITORY)} is out of date; run scripts/config-reference.py")
        return
    if argv:
        sys.exit(__doc__.strip())
    DOCUMENT.write_text(rendered)


if __name__ == "__main__":
    main(sys.argv[1:])
