#!/usr/bin/env python3
"""Generate static Harness registrations; native execution stays in adapters."""

import argparse
import json
from pathlib import Path
import re
import subprocess
from pprint import pformat

ROOT = Path(__file__).resolve().parent.parent
CATALOG = Path("internal/harnessconfig/builtin/catalog.json")
MODULE = "github.com/MiniMax-AI/OpenAgentCore"
HEADER = "// Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.\n"


def load_catalog(path):
    entries = json.loads(path.read_text())
    if not isinstance(entries, list) or not entries:
        raise ValueError("Harness catalog must be a nonempty list")
    kinds = set()
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != {"kind", "label", "configuration", "version"}:
            raise ValueError("Invalid Harness catalog fields")
        if any(not isinstance(value, str) for value in entry.values()):
            raise ValueError("Harness catalog values must be strings")
        if not re.fullmatch(r"[a-z][a-z0-9_]*", entry["kind"]) or entry["kind"] in kinds:
            raise ValueError("Invalid or duplicate Harness kind")
        if not re.fullmatch(r"[a-z][a-z0-9]*", entry["configuration"]):
            raise ValueError("Invalid configuration package")
        if not entry["label"].strip() or any(c in entry["label"] for c in "\n\r\t|"):
            raise ValueError("Invalid Harness label")
        if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", entry["version"]):
            raise ValueError("Invalid pinned Harness version")
        kinds.add(entry["kind"])
    return sorted(entries, key=lambda entry: entry["kind"])


def go(source, build=""):
    return subprocess.run(["gofmt"], input=build + HEADER + source, text=True,
                          check=True, capture_output=True).stdout


def render_installer(providers):
    return ("# Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.\n"
            "# Provider support comes from the adapter-owned Go configuration declarations.\n"
            "PROVIDERS = " + pformat(providers, sort_dicts=True, width=100) + "\n")


def render_client(entries, protocols):
    kinds = ", ".join(json.dumps(entry["kind"]) for entry in entries)
    labels = "\n".join(f'  {json.dumps(entry["kind"])}: {json.dumps(entry["label"])},' for entry in entries)
    return HEADER + f'''
export const coreHarnessKinds = [{kinds}] as const;
export type CoreHarnessKind = (typeof coreHarnessKinds)[number];
export const coreHarnessNames: Record<CoreHarnessKind, string> = {{
{labels}
}};
export const modelProviderProtocols = [{", ".join(json.dumps(protocol) for protocol in protocols)}] as const;
export type ModelProviderProtocol = (typeof modelProviderProtocols)[number];
'''


def render(entries):
    packages = sorted({entry["configuration"] for entry in entries})
    imports = "\n".join(f'\t"{MODULE}/internal/harnessconfig/{package}"' for package in packages)
    configurations = "\n".join(
        f'\t{json.dumps(entry["kind"])}: {entry["configuration"]}.Configuration(),'
        for entry in entries)
    declarations = ", ".join(f'{entry["configuration"]}.Declaration' for entry in entries)
    installations = ", ".join(f'{entry["configuration"]}.Installation()' for entry in entries)
    adapter_imports = "\n".join(f'\t"{MODULE}/apps/daemon/internal/agent/{package}"' for package in packages)
    kinds = ", ".join(json.dumps(entry["kind"]) for entry in entries)
    tick = chr(96)
    rows = "\n".join(
        f'| {tick}{e["kind"]}{tick} | {e["label"]} | {tick}{e["version"]}{tick} | {tick}{e["configuration"]}.Configuration{tick} |'
        for e in entries)
    result = {
        Path("apps/daemon/internal/cli/harness_catalog_linux.go"): go(f'''package cli

import (
    "{MODULE}/apps/daemon/internal/agent"
{adapter_imports}
)

var harnessDeclarations = []agent.Declaration{{{declarations}}}
var harnessInstallations = []agent.Installation{{{installations}}}
''', build="//go:build linux\n\n"),
        Path("internal/harnessconfig/builtin/registry.go"): go(f'''package builtin

import (
    "{MODULE}/internal/harnessconfig"
{imports}
)

var registry = harnessconfig.NewRegistry(map[string]harnessconfig.Configuration{{
{configurations}
}})

func Registry() harnessconfig.Registry {{ return registry }}

// Configuration binds a registered public Harness to its authored declaration.
func Configuration(kind string) harnessconfig.Configuration {{
    configuration, ok := registry.Lookup(kind)
    if !ok {{ panic("unregistered public Harness configuration") }}
    return configuration
}}

// Kinds returns the public identifiers in this build, not Runtime availability.
func Kinds() []string {{ return []string{{{kinds}}} }}

func Contains(kind string) bool {{
    _, ok := registry.Lookup(kind)
    return ok
}}
'''),
        Path("contracts/agents-api/harness-catalog.md"): f'''[//]: # (Generated by scripts/generate-harness-catalog.py; DO NOT EDIT.)
# Built-in Harness registrations

The authored registration list and Harness version pins are [{tick}catalog.json{tick}](https://github.com/MiniMax-AI/OpenAgentCore/blob/main/internal/harnessconfig/builtin/catalog.json). Change it and run {tick}make generate-harness-catalog{tick}; {tick}make check-harness-catalog{tick} checks the generated projections.

| Identifier | Display name | Version | Declaration |
| --- | --- | --- | --- |
{rows}

Each declaration in {tick}internal/harnessconfig/<package>{tick} states the Harness's model providers and its support, the only source Core and the Runtime admit a selection against. These registrations describe the build. Which Harnesses a deployment enables is the {tick}core.harnesses{tick} [process setting](../../docs/configuration.md#settings), and a connected Runtime reports its own availability. [Harness onboarding](./harness-onboarding.md) describes the adapter and packaging steps.
''',
        Path("contracts/agents-api/zh/harness-catalog.md"): f'''[//]: # (Generated by scripts/generate-harness-catalog.py; DO NOT EDIT.)
# 内置 Harness 注册 {{#built-in-harness-registrations}}

注册列表和 Harness 版本固定值的源文件是 [{tick}catalog.json{tick}](https://github.com/MiniMax-AI/OpenAgentCore/blob/main/internal/harnessconfig/builtin/catalog.json)。修改后运行 {tick}make generate-harness-catalog{tick}；{tick}make check-harness-catalog{tick} 检查生成结果。

| 标识符 | 显示名称 | 版本 | 声明 |
| --- | --- | --- | --- |
{rows}

{tick}internal/harnessconfig/<package>{tick} 中的声明给出 Harness 的模型提供方及其支持范围，是 Core 和 Runtime 准入选择的唯一依据。这些注册描述当前构建。部署启用的 Harness 由 {tick}core.harnesses{tick} [进程设置](../../../docs/zh/configuration.md#settings)决定，连接的 Runtime 报告自身可用性。[Harness 接入](./harness-onboarding.md)介绍适配器和打包步骤。
''',
    }

    for entry in entries:
        package = entry["configuration"]
        result[Path(f"internal/harnessconfig/{package}/version.go")] = go(
            f'package {package}\n\n// NativeVersion is the packaged native Harness version.\nconst NativeVersion = {json.dumps(entry["version"])}\n')
    return result


def render_manifests(entries, root):
    versions = {entry["kind"]: entry["version"] for entry in entries}
    result = {}
    # Keep package-manager and standalone artifact manifests in their native
    # formats. Only the Harness version is a projection; other fields retain
    # their existing owners.
    for kind, relative in (("claude_sdk", "packages/claude-sdk-adapter/package.json"),
                           ("mcode", "packages/mcode-harness/source.json")):
        if kind not in versions:
            continue
        path = Path(relative)
        manifest = json.loads((root / path).read_text())
        if kind == "claude_sdk":
            manifest["dependencies"]["@anthropic-ai/claude-agent-sdk"] = versions[kind]
        else:
            manifest["version"] = versions[kind]
        result[path] = json.dumps(manifest, indent=2) + "\n"
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    entries = load_catalog(ROOT / CATALOG)
    stale = []

    def projection(relative, content):
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(relative))
        else:
            path.write_text(content)

    for relative, content in (render(entries) | render_manifests(entries, ROOT)).items():
        projection(relative, content)
    # Refresh the Go registration before loading the adapter declarations. In check
    # mode a stale registration must fail before its declarations can be projected.
    if stale:
        raise SystemExit("Stale Harness catalog projections; run make generate-harness-catalog:\n" + "\n".join(stale))
    declared = json.loads(subprocess.run(["go", "run", "./scripts/harness-catalog"], cwd=ROOT,
                                        text=True, check=True, capture_output=True).stdout)
    projection(Path("scripts/acceptance/harness_catalog.py"), render_installer(declared["harnesses"]))
    projection(Path("packages/agents-client/src/harness-catalog.ts"), render_client(entries, declared["protocols"]))
    if stale:
        raise SystemExit("Stale Harness catalog projections; run make generate-harness-catalog:\n" + "\n".join(stale))


if __name__ == "__main__":
    main()
