#!/usr/bin/env python3
"""Generate static Harness registrations; native execution stays in adapters."""

import argparse
import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent
CATALOG = Path("internal/harnessconfig/builtin/catalog.json")
MODULE = "github.com/MiniMax-AI/OpenAgentCore"
HEADER = "// Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.\n"


def load_catalog(path):
    entries = json.loads(path.read_text())
    if not isinstance(entries, list) or not entries:
        raise ValueError("Harness catalog must be a nonempty list")
    kinds = set()
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != {"kind", "label", "configuration", "profile"}:
            raise ValueError("Invalid Harness catalog fields")
        if any(not isinstance(value, str) for value in entry.values()):
            raise ValueError("Harness catalog values must be strings")
        if not re.fullmatch(r"[a-z][a-z0-9_]*", entry["kind"]) or entry["kind"] in kinds:
            raise ValueError("Invalid or duplicate Harness kind")
        if not re.fullmatch(r"[a-z][a-z0-9]*", entry["configuration"]):
            raise ValueError("Invalid configuration package")
        if not re.fullmatch(r"[a-z][A-Za-z0-9]*", entry["profile"]):
            raise ValueError("Invalid profile constructor")
        if not entry["label"].strip() or any(c in entry["label"] for c in "\n\r\t|"):
            raise ValueError("Invalid Harness label")
        kinds.add(entry["kind"])
    return sorted(entries, key=lambda entry: entry["kind"])


def go(source):
    return subprocess.run(["gofmt"], input=HEADER + source, text=True,
                          check=True, capture_output=True).stdout


def render(entries):
    packages = sorted({entry["configuration"] for entry in entries})
    imports = "\n".join(f'\t"{MODULE}/internal/harnessconfig/{package}"' for package in packages)
    configurations = "\n".join(
        f'\t{json.dumps(entry["kind"])}: {entry["configuration"]}.Configuration(),'
        for entry in entries)
    kinds = ", ".join(json.dumps(entry["kind"]) for entry in entries)
    profiles = "\n".join(
        f'\t{json.dumps(entry["kind"])}: {entry["profile"]}(),' for entry in entries)
    labels = "\n".join(f'  {json.dumps(entry["kind"])}: {json.dumps(entry["label"])},' for entry in entries)
    tick = chr(96)
    rows = "\n".join(
        f'| {tick}{e["kind"]}{tick} | {e["label"]} | {tick}{e["configuration"]}.Configuration{tick} | {tick}{e["profile"]}{tick} |'
        for e in entries)
    return {
        Path("internal/harnessconfig/builtin/registry.go"): go(f'''package builtin

import (
    "{MODULE}/internal/harnessconfig"
{imports}
)

var registry = harnessconfig.NewRegistry(map[string]harnessconfig.Configuration{{
{configurations}
}})

func Registry() harnessconfig.Registry {{ return registry }}

// Configuration binds a registered public Harness to its authored declaration.
func Configuration(kind string) harnessconfig.Configuration {{
    configuration, ok := registry.Lookup(kind)
    if !ok {{ panic("unregistered public Harness configuration") }}
    return configuration
}}

// Kinds returns the public identifiers in this build, not Runtime availability.
func Kinds() []string {{ return []string{{{kinds}}} }}

func Contains(kind string) bool {{
    _, ok := registry.Lookup(kind)
    return ok
}}
'''),
        Path("services/core/internal/engine/catalog_generated.go"): go(f'''package engine

var qualified = NewCatalog(map[string]Profile{{
{profiles}
}})
'''),
        Path("packages/agents-client/src/harness-catalog.ts"): HEADER + f'''
export const coreHarnessKinds = [{kinds}] as const;
export type CoreHarnessKind = (typeof coreHarnessKinds)[number];
export const coreHarnessNames: Record<CoreHarnessKind, string> = {{
{labels}
}};
''',
        Path("contracts/agents-api/harness-catalog.md"): f'''<!-- Generated by scripts/generate-harness-catalog.py; DO NOT EDIT. -->
# Built-in Harness registrations

The authored registration list is
[{tick}catalog.json{tick}](../../internal/harnessconfig/builtin/catalog.json).
Change it and run {tick}make generate-harness-catalog{tick}; generated projections are checked
by {tick}make check-harness-catalog{tick}.

| Identifier | Display name | Model configuration declaration | Core qualification constructor |
| --- | --- | --- | --- |
{rows}

Configuration declarations live in {tick}internal/harnessconfig/<package>{tick};
qualification constructors live in {tick}services/core/internal/engine{tick}.
These registrations describe the build. Deployment enablement, qualified
operations and a connected Runtime's actual availability remain separate checks.
See [Harness onboarding](harness-onboarding.md) for adapter and packaging steps.
''',
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for relative, content in render(load_catalog(ROOT / CATALOG)).items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(relative))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Stale Harness catalog projections; run make generate-harness-catalog:\n" + "\n".join(stale))


if __name__ == "__main__":
    main()
