# Code generated by contractgen; DO NOT EDIT.
"""Adapter-private wire declarations. No SDK or repository dependency."""
ERROR_CODES = ["","invalid","ownership","exists","not_found","command_unconfirmed","unconfirmed","template_invalid","team_mismatch","unauthorized"]
MANAGED_BOOTSTRAP_FIELDS = ["TenantID","EnvironmentID","AllocationID","SessionID","DeviceID","NetworkAccess","AllowedDomains","InstallationID","RuntimeBootstrap"]
MANAGED_IDENTITY_FIELDS = ["TenantID","EnvironmentID","AllocationID","SessionID","DeviceID","InstallationID"]
MAX_COMMAND_INPUT = 52428832
MAX_CREDENTIAL_REFERENCES = 32
MAX_OBSERVATION_REFERENCES = 100
MAX_OUTPUT = 1048576
MAX_REQUEST = 75497472
MAX_RESPONSE = 16777216
NETWORK_ACCESS = ["enabled","disabled","restricted"]
OPERATIONS = ["create","inspect","renew","kill","command","validate_deployment","observe","list_templates","list_builds","verify_credential"]
PROTOCOL_VERSION = 1
REFERENCE_FIELDS = ["TenantID","EnvironmentID","AllocationID"]
REQUEST_FIELDS = ["Version","Operation","Config","Reference","References","Bootstrap","RuntimeBootstrap","Command","Deadline"]
RESPONSE_FIELDS = ["Version","Info","Command","ErrorCode","DeploymentValid","TemplateBuild","Templates","Builds","Observations"]
SDK_VERSION = "2.51.0"
