# Code generated by contractgen; DO NOT EDIT.
"""Adapter-private wire declarations. No SDK or repository dependency."""
ERROR_CODES = ["","invalid","ownership","exists","not_found","unconfirmed","template_invalid","team_mismatch","unauthorized"]
MANAGED_BOOTSTRAP_FIELDS = ["TenantID","EnvironmentID","AllocationID","SandboxIO","InstallationID"]
MANAGED_IDENTITY_FIELDS = ["TenantID","EnvironmentID","AllocationID","InstallationID"]
MAX_CREDENTIAL_REFERENCES = 32
MAX_OUTPUT = 1048576
MAX_REQUEST = 1048576
MAX_RESPONSE = 16777216
OPERATIONS = ["create","inspect","renew","kill","validate_deployment","observe","list_templates","list_builds","verify_credential"]
PROTOCOL_VERSION = 1
REFERENCE_FIELDS = ["TenantID","EnvironmentID","AllocationID"]
REQUEST_FIELDS = ["Version","Operation","Config","Reference","References","Bootstrap","Deadline"]
RESPONSE_FIELDS = ["Version","Info","ErrorCode","DeploymentValid","TemplateBuild","Templates","Builds","Observation"]
SDK_VERSION = "2.51.0"
