// Code generated by scripts/generate-harness-catalog.py; DO NOT EDIT.
package builtin

import (
	"github.com/MiniMax-AI-Dev/parsar/internal/harnessconfig"
	"github.com/MiniMax-AI-Dev/parsar/internal/harnessconfig/claudesdk"
	"github.com/MiniMax-AI-Dev/parsar/internal/harnessconfig/codex"
	"github.com/MiniMax-AI-Dev/parsar/internal/harnessconfig/mcode"
)

var registry = harnessconfig.NewRegistry(map[string]harnessconfig.Configuration{
	"claude_sdk": claudesdk.Configuration(),
	"codex":      codex.Configuration(),
	"mcode":      mcode.Configuration(),
})

func Registry() harnessconfig.Registry { return registry }

// Configuration binds a registered public Harness to its authored declaration.
func Configuration(kind string) harnessconfig.Configuration {
	configuration, ok := registry.Lookup(kind)
	if !ok {
		panic("unregistered public Harness configuration")
	}
	return configuration
}

// Kinds returns the public identifiers in this build, not Runtime availability.
func Kinds() []string { return []string{"claude_sdk", "codex", "mcode"} }

func Contains(kind string) bool {
	_, ok := registry.Lookup(kind)
	return ok
}
