export const apiKeyChinese = {
  "My API key": "我的 API 密钥",
  "API key management is not enabled": "API 密钥管理尚未启用",
  "A deployment administrator needs to enable key management for this console. You can then create, view and delete keys here.": "需要部署管理员为此控制台启用密钥管理，之后即可在这里创建、查看和删除密钥。",
  "If you already have an Agent API key, you can keep using it for requests from your machine or application.": "如果你已有 Agent API 密钥，仍可使用它从本机或应用发起请求。",
  "Check again": "重新检查",
  "You can continue the introduction and use your signed-in console connection to create an Agent.": "你可以继续导览，并通过已登录的控制台连接创建 Agent。",
  "Checking API key management…": "正在检查 API 密钥管理功能…",
  "Could not check API key management. Try again.": "暂时无法检查 API 密钥管理功能，请重试。",
  "Retry this creation": "重试这次创建",
  "API keys": "API 密钥",
  "Give your machine a secure way to call Agent Core.": "让你的机器安全地调用 Agent Core。",
  "Create a key": "创建密钥",
  "Name it so you can recognize it later.": "取一个容易辨认的名称。",
  "How an API key works": "API 密钥如何使用",
  "A request in three beats": "一次请求，三个步骤",
  "Create once. Call your API.": "创建一次，就能调用 API。",
  "Your key connects a request from your machine to Agent Core.": "密钥让你的机器向 Agent Core 发起请求。",
  "Send a request": "发起请求",
  "See the result": "查看结果",
  "View a curl example": "查看 curl 示例",
  "This read-only request lists Agents. The same key can also create Agents and Sessions.": "此只读请求会列出 Agent。同一枚密钥也可用于创建 Agent 和 Session。",
  "Set AGENT_CORE_API_KEY in a terminal that can reach this address.": "在能访问此地址的终端设置 AGENT_CORE_API_KEY。",
  "Copy curl": "复制 curl",
  "Command copied": "已复制命令",
  "Could not copy the command. Select and copy it manually.": "无法复制命令，请选中并手动复制。",
  "The secret appears once when you create it. Save it before closing the message.": "密钥内容只在创建时显示一次，请及时保存。",
  "Create a key for your API requests.": "为你的 API 请求创建一枚密钥。",
  "Use this key when calling Agent API from your own machine or application.": "从本机或应用调用 Agent API 时，带上这枚密钥即可。",
  "Your Web password is for signing in. This key is for API requests.": "Web 密码用于登录控制台，这枚密钥用于调用 API。",
  "Key name": "密钥名称",
  "Create API key": "创建 API 密钥",
  "Creating key…": "正在创建密钥…",
  "Keep this key somewhere safe. It is shown only now.": "请妥善保存这枚密钥，它只会在这里显示一次。",
  "Your new API key": "你的新 API 密钥",
  "Copy key": "复制密钥",
  "I've saved this key": "我已保存这枚密钥",
  "Loading API keys…": "正在读取 API 密钥…",
  "Refresh keys": "刷新密钥",
  "Could not load your keys. Try refreshing.": "暂时无法读取密钥，请刷新重试。",
  "Key management is not connected. Check the paired Core configuration.": "密钥管理尚未连接，请检查配套 Core 的配置。",
  "Could not confirm key creation. Refresh the list before doing anything else.": "暂时无法确认创建结果，请先刷新密钥列表。",
  "This key was created, but its secret cannot be shown again. Delete it and create a new key.": "密钥已创建，但无法再次显示内容。请删除它后创建新密钥。",
  "Check the key name and try again.": "请检查密钥名称后重试。",
  "Select the key and copy it manually.": "请选择密钥内容并手动复制。",
  "Active keys": "有效密钥",
  "No active keys. Create one to call the API.": "暂无有效密钥。创建一枚即可调用 API。",
  "Delete": "删除",
  "Delete key": "删除密钥",
  "Delete this API key? It will stop authenticating new requests and disappear from this list. Existing Agents and Sessions remain.": "删除这枚 API 密钥？它将立即无法用于后续请求，并从当前列表移除。已有 Agent 和 Session 不受影响。",
  "Cancel": "取消",
  "Could not confirm deletion. Refresh the list to check its status.": "暂时无法确认删除结果，请刷新列表检查状态。",
  "API key ready": "API 密钥已就绪",
  "Existing keys stay available. Create another only if you need one.": "已有密钥可以继续使用，需要时再创建新密钥。",
  "Save a key before continuing.": "保存一枚密钥后，就可以继续了。",
} as const;
