export const apiKeyChinese = {
  "Use an existing Agent API key.": "使用已有的 Agent API 密钥。",
  "This console cannot create API keys. Use a key supplied by your Core administrator for requests from your machine or application.": "此控制台无法创建 API 密钥。从本机或应用发起请求时，请使用 Core 管理员提供的密钥。",
  "You can continue the introduction and use your signed-in console connection to create an Agent.": "你可以继续导览，并通过已登录的控制台连接创建 Agent。",
  "Checking API key management…": "正在检查 API 密钥管理功能…",
  "Could not check API key management. Try again.": "暂时无法检查 API 密钥管理功能，请重试。",
  "Retry this creation": "重试这次创建",
  "API keys": "API 密钥",
  "Create a key for your API requests.": "为你的 API 请求创建一枚密钥。",
  "Use this key when calling Agent API from your own machine or application.": "从本机或应用调用 Agent API 时，带上这枚密钥即可。",
  "Your Web password is for signing in. This key is for API requests.": "Web 密码用于登录控制台，这枚密钥用于调用 API。",
  "Key name": "密钥名称",
  "Create API key": "创建 API 密钥",
  "Creating key…": "正在创建密钥…",
  "Keep this key somewhere safe. It is shown only now.": "请妥善保存这枚密钥，它只会在这里显示一次。",
  "Your new API key": "你的新 API 密钥",
  "Copy key": "复制密钥",
  "I've saved this key": "我已保存这枚密钥",
  "Loading API keys…": "正在读取 API 密钥…",
  "Refresh keys": "刷新密钥",
  "Could not load your keys. Try refreshing.": "暂时无法读取密钥，请刷新重试。",
  "Key management is not connected. Check the paired Core configuration.": "密钥管理尚未连接，请检查配套 Core 的配置。",
  "Could not confirm key creation. Refresh the list before doing anything else.": "暂时无法确认创建结果，请先刷新密钥列表。",
  "This key was created, but its secret cannot be shown again. Revoke it and create a new key.": "密钥已创建，但无法再次显示内容。请撤销它后创建新密钥。",
  "Check the key name and try again.": "请检查密钥名称后重试。",
  "Select the key and copy it manually.": "请选择密钥内容并手动复制。",
  "No API keys yet. Create one to get started.": "还没有 API 密钥，创建一枚就可以开始调用。",
  "Active": "有效",
  "Revoked": "已撤销",
  "Revoke": "撤销",
  "Revoke this API key? Requests using it will stop working.": "撤销这枚 API 密钥？使用它的后续请求将无法通过认证。",
  "Confirm revocation": "确认撤销",
  "Cancel": "取消",
  "Could not confirm revocation. Refresh the list to check its status.": "暂时无法确认撤销结果，请刷新列表检查状态。",
  "API key ready": "API 密钥已就绪",
  "Existing keys stay available. Create another only if you need one.": "已有密钥可以继续使用，需要时再创建新密钥。",
  "Save a key before continuing.": "保存一枚密钥后，就可以继续了。",
} as const;
