export const consoleAuthChinese = {
  "Try again": "重试",
  "Copied": "已复制",
  "A place for your Agents to work.": "让你的 Agent 在这里工作。",
  "Connect your machines. Create Agents. Watch work happen.": "连接自己的机器，创建 Agent，让工作在这里发生。",
  "Create your administrator account": "创建管理员账户",
  "You manage this cloud.": "这片云，由你管理。",
  "Use your administrator account to continue.": "使用管理员账户继续。",
  "Welcome back": "欢迎回来",
  "Administrator username": "管理员用户名",
  "Password": "密码",
  "Confirm password": "确认密码",
  "12–72 bytes. Keep this password somewhere safe.": "12–72 字节，请妥善保管这个密码。",
  "Letters, numbers, dots, underscores and hyphens.": "支持英文字母、数字、点、下划线和短横线。",
  "Create administrator account": "创建管理员账户",
  "Sign in": "登录",
  "Signing in…": "正在登录…",
  "Creating account…": "正在创建账户…",
  "Passwords do not match.": "两次输入的密码不一致。",
  "Use a password between 12 and 72 bytes.": "请使用 12–72 字节的密码。",
  "Check your sign-in details and try again.": "请检查登录信息后重试。",
  "Check the account details and try again.": "请检查账户信息后重试。",
  "An administrator already exists. Sign in to continue.": "管理员账户已创建，请登录继续。",
  "Too many attempts. Wait a moment before trying again.": "尝试次数过多，请稍后再试。",
  "Could not confirm the result. Check the account status before trying again.": "暂时无法确认结果，请先检查账户状态。",
  "Check account status": "检查账户状态",
  "Connecting to your console…": "正在连接控制台…",
  "Could not connect to your console.": "暂时无法连接控制台。",
  "Sign out": "退出登录",
  "Signing out…": "正在退出…",
  "Could not sign out. Try again.": "退出失败，请重试。",
  "Console language": "控制台语言",
  "Getting started": "开始使用",
  "Continue setup": "继续设置",
  "Replay introduction": "再次查看引导",
} as const;
