export const consoleAuthChinese = {
  "Try again": "重试",
  "Sign in to Parsar Core": "登录 Parsar Core",
  "Core key": "Core Key",
  "This deployment's Core key. The installer saved it in a private file: {{file}} in the installation directory, by default {{defaultPath}}. It is an administration credential: it cannot call the /v1 Agents API, and the console never keeps it in your browser.":
    "这个部署的 Core Key，由安装器保存在安装目录下的私有文件 {{file}} 中，默认是 {{defaultPath}}。它是管理凭据：不能调用 /v1 Agents API，控制台也不会把它保存在你的浏览器里。",
  "Sign in": "登录",
  "Signing in…": "正在登录…",
  "This Core key is not correct. Check it and try again.": "Core Key 不正确，请检查后重试。",
  "Too many attempts. Try again in {{seconds}} seconds.": "尝试次数过多，请 {{seconds}} 秒后再试。",
  "Too many attempts. Wait a moment before trying again.": "尝试次数过多，请稍后再试。",
  "The console cannot check the key right now. Try again later.": "控制台暂时无法校验 Core Key，请稍后再试。",
  "Could not sign in. Try again.": "登录失败，请重试。",
  "Connecting to your console…": "正在连接控制台…",
  "Could not connect to your console.": "暂时无法连接控制台。",
  "Sign out": "退出登录",
  "Signing out…": "正在退出…",
  "Could not sign out. Try again.": "退出失败，请重试。",
  "Console language": "控制台语言",
} as const;
