export const firstRunChinese = {
  "You can edit and copy the request again. Check its result before sending another request.": "需要时可修改配置并重新复制。再次发送前，请先检查已有请求的结果。",
  "Request was rejected. Check your configuration and try again.": "请求被拒绝，请检查配置后重试。",
  "Agent configuration": "Agent 配置",
  "Fill in your Agent's settings. The request updates as you type.": "填写 Agent 配置，右侧请求代码会同步更新。",
  "Agent name": "Agent 名称",
  "Model ID": "模型 ID",
  "Harness": "执行引擎",
  "Deployment default": "使用部署默认值",
  "Instructions": "指令",
  "Set a model provider for this Agent": "为这个 Agent 配置模型服务",
  "Provider protocol": "模型服务协议",
  "Provider base URL": "模型服务地址",
  "Model API key": "模型 API key",
  "Only for Run here": "仅用于在此运行",
  "The local request asks for this key in your terminal. A key entered here is used only by Run here.": "本地运行时会在终端询问此 key。这里输入的 key 仅用于「在此运行」。",
  "Use the model provider configured for this deployment.": "使用此部署配置的模型服务。",
  "Run here": "在此运行",
  "Uses your signed-in console connection.": "使用当前已登录的控制台连接。",
  "Run locally. The request will ask for your Core API key and model key.": "在本地运行，请求会询问 Core API key 和模型 key。",
  "Run locally. The request will ask for your Core API key.": "在本地运行，请求会询问 Core API key。",
  "Complete the configuration to generate your request.": "填写配置后，这里会生成请求代码。",
  "Core API key authorizes this request. Model key authorizes your model provider.": "Core API key 用于访问 Core，模型 key 用于访问模型服务。",
  "Add this machine as a host. In hosted mode, Core creates and manages sandboxes on these hosts to provide resources for Agents.": "把这台机器添加为宿主机。使用 hosted 模式时，Core 会在这些宿主机上创建和管理沙箱，为 Agent 提供运行资源。",
  "Home": "首页",
  "Your Agent cloud starts here.": "你的 Agent 云，从这里开始。",
  "One deployment. Your machines. Your Agents.": "一个部署，连接你的机器，管理你的 Agent。",
  "Skip introduction": "跳过导览",
  "First steps": "开始使用",
  "Your access": "访问方式",
  "Your machines": "你的机器",
  "Your first Agent": "第一个 Agent",
  "Keep your sign-in details.": "保存你的登录信息。",
  "Use this address and administrator account to return to your console.": "下次使用这个地址和管理员账户登录控制台。",
  "Console address": "控制台地址",
  "Administrator": "管理员",
  "Signed-in administrator": "已登录的管理员",
  "Copy sign-in details": "复制登录信息",
  "Select the details and copy them manually.": "请选择登录信息并手动复制。",
  "I've saved it. Continue": "我已保存，继续",
  "This is your Agent cloud.": "这就是你的 Agent 云。",
  "Connect your own machine.": "连接你自己的机器。",
  "Add a machine with one command. Its connection will appear here.": "用一条命令添加机器，连接状态会在这里显示。",
  "Optional": "可选",
  "You can add more machines whenever you need them.": "需要时，你随时可以添加更多机器。",
  "Continue to the API": "继续体验 API",
  "Skip for now": "暂时跳过",
  "Make your first API request.": "发出第一个 API 请求。",
  "Create an Agent and see it here.": "创建一个 Agent，然后在这里看到它。",
  "Browser": "浏览器",
  "Run this in the browser console on this page, or use Run request.": "在当前页面的浏览器控制台运行，或点击「运行请求」。",
  "Core API base URL": "Core API 基础地址",
  "Enter the direct Core API URL, including /v1. Set CORE_API_KEY in your terminal.": "输入包含 /v1 的 Core API 直连地址，并在终端设置 CORE_API_KEY。",
  "Enter an HTTPS URL or a loopback HTTP URL without credentials, query parameters, or fragments.": "请输入 HTTPS 或回环 HTTP 地址，不含凭据、查询参数或片段。",
  "Copy request": "复制请求",
  "Run request": "运行请求",
  "Checking for your Agent…": "正在查找你的 Agent…",
  "Creating Agent…": "正在创建 Agent…",
  "Waiting for your request…": "等待你的请求…",
  "The request may have completed. Check for its Agent before trying another request.": "请求可能已完成。请先检查是否已创建 Agent。",
  "Unable to check the result. Your last state is kept here.": "暂时无法检查结果，这里保留上次的状态。",
  "Check result": "检查结果",
  "Agent created": "Agent 已创建",
  "Open Agent": "打开 Agent",
  "Finish introduction": "完成导览",
  "Your Agent will appear here": "你的 Agent 将出现在这里",
  "Run the request to create your first saved Agent.": "运行请求，创建你的第一个 Agent。",
  "Model": "模型",
  "Agent ID": "Agent ID",
  "Back": "上一步",
  "API documentation": "API 文档",
  "Use the console connection (/v1) to run this browser example.": "请使用控制台连接（/v1）运行浏览器示例。",
  "Select the request and copy it manually.": "请选择请求并手动复制。",
  "A copy is ready to run. We are watching for its Agent.": "请求已复制，运行后会在这里显示 Agent。",
} as const;
